-- SIX UNDERSTANDING ENGINE · 0009 · Seed lexicon and concept graph
-- Workroom: WR-SIXENGINE-001
--
-- GENERATED FILE. Do not edit by hand.
--   node six-engine/tools/generate-seed-sql.mjs > db/six-engine/0009_seed_lexicon_and_concepts.sql
--
-- The runtime lexicon in six-engine/lib/lexicon.js is the source. Generating
-- the rows from it is what stops the backend and the runtime from teaching
-- two different meanings of the same word.
--
-- Seeds are additive and re-runnable: every insert is ON CONFLICT DO NOTHING,
-- so a sense edited in the backend by a department is never overwritten by a
-- re-run of this migration.

begin;

-- Lexemes ---------------------------------------------------------------------
insert into sixu_lexemes (lemma, is_multiword, band) values
  ('left', false, 1),
  ('of', false, 1),
  ('each', false, 1),
  ('share', false, 1),
  ('more than', true, 2),
  ('less than', true, 2),
  ('altogether', false, 2),
  ('difference', false, 1),
  ('product', false, 1),
  ('table', false, 1),
  ('mean', false, 1),
  ('volume', false, 1),
  ('odd', false, 1),
  ('primary', false, 2),
  ('record', false, 1),
  ('consensus', false, 4),
  ('if', false, 1),
  ('not', false, 1),
  ('all', false, 1),
  ('some', false, 1),
  ('because', false, 1),
  ('per', false, 2),
  ('remaining', false, 2)
on conflict (lemma) do nothing;

-- Word senses -----------------------------------------------------------------
insert into sixu_word_senses (id, lemma, job, domains, band, meaning_here, substitute, example, non_example, invariant) values
  ('left#remainder', 'left', 'QUANTITY_REMAINDER'::sixu_sense_job, array['math','everyday'], 1,
   'how many are still there after some were taken away',
   'still there',
   'She had 5 apples and gave 2 away, so 3 are left.',
   'Turn left at the corner — that is a direction, not an amount.', false),
  ('left#direction', 'left', 'DIRECTION'::sixu_sense_job, array['everyday'], 1,
   'the side opposite your right hand',
   'that side',
   'Turn left at the shop.',
   'Three are left — that is an amount, not a side.', false),
  ('of#part', 'of', 'OPERATION_CUE'::sixu_sense_job, array['math'], 2,
   'here "of" means multiply — a part taken from an amount',
   'times',
   'Half of 12 means half times 12, which is 6.',
   'The lid of the jar — that "of" names what belongs to what.', true),
  ('of#belonging', 'of', 'STRUCTURE_TECHNICAL'::sixu_sense_job, array['everyday'], 1,
   'says what belongs to what',
   'belonging to',
   'The lid of the jar.',
   'A third of 9 — that "of" is a multiplication.', false),
  ('each#distributive', 'each', 'DISTRIBUTIVE'::sixu_sense_job, array['math','everyday'], 1,
   'the same amount goes to every one of them, one at a time',
   'every single one gets this much',
   '4 children get 3 sweets each — every child gets 3, not 3 between them.',
   '4 children share 3 sweets — that is one amount split, not 3 per child.', true),
  ('share#divide', 'share', 'OPERATION_CUE'::sixu_sense_job, array['math'], 1,
   'split one amount into equal parts',
   'split equally',
   '12 sweets shared between 4 children gives 3 each.',
   '4 children with 12 sweets each — that is not sharing, that is 12 per child.', true),
  ('share#portion', 'share', 'QUANTITY_TOTAL'::sixu_sense_job, array['money','everyday'], 2,
   'the part that belongs to one person',
   'their part',
   'Her share of the money was 20 pounds.',
   'Share the sweets — there it is the action of splitting.', false),
  ('more_than#comparison', 'more than', 'COMPARISON'::sixu_sense_job, array['math'], 2,
   'the first amount is bigger, and by how much',
   'bigger by',
   'Sam has 3 more than Ada. If Ada has 5, Sam has 8.',
   'Sam has 3 more than Ada does NOT mean Sam has 3.', true),
  ('less_than#inverse', 'less than', 'RELATION_INVERSE'::sixu_sense_job, array['math'], 2,
   'the first amount is smaller — and the sentence names the smaller one first, so the subtraction runs backwards from the reading order',
   'smaller by',
   'Ada has 3 less than Sam. If Sam has 8, Ada has 5 — you take 3 off Sam, not off Ada.',
   'Ada has 3 less than Sam does NOT mean 3 − 8.', true),
  ('altogether#total', 'altogether', 'QUANTITY_TOTAL'::sixu_sense_job, array['math'], 2,
   'add every part to get one number',
   'in total',
   '3 red and 4 blue is 7 altogether.',
   'It is altogether wrong — there it means completely.', true),
  ('difference#subtract', 'difference', 'OPERATION_CUE'::sixu_sense_job, array['math'], 2,
   'the gap between two amounts — subtract the smaller from the bigger',
   'the gap between them',
   'The difference between 9 and 4 is 5.',
   'The difference between the two stories — there it means how they are unlike.', true),
  ('difference#unlike', 'difference', 'COMPARISON'::sixu_sense_job, array['everyday'], 1,
   'a way two things are not the same',
   'what is not the same',
   'The difference between the two accounts is who wrote them.',
   'The difference between 9 and 4 — there it is a subtraction.', false),
  ('product#multiply', 'product', 'OPERATION_CUE'::sixu_sense_job, array['math'], 3,
   'the answer when you multiply',
   'multiply answer',
   'The product of 3 and 4 is 12.',
   'A product on a shelf — that is a thing for sale.', true),
  ('product#goods', 'product', 'OBJECT_EVERYDAY'::sixu_sense_job, array['everyday','money'], 1,
   'a thing that is made and sold',
   'item for sale',
   'The shop sells six products.',
   'The product of 3 and 4 — there it is a multiplication.', false),
  ('table#data', 'table', 'STRUCTURE_TECHNICAL'::sixu_sense_job, array['math','data'], 2,
   'rows and columns holding numbers you read across and down',
   'the number grid',
   'Read the second row of the table.',
   'The plate is on the table — that is furniture.', false),
  ('table#furniture', 'table', 'OBJECT_EVERYDAY'::sixu_sense_job, array['everyday'], 1,
   'the thing you sit at',
   'the furniture',
   'Put it on the table.',
   'The table shows the rainfall — there it is a grid of numbers.', false),
  ('mean#average', 'mean', 'OPERATION_CUE'::sixu_sense_job, array['math','data'], 3,
   'add them all, then split the total evenly between them',
   'the evened-out number',
   'The mean of 2, 4 and 9 is 5.',
   'He was mean to her — that is about behaviour.', true),
  ('mean#signify', 'mean', 'DISCOURSE'::sixu_sense_job, array['everyday'], 1,
   'stands for, or points to',
   'stands for',
   'A red light means stop.',
   'The mean of the scores — there it is a calculation.', false),
  ('volume#space', 'volume', 'STRUCTURE_TECHNICAL'::sixu_sense_job, array['math','science'], 3,
   'how much space something takes up inside',
   'space inside',
   'The box has a volume of 24 cubic centimetres.',
   'Turn the volume down — that is loudness.', false),
  ('volume#loudness', 'volume', 'OBJECT_EVERYDAY'::sixu_sense_job, array['everyday'], 1,
   'how loud a sound is',
   'loudness',
   'Turn the volume up.',
   'The volume of the box — there it is space inside.', false),
  ('odd#parity', 'odd', 'STRUCTURE_TECHNICAL'::sixu_sense_job, array['math'], 2,
   'a number that cannot be split into two equal whole parts',
   'not a pair number',
   '7 is odd because it cannot be split into two equal whole halves.',
   'That was odd of him — that means strange.', false),
  ('odd#strange', 'odd', 'COMPARISON'::sixu_sense_job, array['everyday'], 1,
   'unusual',
   'strange',
   'It was an odd thing to say.',
   '7 is odd — there it is about splitting into pairs.', false),
  ('primary#source', 'primary', 'SOURCE_STANDING'::sixu_sense_job, array['history','research'], 3,
   'made at the time by someone who was there',
   'first-hand, from the time',
   'A ship register written the same week is a primary source.',
   'A book written 200 years later is not primary, however careful it is.', true),
  ('primary#main', 'primary', 'SCOPE'::sixu_sense_job, array['everyday'], 2,
   'the main one',
   'main',
   'The primary reason was cost.',
   'A primary source — there it means written at the time.', false),
  ('record#document', 'record', 'SOURCE_STANDING'::sixu_sense_job, array['history','research'], 2,
   'a written or kept trace of something that happened',
   'the written trace',
   'The parish record lists the baptism.',
   'She broke the record — that is a best-ever result.', true),
  ('record#best', 'record', 'COMPARISON'::sixu_sense_job, array['everyday','sport'], 1,
   'the best result anyone has reached',
   'the best so far',
   'She broke the school record.',
   'The census record — there it is a document.', false),
  ('consensus#standing', 'consensus', 'SOURCE_STANDING'::sixu_sense_job, array['research','history'], 4,
   'what most people who study this currently hold — it says who holds the view, not that the view is proved',
   'what most researchers currently hold',
   'The consensus dates it to the 1400s; two dated letters could still move it.',
   'Consensus does not mean settled fact — a consensus can be wrong and has been.', true),
  ('if#conditional', 'if', 'CONDITIONAL'::sixu_sense_job, array['general'], 1,
   'the rest only holds when this part is true',
   'only when',
   'If the bag is full, she buys another — when it is not full, she does not.',
   'She buys another bag — with no "if" there is no condition at all.', true),
  ('not#negation', 'not', 'NEGATION'::sixu_sense_job, array['general'], 1,
   'turns the statement into its opposite',
   'the opposite of this',
   'The box is not empty — so there is something in it.',
   'Dropping "not" reverses the whole meaning.', true),
  ('all#universal', 'all', 'SCOPE'::sixu_sense_job, array['general'], 1,
   'every single one, with no exception',
   'every single one',
   'All the cups are clean — not one is dirty.',
   'Most of the cups are clean — that allows dirty ones.', true),
  ('some#existential', 'some', 'SCOPE'::sixu_sense_job, array['general'], 1,
   'at least one, but not stated how many — and not necessarily all',
   'at least one, maybe not all',
   'Some records survived — others did not.',
   'All records survived — that is a different claim.', true),
  ('because#cause', 'because', 'DISCOURSE'::sixu_sense_job, array['general'], 1,
   'names the cause — what comes after it is why the first part happened',
   'the reason is',
   'The river rose because the rain fell — the rain came first and caused it.',
   'The river rose and the rain fell — that gives no cause and no order.', true),
  ('per#rate', 'per', 'DISTRIBUTIVE'::sixu_sense_job, array['math','science'], 2,
   'for every one of them',
   'for each one',
   '60 miles per hour is 60 miles in every single hour.',
   '60 miles in total — that is one journey, not a rate.', true),
  ('remaining#remainder', 'remaining', 'QUANTITY_REMAINDER'::sixu_sense_job, array['math'], 2,
   'what is still there after the change',
   'what is still there',
   'She spent 4 of 10, so the remaining amount is 6.',
   'The whole amount — that is before the change, not after.', false)
on conflict (id) do nothing;

-- Sense cues ------------------------------------------------------------------
-- Cues are stored as data so a department can teach the engine a new context
-- without a code change. Patterns are PostgreSQL-flavoured regular expressions.
insert into sixu_sense_cues (sense_id, cue_pattern, cue_kind, weight) values
  ('left#remainder', 'how many .*\yleft\y', 'REGEX', 3),
  ('left#remainder', '\yhas\y.*\yleft\y', 'REGEX', 3),
  ('left#remainder', '\yare left\y', 'REGEX', 3),
  ('left#remainder', '\yleft over\y', 'REGEX', 3),
  ('left#direction', '\yturn left\y', 'REGEX', 3),
  ('left#direction', '\yon the left\y', 'REGEX', 3),
  ('left#direction', '\yleft side\y', 'REGEX', 3),
  ('of#part', '\y(half|third|quarter|\d+\s*%|\d+\/\d+)\s+of\y', 'REGEX', 3),
  ('of#part', '\yfraction of\y', 'REGEX', 3),
  ('of#belonging', '\yof the\y', 'REGEX', 3),
  ('each#distributive', '\yeach\y', 'REGEX', 3),
  ('each#distributive', '\yapiece\y', 'REGEX', 3),
  ('each#distributive', '\yper\y', 'REGEX', 3),
  ('share#divide', '\yshare[ds]?\y', 'REGEX', 3),
  ('share#divide', '\yshared (between|among)\y', 'REGEX', 3),
  ('share#divide', '\ysplit\y', 'REGEX', 3),
  ('share#portion', '\y(his|her|their|my) share\y', 'REGEX', 3),
  ('share#portion', '\yshare of the\y', 'REGEX', 3),
  ('more_than#comparison', '\ymore than\y', 'REGEX', 3),
  ('more_than#comparison', '\ygreater than\y', 'REGEX', 3),
  ('less_than#inverse', '\yless than\y', 'REGEX', 3),
  ('less_than#inverse', '\yfewer than\y', 'REGEX', 3),
  ('altogether#total', '\yaltogether\y', 'REGEX', 3),
  ('altogether#total', '\yin all\y', 'REGEX', 3),
  ('altogether#total', '\yin total\y', 'REGEX', 3),
  ('difference#subtract', '\ydifference between\y', 'REGEX', 3),
  ('difference#subtract', '\yhow many more\y', 'REGEX', 3),
  ('difference#subtract', '\yhow much (more|less)\y', 'REGEX', 3),
  ('difference#unlike', '\ydifference between the (two |)(account|story|version|report)', 'REGEX', 3),
  ('product#multiply', '\yproduct of\y', 'REGEX', 3),
  ('product#goods', '\y(sell|sold|buy|bought|shelf|store)\y', 'REGEX', 3),
  ('table#data', '\ythe table (below|above|shows)\y', 'REGEX', 3),
  ('table#data', '\yrow\y', 'REGEX', 3),
  ('table#data', '\ycolumn\y', 'REGEX', 3),
  ('table#furniture', '\yon the table\y', 'REGEX', 3),
  ('table#furniture', '\yunder the table\y', 'REGEX', 3),
  ('mean#average', '\ythe mean\y', 'REGEX', 3),
  ('mean#average', '\ymean of\y', 'REGEX', 3),
  ('mean#average', '\yaverage\y', 'REGEX', 3),
  ('mean#signify', '\ydoes .* mean\y', 'REGEX', 3),
  ('mean#signify', '\ymeans\y', 'REGEX', 3),
  ('volume#space', '\yvolume of the\y', 'REGEX', 3),
  ('volume#space', '\ycubic\y', 'REGEX', 3),
  ('volume#loudness', '\yturn (up|down) the volume\y', 'REGEX', 3),
  ('volume#loudness', '\yvolume (up|down)\y', 'REGEX', 3),
  ('odd#parity', '\yodd number\y', 'REGEX', 3),
  ('odd#parity', '\yodd or even\y', 'REGEX', 3),
  ('odd#strange', '\yodd (thing|way|that)\y', 'REGEX', 3),
  ('primary#source', '\yprimary source\y', 'REGEX', 3),
  ('primary#source', '\yfirst[- ]hand\y', 'REGEX', 3),
  ('primary#main', '\yprimary (reason|purpose|goal|aim)\y', 'REGEX', 3),
  ('record#document', '\yrecords?\y.*\y(show|list|survive|kept|destroyed|lost)\y', 'REGEX', 3),
  ('record#document', '\y(parish|census|ship|court) records?\y', 'REGEX', 3),
  ('record#best', '\y(broke|set|held) (the|a) record\y', 'REGEX', 3),
  ('record#best', '\yworld record\y', 'REGEX', 3),
  ('consensus#standing', '\yconsensus\y', 'REGEX', 3),
  ('consensus#standing', '\ymost (historians|scientists|researchers|scholars)\y', 'REGEX', 3),
  ('consensus#standing', '\ymainstream (view|account|history)\y', 'REGEX', 3),
  ('if#conditional', '\yif\y', 'REGEX', 3),
  ('if#conditional', '\ywhen(ever)?\y', 'REGEX', 3),
  ('if#conditional', '\yprovided that\y', 'REGEX', 3),
  ('if#conditional', '\yunless\y', 'REGEX', 3),
  ('not#negation', '\ynot\y', 'REGEX', 3),
  ('not#negation', '\yn''t\y', 'REGEX', 3),
  ('not#negation', '\ynever\y', 'REGEX', 3),
  ('not#negation', '\yno longer\y', 'REGEX', 3),
  ('all#universal', '\yall\y', 'REGEX', 3),
  ('all#universal', '\yevery\y', 'REGEX', 3),
  ('all#universal', '\ynone\y', 'REGEX', 3),
  ('some#existential', '\ysome\y', 'REGEX', 3),
  ('some#existential', '\yseveral\y', 'REGEX', 3),
  ('some#existential', '\ya few\y', 'REGEX', 3),
  ('because#cause', '\ybecause\y', 'REGEX', 3),
  ('because#cause', '\ysince\y', 'REGEX', 3),
  ('because#cause', '\yas a result\y', 'REGEX', 3),
  ('because#cause', '\ytherefore\y', 'REGEX', 3),
  ('because#cause', '\yso that\y', 'REGEX', 3),
  ('per#rate', '\yper\y', 'REGEX', 3),
  ('per#rate', '\yfor every\y', 'REGEX', 3),
  ('per#rate', '\ya (day|week|hour|month|year)\y', 'REGEX', 3),
  ('remaining#remainder', '\yremain(ing|der|s)?\y', 'REGEX', 3),
  ('remaining#remainder', '\ywhat is left\y', 'REGEX', 3)
on conflict (sense_id, cue_pattern) do nothing;

-- Concept graph ---------------------------------------------------------------
insert into sixu_concepts (id, label, band) values
  ('counting', 'counting whole things', 1),
  ('addition', 'putting amounts together', 1),
  ('subtraction', 'taking an amount away', 1),
  ('comparison', 'which amount is bigger, and by how much', 2),
  ('inverse_comparison', 'a comparison written in the opposite order to the calculation', 2),
  ('equal_groups', 'the same amount in every group', 2),
  ('multiplication', 'equal groups counted quickly', 2),
  ('division_sharing', 'splitting one amount into equal parts', 2),
  ('two_step_word_problem', 'a problem needing two operations in order', 3),
  ('density', 'how much mass sits in a given space', 3),
  ('floating', 'why some things float', 3),
  ('source_type', 'who made a record, and when', 2),
  ('primary_source', 'a record made at the time by someone present', 3),
  ('record_survival', 'why some records survive and others do not', 3),
  ('who_was_recorded', 'who the record-keepers wrote about, and who they left out', 3),
  ('evidence_weighing', 'holding two accounts against each other', 4),
  ('contested_claim', 'a claim the field has not settled', 4)
on conflict (id) do nothing;

insert into sixu_concept_prerequisites (concept_id, prerequisite_id) values
  ('addition', 'counting'),
  ('subtraction', 'counting'),
  ('subtraction', 'addition'),
  ('comparison', 'subtraction'),
  ('inverse_comparison', 'comparison'),
  ('equal_groups', 'addition'),
  ('multiplication', 'equal_groups'),
  ('division_sharing', 'equal_groups'),
  ('division_sharing', 'subtraction'),
  ('two_step_word_problem', 'inverse_comparison'),
  ('two_step_word_problem', 'division_sharing'),
  ('density', 'division_sharing'),
  ('floating', 'density'),
  ('primary_source', 'source_type'),
  ('record_survival', 'source_type'),
  ('who_was_recorded', 'record_survival'),
  ('evidence_weighing', 'primary_source'),
  ('evidence_weighing', 'who_was_recorded'),
  ('contested_claim', 'evidence_weighing')
on conflict (concept_id, prerequisite_id) do nothing;

commit;
