-- Companies and suppliers. THYLORA leads a genre; it does not own the economy.
-- Every new name is PROPOSED_PENDING_CHAIRMAN. Peete Crown, DGM, MAH', C&W are
-- carried as EXISTING_CANON and are not re-created, re-scoped or renamed here.

begin;

insert into er_civ_company_registry
(company_code, company_name, name_state, pronunciation, proposed_meaning, genre, ownership_class,
 parent_entity, role_scope, competes_with, canon_links, state, provenance) values

-- ---- existing canon, preserved exactly ----------------------------------
('ERCIV-CO-PEETE-CROWN','Peete Crown','EXISTING_CANON',null,
 'Chairman-established top vehicle brand/family. Carried unchanged from ER-BRAND-PEETE-CROWN-001.',
 'GROUND_PASSENGER_FLAGSHIP','EXISTING_CANON',null,
 '["top vehicle marque","flagship and ultra-luxury ground vehicles","performance family","brand design language authority"]',
 '["ERCIV-CO-SORREL-VANCE","ERCIV-CO-OTSEN"]',
 '["ER-BRAND-PEETE-CROWN-001","ER-DESIGN-NEWNEW-001","ER-DESIGN-WHEEL-001","ER-DESIGN-CROWN-001"]',
 'LOCKED_UPSTREAM',
 '{"authority":"ER-BRAND-PEETE-CROWN-001","note":"LOCKED brand. This row is an industry-map reference only and confers no new scope."}'),

('ERCIV-CO-DGM','DGM','EXISTING_CANON',null,
 'Sub-brand of Peete Crown. Expansion of initials remains UNKNOWN. Product scope remains UNRESOLVED in backend.',
 'GROUND_PASSENGER_SUBBRAND','EXISTING_CANON','Peete Crown',
 '["sub-brand of Peete Crown"]','[]',
 '["ER-BRAND-DGM-001"]','LOCKED_UPSTREAM',
 '{"authority":"ER-BRAND-DGM-001","scope_state":"UNRESOLVED","note":"Scope was requested from backend. Backend holds no scope definition. Chairman decision required; nothing assigned to DGM by this build."}'),

('ERCIV-CO-MAH','MAH''','EXISTING_CANON',null,
 'Chairman-established vehicle brand/name under Peete Crown. Product scope and meaning remain in development. Not the MAH-001 authority code.',
 'GROUND_PASSENGER_SUBBRAND','EXISTING_CANON','Peete Crown',
 '["sub-brand of Peete Crown","model assignment: Mateo (ER-MODEL-MAH-MATEO-001)"]','[]',
 '["ER-BRAND-MAH-001","ER-MODEL-MAH-MATEO-001"]','LOCKED_UPSTREAM',
 '{"authority":"ER-BRAND-MAH-001","scope_state":"UNRESOLVED","note":"Scope was requested from backend. Backend holds no body-class or product scope. Chairman decision required; nothing assigned to MAH by this build."}'),

('ERCIV-CO-CW-AUTO','C&W Auto & Customs','EXISTING_CANON',null,
 'Vehicle factory, restoration garage, custom builder and managed fleet house. Canonical form is C&W, never CNW.',
 'FACTORY_RESTORATION_CUSTOM_FLEET','EXISTING_CANON',null,
 '["vehicle factory","restoration garage","custom builder","managed fleet house","show production","managed storage, rental and sale"]',
 '["ERCIV-CO-MARN-DAUGHTERS"]',
 '["CW-AUTO-CUSTOMS-FACILITY-001","CW-AUTO-CUSTOMS-001","CNW-HERITAGE-FLEET-001","AUTO-NAME-001"]',
 'ACTIVE_SIMULATION_PRODUCTION',
 '{"authority":"Chairman correction 2026-09-16","staffing_floor":52,"note":"Carried unchanged. 52 in-world automotive employees. No Earth building or Earth employment asserted."}'),

-- ---- THYLORA-owned genre leads (proposed names) -------------------------
('ERCIV-CO-ORIN','Orin','PROPOSED_PENDING_CHAIRMAN','OR-in',
 'The first one held. The marque a person owns first.',
 'GROUND_PASSENGER_EVERYDAY','THYLORA_OWNED',null,
 '["affordable everyday ground vehicles","first-car and older-driver mobility","repairable compact platforms","fleet and municipal light vehicles"]',
 '["ERCIV-CO-HALLOWMOOR","ERCIV-CO-OTSEN"]',
 '["AUTO-CLASS-EVERYDAY","VEH-SMALL-DEEP-006"]','DESIGN',
 '{"reason":"Peete Crown is the locked top brand. An affordable hatch cannot sit under a top marque without diluting it, and DGM/MAH scope is unresolved, so a separate everyday marque is proposed rather than assumed."}'),

('ERCIV-CO-ALDERVANE','Aldervane','PROPOSED_PENDING_CHAIRMAN','AL-der-vayn',
 'The elder road. The long haul that carries the world''s weight.',
 'HEAVY_HAUL_LOGISTICS','THYLORA_OWNED',null,
 '["heavy trucks","tractor units","rigid freight","logistics fleet vehicles","yard and port tractors"]',
 '["ERCIV-CO-BRACKENHALL"]',
 '["VEH-HEAVY-DEEP-003","VEH-TRUCK-003"]','DESIGN','{}'),

('ERCIV-CO-WENDO','Wendo','PROPOSED_PENDING_CHAIRMAN','WEN-doh',
 'Carried together. A vehicle that belongs to everyone riding in it.',
 'TRANSIT_AND_BUS','THYLORA_OWNED',null,
 '["city buses","intercity coaches","school and community transport","accessible transit","transit depot systems"]',
 '["ERCIV-CO-BELLHAVEN","ERCIV-CO-TWO-RIVERS"]',
 '["ER-MOBILITY-TWO-LEVEL-001","THY-SITE-MOBILITY-001"]','DESIGN','{}'),

('ERCIV-CO-SEVRIN','Sevrin','PROPOSED_PENDING_CHAIRMAN','SEV-rin',
 'The one who stays. Apparatus that arrives and does not leave until people are out.',
 'EMERGENCY_AND_RESCUE','THYLORA_OWNED',null,
 '["fire and rescue apparatus","ambulance and patient transport","technical rescue vehicles","corridor rescue response units","water rescue craft tenders"]',
 '["ERCIV-CO-RYKE"]',
 '["CNW-ROADSAFE-001","CNW-SUBMERGE-001","ER-AUTO-GAP-008"]','DESIGN','{}'),

('ERCIV-CO-FURLO','Furlo','PROPOSED_PENDING_CHAIRMAN','FUR-loh',
 'The turned row. Machines that feed people.',
 'AGRICULTURAL','THYLORA_OWNED',null,
 '["tractors","harvesters","implement carriers","orchard and row-crop machines","farm transport"]',
 '["ERCIV-CO-QUILLON"]','[]','DESIGN','{}'),

('ERCIV-CO-ONDERN','Ondern','PROPOSED_PENDING_CHAIRMAN','ON-dern',
 'The under-work. What is built below before anything can stand.',
 'CONSTRUCTION_AND_EARTHMOVING','THYLORA_OWNED',null,
 '["excavators","loaders","graders","site dumpers","road-building plant","lifting and access machines"]',
 '["ERCIV-CO-FERROWRIGHT"]',
 '["THY-ROAD-CIRCULAR-001"]','DESIGN','{}'),

('ERCIV-CO-HALERIN','Halerin','PROPOSED_PENDING_CHAIRMAN','HAL-uh-rin',
 'Held in air. Flight that is answerable to the people inside it.',
 'CIVIL_AVIATION','THYLORA_OWNED',null,
 '["civil fixed-wing aircraft","rotorcraft","VTOL research airframes","Guardian Flight escort and support research","aviation ground support"]',
 '["ERCIV-CO-KESTRIN"]',
 '["ER-VEH-AIR-001","THY-GUARDIAN-FLIGHT-001","SURV-AIR-OCEAN-001"]','DESIGN',
 '{"gate":"Aviation programs may not inherit ground-vehicle evidence. No flight-performance claim without an airworthiness basis."}'),

('ERCIV-CO-KEELRA','Keelra','PROPOSED_PENDING_CHAIRMAN','KEEL-rah',
 'The keel that returns. A hull is judged by whether it comes back.',
 'MARINE','THYLORA_OWNED',null,
 '["workboats","ferries","rescue craft","coastal freight","submersible research hulls"]',
 '["ERCIV-CO-DEEPMARROW"]',
 '["ER-VEH-MARINE-001","SURV-SUB-LOSSCOMMS-001"]','DESIGN','{}'),

('ERCIV-CO-AMBRENT','Ambrent','PROPOSED_PENDING_CHAIRMAN','AM-brent',
 'Walks around and guards. Protection that travels with the person.',
 'ARMORED_PROTECTION','THYLORA_OWNED',null,
 '["armored passenger transport","cash and valuables transit","protected medical evacuation","protected utility vehicles"]',
 '[]','[]','DESIGN',
 '{"boundary":"Protection and survivability only. No weapon, munition or offensive capability is designed, specified or implied."}'),

('ERCIV-CO-CORVETH','Corveth','PROPOSED_PENDING_CHAIRMAN','KOR-veth',
 'The carried column. Moving people and supply, not force.',
 'MILITARY_TRANSPORT_MOBILITY_ONLY','THYLORA_OWNED',null,
 '["troop and personnel transport","field logistics and supply trucks","engineering and recovery vehicles","field medical transport","bridging and mobility support"]',
 '[]','[]','DESIGN',
 '{"boundary":"Taxonomy and capability level only. Mobility, protection, rescue, logistics, engineering, recovery and safety. No weapons, munitions, targeting, or destructive hardware is carried in this canon."}'),

('ERCIV-CO-TAMBER','Tamber','PROPOSED_PENDING_CHAIRMAN','TAM-ber',
 'Small and sure. The lightest thing that still gets you there.',
 'LIGHT_MOBILITY','THYLORA_OWNED',null,
 '["motorcycles","light electric mobility","cycles","powered wheelchairs and mobility devices","last-mile delivery vehicles"]',
 '[]','[]','DESIGN','{}'),

('ERCIV-CO-STONELANE','Stonelane Roadworks','PROPOSED_PENDING_CHAIRMAN','STONE-layn',
 'The made way. Roads are the other half of every vehicle.',
 'ROAD_AND_BRIDGE_INFRASTRUCTURE','THYLORA_OWNED',null,
 '["road construction and resurfacing","bridge works","drainage and texture programs","wind barrier installation","roadside sensing installation"]',
 '[]',
 '["THY-ROAD-CIRCULAR-001","CNW-ROADSAFE-001","ER-MOBILITY-TWO-LEVEL-001"]','DESIGN','{}'),

-- ---- independent competitors (NOT THYLORA-owned) ------------------------
('ERCIV-CO-HALLOWMOOR','Hallowmoor Motorworks','PROPOSED_PENDING_CHAIRMAN','HAL-oh-moor',
 'The open moor. Plain vehicles for plain money.',
 'GROUND_PASSENGER_EVERYDAY','INDEPENDENT',null,
 '["mass-market ground vehicles","price-led compact and mid vehicles","used-vehicle network"]',
 '["ERCIV-CO-ORIN"]','[]','DESIGN',
 '{"role":"Price pressure on Orin. Exists so affordability is a contested market, not a THYLORA favour."}'),

('ERCIV-CO-OTSEN','Otsen Vehicle Company','PROPOSED_PENDING_CHAIRMAN','OT-sen',
 'The steady house. Mid-market family vehicles.',
 'GROUND_PASSENGER_MID','INDEPENDENT',null,
 '["family sedans, wagons and crossovers","mid-market vans","family fleet sales"]',
 '["ERCIV-CO-ORIN","ERCIV-CO-PEETE-CROWN"]','[]','DESIGN','{}'),

('ERCIV-CO-SORREL-VANCE','Sorrel & Vance','PROPOSED_PENDING_CHAIRMAN','SOR-el and VANS',
 'Two coachbuilders'' names. Bodies made one at a time.',
 'ULTRA_LUXURY_COACHBUILT','INDEPENDENT',null,
 '["coachbuilt luxury bodies","commission-only vehicles","restoration of significant luxury vehicles"]',
 '["ERCIV-CO-PEETE-CROWN"]',
 '["AUTO-CLASS-ULTRA"]','DESIGN',
 '{"role":"Genuine rival to Peete Crown at the top. A top brand with no rival is an assertion, not a market."}'),

('ERCIV-CO-BRACKENHALL','Brackenhall Freight Machines','PROPOSED_PENDING_CHAIRMAN','BRAK-en-hall',
 'The hall at the rough ground. Trucks built for operators, not for shows.',
 'HEAVY_HAUL_LOGISTICS','INDEPENDENT',null,
 '["heavy trucks","vocational chassis","operator-led fleet supply"]',
 '["ERCIV-CO-ALDERVANE"]','[]','DESIGN','{}'),

('ERCIV-CO-BELLHAVEN','Bellhaven Coach','PROPOSED_PENDING_CHAIRMAN','BEL-hay-ven',
 'The safe harbour bell. Coaches for long roads.',
 'TRANSIT_AND_BUS','INDEPENDENT',null,
 '["intercity coaches","charter and tour coaches","school transport"]',
 '["ERCIV-CO-WENDO"]','[]','DESIGN','{}'),

('ERCIV-CO-TWO-RIVERS','Two Rivers Transit Company','PROPOSED_PENDING_CHAIRMAN',null,
 'A municipal operator that also builds small series for its own routes.',
 'TRANSIT_OPERATOR_AND_BUILDER','INDEPENDENT',null,
 '["municipal transit operation","small-series transit vehicle building","depot and charging operation"]',
 '["ERCIV-CO-WENDO"]','[]','DESIGN',
 '{"role":"A customer that can build its own vehicles. Keeps THYLORA transit honest on price and serviceability."}'),

('ERCIV-CO-RYKE','Ryke Emergency Apparatus','PROPOSED_PENDING_CHAIRMAN','RIKE',
 'The reach. Apparatus built around the ladder and the hose.',
 'EMERGENCY_AND_RESCUE','INDEPENDENT',null,
 '["fire apparatus","aerial and technical rescue","service and refurbishment of apparatus"]',
 '["ERCIV-CO-SEVRIN"]','[]','DESIGN','{}'),

('ERCIV-CO-QUILLON','Quillon Agricultural','PROPOSED_PENDING_CHAIRMAN','KWIL-on',
 'The guard on the blade. Machines that protect the people working them.',
 'AGRICULTURAL','INDEPENDENT',null,
 '["tractors and implements","harvest machinery","smallholder machinery"]',
 '["ERCIV-CO-FURLO"]','[]','DESIGN','{}'),

('ERCIV-CO-FERROWRIGHT','Ferrowright Machines','PROPOSED_PENDING_CHAIRMAN','FER-oh-rite',
 'The iron maker. Plant built to be rebuilt.',
 'CONSTRUCTION_AND_EARTHMOVING','INDEPENDENT',null,
 '["excavators and loaders","compaction and paving plant","rebuild and remanufacture"]',
 '["ERCIV-CO-ONDERN"]','[]','DESIGN','{}'),

('ERCIV-CO-KESTRIN','Kestrin Aviation','PROPOSED_PENDING_CHAIRMAN','KES-trin',
 'The small hunting bird. Light aircraft and utility flight.',
 'CIVIL_AVIATION','INDEPENDENT',null,
 '["light fixed-wing aircraft","utility and bush aviation","flight training fleets","aerial survey"]',
 '["ERCIV-CO-HALERIN"]','[]','DESIGN','{}'),

('ERCIV-CO-DEEPMARROW','Deepmarrow Marine','PROPOSED_PENDING_CHAIRMAN','DEEP-mar-oh',
 'The deep bone. Hulls for cold, deep water.',
 'MARINE','INDEPENDENT',null,
 '["fishing and workboats","coastal freight","deep-water research support"]',
 '["ERCIV-CO-KEELRA"]','[]','DESIGN','{}'),

('ERCIV-CO-MARN-DAUGHTERS','Marn & Daughters Bodyworks','PROPOSED_PENDING_CHAIRMAN','MARN',
 'A family panel shop that outlived its founder.',
 'RESTORATION_AND_CUSTOM','INDEPENDENT',null,
 '["restoration","panel and paint","heritage fabrication","custom one-offs"]',
 '["ERCIV-CO-CW-AUTO"]',
 '["AUTO-CLASS-HERITAGE","VEH-HERITAGE-006"]','DESIGN',
 '{"role":"Independent rival to C&W. Restoration quality should be contested, not granted."}')
on conflict (company_code) do nothing;

-- ---- suppliers -----------------------------------------------------------
insert into er_civ_supplier_registry
(supplier_code, supplier_name, name_state, pronunciation, proposed_meaning, supply_domain,
 ownership_class, supplies_to, critical_failure_modes, second_source_state, canon_links, provenance) values

('ERCIV-SUP-CINDREL','Cindrel Cell Works','PROPOSED_PENDING_CHAIRMAN','SIN-drel',
 'The ember held. Stored energy that must never be let loose at once.',
 'BATTERIES_AND_ENERGY_CELLS','INDEPENDENT',
 '["ERCIV-CO-ORIN","ERCIV-CO-PEETE-CROWN","ERCIV-CO-WENDO","ERCIV-CO-TAMBER"]',
 '["cell thermal runaway propagation","pack enclosure breach from underbody strike","cold-temperature capacity loss misrepresented as range","end-of-life cells entering reuse without state-of-health evidence"]',
 'REQUIRED_NOT_YET_NAMED','["ER-AUTO-GAP-005"]',
 '{"note":"Independent on purpose. A single owned battery source would make every THYLORA vehicle share one failure mode."}'),

('ERCIV-SUP-VANTOR','Vantor Drive Systems','PROPOSED_PENDING_CHAIRMAN','VAN-tor',
 'The turning. Motors, reduction and drive control.',
 'TRACTION_MOTORS_AND_DRIVE_UNITS','THYLORA_OWNED',
 '["ERCIV-CO-ORIN","ERCIV-CO-PEETE-CROWN","ERCIV-CO-ALDERVANE","ERCIV-CO-WENDO"]',
 '["uncommanded torque","loss of torque in a lane-change","regeneration loss on ice","position-sensor drift"]',
 'REQUIRED_NOT_YET_NAMED','[]','{}'),

('ERCIV-SUP-TORRAND','Torrand Tire Company','PROPOSED_PENDING_CHAIRMAN','TOR-and',
 'The turning band. The only part of the vehicle that touches the road.',
 'TIRES','INDEPENDENT',
 '["ALL_GROUND_COMPANIES"]',
 '["tread separation","hydroplaning onset below posted speed on worn tread","load/speed rating exceeded by heavy variants","aging failure in low-mileage stored vehicles"]',
 'REQUIRED_NOT_YET_NAMED','["ERCIV-STUDY-HYDROPLANE-001","ER-AUTO-GAP-006"]','{}'),

('ERCIV-SUP-CLEARMONT','Clearmont Glassworks','PROPOSED_PENDING_CHAIRMAN','CLEER-mont',
 'The clear hill. Glazing, vision and light.',
 'GLASS_AND_GLAZING','INDEPENDENT',
 '["ALL_GROUND_COMPANIES","ERCIV-CO-KEELRA","ERCIV-CO-WENDO"]',
 '["laminate delamination obscuring vision","side glass that will not break for rescue or egress","optical distortion in large curved screens","coating interference with sensing"]',
 'REQUIRED_NOT_YET_NAMED','["ER-AUTO-GAP-007"]',
 '{"note":"Egress-breakable side glazing is a submersion and rescue requirement, not a comfort choice."}'),

('ERCIV-SUP-HOLDFAST','Holdfast Occupant Systems','PROPOSED_PENDING_CHAIRMAN',null,
 'To hold fast. Belts, airbags and the seat that carries the load.',
 'OCCUPANT_SAFETY_SYSTEMS','THYLORA_OWNED',
 '["ALL_GROUND_COMPANIES","ERCIV-CO-WENDO","ERCIV-CO-SEVRIN"]',
 '["restraint that will not release after power loss","airbag deployment out of stroke for out-of-position occupants","child-restraint anchor misuse","far-side occupant excursion"]',
 'REQUIRED_NOT_YET_NAMED','["ER-AUTO-GAP-007","IMP-SIDE-001"]','{}'),

('ERCIV-SUP-WAYKEN','Wayken Navigation','PROPOSED_PENDING_CHAIRMAN','WAY-ken',
 'To know the way. Position, route and corridor messaging.',
 'NAVIGATION_AND_POSITIONING','THYLORA_OWNED',
 '["ALL_COMPANIES"]',
 '["confident position in a place the vehicle is not","silent loss of corridor messaging","route guidance into a closed or flooded corridor","identity inference from position data"]',
 'REQUIRED_NOT_YET_NAMED','["CNW-ROADSAFE-001"]',
 '{"rule":"No safety function may depend solely on infrastructure messaging. Losing the link must never leave a vehicle worse than one that never had it."}'),

('ERCIV-SUP-LOMERE','Lomere Interiors','PROPOSED_PENDING_CHAIRMAN','loh-MEER',
 'The soft room. Seats, trim, textiles and touch.',
 'INTERIORS_AND_TEXTILES','INDEPENDENT',
 '["ALL_GROUND_COMPANIES"]',
 '["trim that blocks a belt path or an airbag seam","flammability in a post-crash fire","seat-frame failure under rear impact","materials that outgas in heat"]',
 'REQUIRED_NOT_YET_NAMED','[]','{}'),

('ERCIV-SUP-SKARN','Skarn Avionics','PROPOSED_PENDING_CHAIRMAN','SKARN',
 'The hard seam. Flight instruments and control electronics.',
 'AVIATION_SYSTEMS','INDEPENDENT',
 '["ERCIV-CO-HALERIN","ERCIV-CO-KESTRIN"]',
 '["single-channel flight-critical control","display loss in degraded power","icing sensor disagreement","beacon failure after impact"]',
 'REQUIRED_NOT_YET_NAMED','["ER-VEH-AIR-001","THY-GUARDIAN-FLIGHT-001"]',
 '{"gate":"Aviation evidence is separate. Nothing from the ground programs transfers."}'),

('ERCIV-SUP-FATHOMGATE','Fathomgate Marine Systems','PROPOSED_PENDING_CHAIRMAN',null,
 'The gate at depth. Propulsion, steering and life support for water.',
 'MARINE_SYSTEMS','INDEPENDENT',
 '["ERCIV-CO-KEELRA","ERCIV-CO-DEEPMARROW","ERCIV-CO-SEVRIN"]',
 '["loss of steering with propulsion still running","compartment flooding across a failed boundary","life-support CO2 scrubbing failure in enclosed craft","single-link control on a submerged craft"]',
 'REQUIRED_NOT_YET_NAMED','["ER-VEH-MARINE-001","SURV-SUB-LOSSCOMMS-001"]',
 '{"rule":"Consumer wireless control alone can never be a sole critical path. Carried from ER-VEH-MARINE-001."}'),

('ERCIV-SUP-PELL','Pell Hydraulic Works','PROPOSED_PENDING_CHAIRMAN','PEL',
 'The push. Cylinders, pumps and valves for plant.',
 'CONSTRUCTION_HYDRAULICS','INDEPENDENT',
 '["ERCIV-CO-ONDERN","ERCIV-CO-FERROWRIGHT","ERCIV-CO-FURLO","ERCIV-CO-SEVRIN"]',
 '["uncommanded boom descent on hose burst","stored pressure released during service","hose burst spraying hot fluid into a cab","load-holding valve bypass"]',
 'REQUIRED_NOT_YET_NAMED','[]',
 '{"rule":"Every lifting circuit must hold its load with the engine off and the hoses cut."}'),

('ERCIV-SUP-ONDERN-HYD','Ondern Hydraulics Division','PROPOSED_PENDING_CHAIRMAN',null,
 'In-house hydraulics for Ondern plant; second source to Pell.',
 'CONSTRUCTION_HYDRAULICS','THYLORA_OWNED',
 '["ERCIV-CO-ONDERN"]',
 '["same failure modes as ERCIV-SUP-PELL"]',
 'SECOND_SOURCE_TO_PELL','[]','{}'),

('ERCIV-SUP-ROUNDHOUSE','Roundhouse Fleet Care','PROPOSED_PENDING_CHAIRMAN',null,
 'The shed where everything comes back. Fleet maintenance and inspection.',
 'FLEET_MAINTENANCE','INDEPENDENT',
 '["ERCIV-CO-WENDO","ERCIV-CO-ALDERVANE","ERCIV-CO-TWO-RIVERS","ERCIV-CO-CW-AUTO"]',
 '["inspection signed without the inspection","deferred defect that becomes a corridor incident","parts provenance lost in a rushed repair","filter service skipped because it is logged as comfort"]',
 'REQUIRED_NOT_YET_NAMED','["SVC-ROUTINE","SVC-DIAGNOSTIC","ERCIV-STUDY-FILTER-001"]','{}'),

('ERCIV-SUP-CURRENTMARK','Currentmark Energy','PROPOSED_PENDING_CHAIRMAN',null,
 'The mark on the meter. Charging and energy dispensing.',
 'CHARGING_AND_ENERGY_DISPENSING','INDEPENDENT',
 '["ALL_GROUND_COMPANIES"]',
 '["connector heating under sustained high current","earth fault in wet conditions","charge session billed but not delivered","corridor charging unavailable during an evacuation"]',
 'REQUIRED_NOT_YET_NAMED','[]',
 '{"note":"Evacuation availability is a safety requirement, not a commercial one."}'),

('ERCIV-SUP-REBATCH','Rebatch Materials','EXISTING_CANON',null,
 'Recovery and re-batching of materials. Uses the existing canon term rebatch from CNW-HERITAGE-001.',
 'RECYCLING_AND_MATERIAL_RECOVERY','THYLORA_OWNED',
 '["ALL_COMPANIES","ERCIV-CO-STONELANE"]',
 '["recovered material entering a safety-critical part without traceability","battery pack recovery without state-of-health evidence","contaminated recyclate weakening a road layer"]',
 'REQUIRED_NOT_YET_NAMED','["CNW-HERITAGE-001","THY-ROAD-CIRCULAR-001"]',
 '{"note":"Term rebatch is existing canon. Entity name still requires Chairman approval."}'),

('ERCIV-SUP-SIEVEWORKS','Sieveworks Filtration','PROPOSED_PENDING_CHAIRMAN','SEEV-works',
 'The sieve. Air, fluid and cabin filtration.',
 'FILTRATION','INDEPENDENT',
 '["ALL_COMPANIES"]',
 '["cabin filter restriction cutting defrost airflow","intake restriction misread as an engine fault","pack coolant filter bypass under cold viscosity","filter housing that needs a structural part removed to reach"]',
 'REQUIRED_NOT_YET_NAMED','["ERCIV-STUDY-FILTER-001","ER-AUTO-GAP-005"]','{}'),

('ERCIV-SUP-CORRIDOR-SENSE','Corridor Sense Company','PROPOSED_PENDING_CHAIRMAN',null,
 'Roadside detection, weather and hazard sensing.',
 'ROADSIDE_SENSING','INDEPENDENT',
 '["ERCIV-CO-STONELANE","ERCIV-CO-SEVRIN","ERCIV-SUP-WAYKEN"]',
 '["hazard reported after the vehicle has passed it","false hazard causing a hard brake in traffic","sensing repurposed into identity tracking","sensor blinded by the weather it exists to report"]',
 'REQUIRED_NOT_YET_NAMED','["CNW-ROADSAFE-001","ER-AUTO-GAP-008"]',
 '{"rule":"States hazards, never identities. Carried from CNW-ROADSAFE-001 no_false_claim_of_identity_detection."}'),

('ERCIV-SUP-HALTEN','Halten Brake Company','PROPOSED_PENDING_CHAIRMAN','HAWL-ten',
 'To hold. Friction, calipers and brake thermal capacity.',
 'BRAKES_AND_FRICTION','INDEPENDENT',
 '["ALL_GROUND_COMPANIES"]',
 '["thermal fade on a long descent at full load","corrosion seizure in a stored heritage vehicle","pad material change altering stopping distance without notice","electronic brake command loss with no mechanical reserve"]',
 'REQUIRED_NOT_YET_NAMED','["ERCIV-STUDY-GRIP-001"]','{}'),

('ERCIV-SUP-WHEELS-UNRESOLVED','UNRESOLVED — wheel manufacturing entity','UNRESOLVED',null,
 'The wheel design language is existing canon (VYC 2ST, ER-AUTO-GAP-006 and ER-DESIGN-WHEEL-001). The manufacturing entity has never been named and is not invented here.',
 'WHEELS','EXISTING_CANON',
 '["ALL_GROUND_COMPANIES"]',
 '["fatigue cracking at the spoke root","impact failure at low-profile fitment","unsprung mass penalty from cosmetic diameter","brake cooling blocked by a closed face"]',
 'CHAIRMAN_DECISION_REQUIRED','["ER-AUTO-GAP-006","ER-DESIGN-WHEEL-001"]',
 '{"note":"VYC 2ST is an existing Chairman mark. No entity name is proposed for it by this build."}')
on conflict (supplier_code) do nothing;

-- ---- market structure ----------------------------------------------------
insert into er_civ_market_structure (genre, thylora_lead_company, independent_companies, concentration_rule, rationale) values
('GROUND_PASSENGER_EVERYDAY','Orin','["Hallowmoor Motorworks","Otsen Vehicle Company"]',
 '{"thylora_share_ceiling_pct":45,"minimum_independent_competitors":2,"rule":"If a THYLORA marque holds more than the ceiling in a genre, the correction is that the rivals get better, not that the rival is removed."}',
 'Affordability must be contested. A cheap car that has no rival becomes a cheap car by permission.'),
('GROUND_PASSENGER_FLAGSHIP','Peete Crown','["Sorrel & Vance","Otsen Vehicle Company"]',
 '{"thylora_share_ceiling_pct":60,"minimum_independent_competitors":1,"rule":"Peete Crown may lead. It may not be the only thing at the top."}',
 'A top brand with no rival is an assertion, not a market. Sorrel & Vance exists so Peete Crown has to win.'),
('HEAVY_HAUL_LOGISTICS','Aldervane','["Brackenhall Freight Machines"]',
 '{"thylora_share_ceiling_pct":50,"minimum_independent_competitors":1}',
 'Operators buy on running cost and uptime. An unchallenged supplier stops measuring either.'),
('TRANSIT_AND_BUS','Wendo','["Bellhaven Coach","Two Rivers Transit Company"]',
 '{"thylora_share_ceiling_pct":50,"minimum_independent_competitors":2,"rule":"At least one transit rival must also be an operator, so the buyer can build what it cannot buy."}',
 'Public transport paid for by the public should not have a single vendor.'),
('EMERGENCY_AND_RESCUE','Sevrin','["Ryke Emergency Apparatus"]',
 '{"thylora_share_ceiling_pct":55,"minimum_independent_competitors":1}',
 'Rescue capacity cannot be held hostage to one supplier''s delivery schedule.'),
('AGRICULTURAL','Furlo','["Quillon Agricultural"]',
 '{"thylora_share_ceiling_pct":45,"minimum_independent_competitors":1}',
 'Food supply must not depend on one machinery source.'),
('CONSTRUCTION_AND_EARTHMOVING','Ondern','["Ferrowright Machines"]',
 '{"thylora_share_ceiling_pct":50,"minimum_independent_competitors":1}',
 'Rebuildability is only proven when a rival rebuilds better.'),
('CIVIL_AVIATION','Halerin','["Kestrin Aviation"]',
 '{"thylora_share_ceiling_pct":40,"minimum_independent_competitors":1,"rule":"Aviation concentration limits are tighter because a single design fault grounds a whole fleet."}',
 'One airframe family owning a sky is a single point of failure for an entire domain.'),
('MARINE','Keelra','["Deepmarrow Marine"]',
 '{"thylora_share_ceiling_pct":45,"minimum_independent_competitors":1}',
 'Coastal communities need more than one yard.'),
('RESTORATION_AND_CUSTOM','C&W Auto & Customs','["Marn & Daughters Bodyworks"]',
 '{"thylora_share_ceiling_pct":55,"minimum_independent_competitors":1}',
 'Restoration quality should be contested. C&W is preserved as the lead house, not as the only house.'),
('ARMORED_PROTECTION','Ambrent','[]',
 '{"thylora_share_ceiling_pct":100,"minimum_independent_competitors":0,"rule":"Deliberately not opened to independents at this stage. Protection products carry misuse risk and stay inside a single accountable house until the Chairman decides otherwise."}',
 'This is the one genre where concentration is the safer choice, and it is a decision, not an oversight.'),
('MILITARY_TRANSPORT_MOBILITY_ONLY','Corveth','[]',
 '{"thylora_share_ceiling_pct":100,"minimum_independent_competitors":0,"rule":"Closed for the same reason as armored protection. Scope stays at mobility, logistics, engineering, recovery and medical transport."}',
 'Kept inside one accountable house so the weapons boundary has one owner.'),
('ROAD_AND_BRIDGE_INFRASTRUCTURE','Stonelane Roadworks','[]',
 '{"thylora_share_ceiling_pct":100,"minimum_independent_competitors":0,"rule":"Open to independents once the first corridor standard is published and can be tendered against."}',
 'You cannot tender a standard that does not exist yet.'),
('LIGHT_MOBILITY','Tamber','[]',
 '{"thylora_share_ceiling_pct":60,"minimum_independent_competitors":0,"independent_required_before_first_release":true,"rule":"No independent rival named yet. One is required as a gate on first product release, not as a present-state minimum, so this row states the obligation without pretending it is already met."}',
 'Deliberately left as a named open gap. A rival invented only to satisfy a rule would be a name nobody asked for, and would hide the fact that this genre currently has no competition at all.')
on conflict (genre) do nothing;

commit;
