-- THYLORA · QYRIS · 0002 · Pre-marriage pack
--
-- GENERATED FILE — DO NOT EDIT BY HAND.
-- Source of truth: qyris/data/premarriage-pack.js
-- Regenerate:     node db/qyris/generate-seed.mjs
-- Drift check:    node db/qyris/generate-seed.mjs --check  (run by npm test)
--
-- Idempotent: every insert is an upsert, so a second application is a no-op.


insert into qyr_packs (pack_id, title, kind, notice) values
  ('QYRIS-PREMARRIAGE-001', 'Pre-Marriage QYRIS Question Pack', 'PREMARRIAGE', 'A question pack, not advice, not a contract, and not a substitute for a lawyer, a clinician or a counsellor. Every SAFEGUARD exists because the question can be misused.')
on conflict (pack_id) do update set title = excluded.title, notice = excluded.notice;

insert into qyr_nodes (node_id, pack_id, parent_id, cluster_id, label, depth, ordinal, question, yield, reason, inspect, safeguard) values
  ('MONEY', 'QYRIS-PREMARRIAGE-001', null, 'MONEY', 'MONEY', 0, 0, 'What does each of us actually earn, own, owe and control today — in numbers, not in impressions?', 'A single written picture of two financial lives, with amounts, accounts and who can move what.', 'Almost every later money fight is really a fight about a number one person never saw.', 'Compare what is said against statements, pay records and account access. Unverifiable figures stay marked UNKNOWN rather than assumed.', 'Disclosure is mutual and simultaneous. Neither person hands over documents to someone who has not handed over their own, and neither is asked for account credentials.'),
  ('MONEY.INCOME', 'QYRIS-PREMARRIAGE-001', 'MONEY', 'MONEY', null, 1, 0, 'What is each income, how stable is it, and what would it take for it to stop?', 'A stability rating per income stream and the named event that would end each one.', 'Two people can have identical incomes and completely different exposure.', 'Check the last two years, not the best month. Commission, tips, gig and seasonal income are checked against the low period.', 'A low or unstable income is a planning input, not a verdict on the person. The question is what to build around it, not whether they qualify.'),
  ('MONEY.ACCOUNTS', 'QYRIS-PREMARRIAGE-001', 'MONEY', 'MONEY', null, 1, 1, 'Which accounts stay separate, which become joint, and who may move money without asking?', 'A written account map with a named authority for each account.', 'Joint access is an authority decision disguised as a convenience decision.', 'Name a real amount. Can either person move it alone today? If yes, that is the actual rule, whatever was agreed verbally.', 'Each person keeps at least one account in their own name that the other cannot drain. This is not distrust; it is the difference between a hard week and a trapped year.'),
  ('MONEY.ACCOUNTS.THRESHOLD', 'QYRIS-PREMARRIAGE-001', 'MONEY.ACCOUNTS', 'MONEY', null, 2, 0, 'Above what amount does a purchase require the other person to be told first?', 'One number both people can state from memory.', 'An unstated threshold is discovered only when it has already been crossed.', 'Ask each separately and compare the two numbers. A gap is the finding.', 'The threshold applies symmetrically, including to the higher earner.'),
  ('MONEY.ACCOUNTS.EXIT', 'QYRIS-PREMARRIAGE-001', 'MONEY.ACCOUNTS', 'MONEY', null, 2, 1, 'If this relationship ended badly, what could the other person do to these accounts in one afternoon?', 'A named worst case per account, and whether either person accepts it.', 'Access granted in a good season is still access in a bad one.', 'Read the actual account terms for withdrawal, overdraft and closure rights. Verbal assurance is not a control.', 'Asking this is not planning to leave. Refusing to let it be asked is itself the answer.'),
  ('MONEY.HISTORY', 'QYRIS-PREMARRIAGE-001', 'MONEY', 'MONEY', null, 1, 2, 'What did money mean in each of our childhood homes, and what did we each promise ourselves we would never repeat?', 'The rule each person is privately enforcing without having stated it.', 'People do not argue about the grocery bill. They argue about what the grocery bill meant in 1998.', 'Listen for the moment each story turns tense. That is where the private rule lives.', 'A family money history is offered, not extracted. A person may name that a period is not open yet.'),
  ('MONEY.SUPPORT', 'QYRIS-PREMARRIAGE-001', 'MONEY', 'MONEY', null, 1, 3, 'Who outside this household currently receives money from either of us, and on what standing?', 'A named list of dependants, relatives and obligations with amounts and expected duration.', 'Support that predates the marriage does not stop at the wedding, and hidden support becomes the first betrayal narrative.', 'Check bank outflows for the last six months against the stated list.', 'Existing obligations to children, parents and elders are named as obligations, not negotiated down as a condition of marriage.'),
  ('DEBT', 'QYRIS-PREMARRIAGE-001', null, 'DEBT', 'DEBT', 0, 1, 'What is every debt either of us carries, who is legally on it, and what happens to it if we marry?', 'A complete debt schedule with legal owner, balance, rate and the marital effect of each.', 'Marriage changes who can be pursued for a debt in ways most people never check before the ceremony.', 'Pull the actual credit record. A remembered balance is an estimate; a statement is evidence.', 'No debt disclosure is used as leverage later. It is a shared map, not a file kept on a person.'),
  ('DEBT.INVENTORY', 'QYRIS-PREMARRIAGE-001', 'DEBT', 'DEBT', null, 1, 0, 'What is owed, to whom, at what rate, and how many months until it is gone at the current payment?', 'A payoff date per debt instead of a permanent background hum.', 'Debt without a date behaves like weather. Debt with a date behaves like a task.', 'Recompute the payoff date from balance, rate and payment. Do not accept the lender marketing figure.', 'The person with more debt is not made to feel they are entering as a liability.'),
  ('DEBT.EXPOSURE', 'QYRIS-PREMARRIAGE-001', 'DEBT', 'DEBT', null, 1, 1, 'Which of these debts could a creditor pursue against the other spouse after marriage, and under whose rules?', 'A jurisdiction-checked list of which debts travel and which do not.', 'Community-property rules, co-signing and joint accounts each transfer exposure differently, and people guess wrong.', 'Confirm against the actual jurisdiction, in writing, before relying on it.', 'This is legal exposure, and the pack names it as a question for a lawyer rather than answering it.'),
  ('DEBT.EXPOSURE.COSIGN', 'QYRIS-PREMARRIAGE-001', 'DEBT.EXPOSURE', 'DEBT', null, 2, 0, 'Will either of us be asked to co-sign for the other, and what is the answer before the moment arrives?', 'A standing answer decided while calm.', 'A co-signing decision made under time pressure is not a decision.', 'Name the specific instrument. "Would you help me" is not a co-sign; a signature is.', 'Either person may decline to co-sign without it counting as a withdrawal of love. That protection is stated up front, once, so it is available later.'),
  ('DEBT.EXPOSURE.HIDDEN', 'QYRIS-PREMARRIAGE-001', 'DEBT.EXPOSURE', 'DEBT', null, 2, 1, 'What debt exists that has not been said out loud yet — and what would make it safe to say?', 'The condition under which the remaining disclosure becomes possible.', 'Undisclosed debt is usually hidden for shame, not fraud, and shame responds to conditions.', 'A credit record surfaces most of it. The gap between the record and the conversation is the finding.', 'The answer is met once without punishment. This is stated before the question is asked, and it is honoured, or the pack has done harm.'),
  ('DEBT.PLAN', 'QYRIS-PREMARRIAGE-001', 'DEBT', 'DEBT', null, 1, 2, 'Whose debt gets paid first with shared money, and who decided that?', 'An ordering rule with a stated basis — rate, balance, risk or fairness.', 'Without a rule, the order is set by whoever is more insistent, and resentment compounds faster than interest.', 'Apply the rule to a real month and see whether both people still agree with the output.', 'The rule can be revisited on a fixed schedule, so agreeing to it now is not agreeing to it forever.'),
  ('DEBT.FUTURE', 'QYRIS-PREMARRIAGE-001', 'DEBT', 'DEBT', null, 1, 3, 'What new debt are we each willing to take on after marriage, and for what?', 'A named list of acceptable reasons to borrow, and unacceptable ones.', 'The disagreement is rarely about borrowing; it is about what counts as a good enough reason.', 'Test the list against three real scenarios, including one medical and one family emergency.', 'Emergency care is never gated by the borrowing list.'),
  ('CHILDREN', 'QYRIS-PREMARRIAGE-001', null, 'CHILDREN', 'CHILDREN', 0, 2, 'Do we each want children, how many, when, and what happens to this marriage if the answer turns out to be no?', 'Two stated positions and an agreed answer to the mismatch case, decided before it is urgent.', 'This is the most common unrecoverable mismatch, and it is usually discovered years after it could have been discussed.', 'Ask each person separately, then compare. An answer given in front of the other is a different answer.', 'Neither person is talked out of their position in this session. A mismatch is allowed to stand unresolved rather than be papered over.'),
  ('CHILDREN.EXISTING', 'QYRIS-PREMARRIAGE-001', 'CHILDREN', 'CHILDREN', null, 1, 0, 'What children already exist, in whose care, and what does each of us owe them?', 'A clear statement of existing parental obligations, custody arrangements and financial duties.', 'Existing children have prior claims that a new marriage does not reduce.', 'Check court orders and custody agreements as written, not as remembered.', 'A child''s existing arrangement is not renegotiated to accommodate a new relationship without the process that protects that child.'),
  ('CHILDREN.FERTILITY', 'QYRIS-PREMARRIAGE-001', 'CHILDREN', 'CHILDREN', null, 1, 1, 'What do we each know about our own fertility, and what are we each willing to do if it is difficult?', 'A stated limit on treatment, cost and time before this becomes a crisis decision.', 'Fertility treatment decisions made inside grief are made without a floor.', 'This is a medical question. The pack records the position; a clinician establishes the facts.', 'No medical detail is stored by this system. Only each person''s stated willingness is recorded, and either can withdraw it at any time.'),
  ('CHILDREN.FERTILITY.ALTERNATIVES', 'QYRIS-PREMARRIAGE-001', 'CHILDREN.FERTILITY', 'CHILDREN', null, 2, 0, 'Where does each of us stand on adoption, fostering, donor conception and remaining child-free?', 'Four separate positions instead of one assumed one.', 'People who agree on "children" often disagree completely on how.', 'Ask about each path separately. Agreement on the goal hides disagreement on the route.', 'A position on any one path is not treated as a position on the others.'),
  ('CHILDREN.FERTILITY.STOP', 'QYRIS-PREMARRIAGE-001', 'CHILDREN.FERTILITY', 'CHILDREN', null, 2, 1, 'Who decides when trying stops, and what does the other person do if they disagree?', 'A named decision-holder and a named response to disagreement.', 'The stopping decision is the one that breaks couples, because it is rarely assigned in advance.', 'Check whether the stated rule survives the case where the one who wants to stop is the one not undergoing treatment.', 'The person whose body is involved holds the final decision on their own treatment. This is not a negotiated point.'),
  ('CHILDREN.RAISING', 'QYRIS-PREMARRIAGE-001', 'CHILDREN', 'CHILDREN', null, 1, 2, 'How will children be disciplined, schooled, fed, and taught about faith, race, money and conflict?', 'The specific practices each person assumes are normal.', '"We will figure it out" is answered by whoever acts first, under stress, at 2am.', 'Ask each person to describe a concrete scene, not a principle. Principles agree; scenes do not.', 'Physical discipline, and any practice either person names as harm, is a named disagreement rather than a deferred one.'),
  ('CHILDREN.LOAD', 'QYRIS-PREMARRIAGE-001', 'CHILDREN', 'CHILDREN', null, 1, 3, 'Who does the night wakings, the appointments, the school contact and the carrying of the whole schedule in their head?', 'A named allocation of the invisible load, not just the visible tasks.', 'The load that is not written down lands on whoever notices it first, permanently.', 'List twenty real tasks and assign each. The distribution, not the intention, is the answer.', 'The allocation is reviewable. Whoever is carrying more may say so without it being a complaint about the other''s character.'),
  ('FAMILY_BOUNDARIES', 'QYRIS-PREMARRIAGE-001', null, 'FAMILY_BOUNDARIES', 'FAMILY BOUNDARIES', 0, 3, 'What may each of our families decide, know, enter or expect — and who tells them when the answer is no?', 'A boundary map naming, per family, what is decided inside the marriage and what is not.', 'In-law conflict is rarely about the in-laws; it is about which spouse is willing to hold a line with their own family.', 'Test with a real past incident. What actually happened is the current boundary, whatever was intended.', 'Each person is responsible for holding the line with their own family. Neither is required to be the one who delivers the other''s bad news.'),
  ('FAMILY_BOUNDARIES.ACCESS', 'QYRIS-PREMARRIAGE-001', 'FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', null, 1, 0, 'Who may visit, stay, hold keys, or arrive without notice?', 'A stated access rule for the home, per person, with a notice expectation.', 'Physical access to the home is the most concrete boundary and the least often stated.', 'Count who currently holds a key or a code. That is the real list.', 'Either spouse can withdraw home access from any person, including their own relative, without justifying it to the family.'),
  ('FAMILY_BOUNDARIES.INFORMATION', 'QYRIS-PREMARRIAGE-001', 'FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', null, 1, 1, 'What about this marriage may be told to family, and what stays inside it?', 'A named privacy line covering money, conflict, fertility, health and plans.', 'A private matter repeated to a parent cannot be made private again.', 'Name three specific matters and ask each person whether their mother already knows.', 'Either person may name a matter private at any time, retroactively for future telling, and that is honoured without argument.'),
  ('FAMILY_BOUNDARIES.INFORMATION.CONFLICT', 'QYRIS-PREMARRIAGE-001', 'FAMILY_BOUNDARIES.INFORMATION', 'FAMILY_BOUNDARIES', null, 2, 0, 'When we fight, who hears about it outside this house?', 'A named list of who is told, and what they are told.', 'A family told only the bad half of every fight builds a permanent case against a spouse who has already forgiven and moved on.', 'Ask what each person''s family currently believes about the other. The gap between that and reality is the damage already done.', 'Both people keep the right to real support from someone — a friend, a counsellor, a faith leader. The boundary is against building a hostile jury, not against being helped.'),
  ('FAMILY_BOUNDARIES.INFORMATION.REPAIR', 'QYRIS-PREMARRIAGE-001', 'FAMILY_BOUNDARIES.INFORMATION', 'FAMILY_BOUNDARIES', null, 2, 1, 'When something private has already been told, what repairs it?', 'A concrete repair action rather than an apology alone.', 'Boundaries are established by what happens after they are crossed, not by what was agreed before.', 'Check whether the repair changes what the family is told next time. If not, it was a sentiment.', 'Repair is not conditioned on the wronged person first proving the harm was serious enough.'),
  ('FAMILY_BOUNDARIES.OBLIGATION', 'QYRIS-PREMARRIAGE-001', 'FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', null, 1, 2, 'What care, money, time and presence does each family expect, and which of those expectations do we accept?', 'An accepted-obligations list and an explicitly declined list.', 'Unaccepted expectations do not disappear; they get charged as debts at holidays and funerals.', 'Compare what was declined against what actually gets given over the next six months.', 'Declining an expectation is allowed to be unpopular. The pack does not require family approval as a test of a good decision.'),
  ('FAMILY_BOUNDARIES.CULTURE', 'QYRIS-PREMARRIAGE-001', 'FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', null, 1, 3, 'Where do our two families'' cultures, languages, customs and histories differ, and which practices will this household actually keep?', 'A named set of practices the household carries forward, and who teaches them.', 'Heritage that is never assigned to someone quietly stops being transmitted within one generation.', 'Name the practice, the occasion and the person responsible. Anything without a named person is aspiration.', 'Neither lineage is treated as the default from which the other is a deviation. A practice kept by only one side is still the household''s practice.'),
  ('FAITH_WORLDVIEW', 'QYRIS-PREMARRIAGE-001', null, 'FAITH_WORLDVIEW', 'FAITH / WORLDVIEW', 0, 4, 'What does each of us actually believe, how does it govern daily life, and what happens if one of us changes?', 'A stated belief position, its practical obligations, and an agreed response to change.', 'Shared belief is usually checked at the level of label. The friction is at the level of practice and of exit.', 'Look at the calendar and the bank statement. Both record belief more honestly than a statement does.', 'No person is required to state a belief they are still working out. "Unresolved" is a permitted answer and is recorded as such.'),
  ('FAITH_WORLDVIEW.PRACTICE', 'QYRIS-PREMARRIAGE-001', 'FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', null, 1, 0, 'What must be done weekly, yearly and on life events — and who is expected to do it?', 'A concrete obligations calendar rather than an identity label.', 'Two people of the same stated faith can have entirely incompatible practice loads.', 'Walk an actual year. Holidays, fasts, tithes, services, dietary rules, dress and rest days.', 'Participation is distinguished from observance. Attending is not converting, and neither is recorded as the other.'),
  ('FAITH_WORLDVIEW.AUTHORITY', 'QYRIS-PREMARRIAGE-001', 'FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', null, 1, 1, 'Whose ruling settles a disagreement — a text, a leader, a community, a conscience, or the two of us?', 'A named decision authority for belief-governed disputes.', 'An unnamed authority defaults to whoever can invoke one, which is a power question wearing a faith costume.', 'Test with a real disagreement the couple has already had.', 'Neither person is bound to an authority they did not personally accept, and accepting one does not surrender bodily autonomy or the right to leave.'),
  ('FAITH_WORLDVIEW.AUTHORITY.CHANGE', 'QYRIS-PREMARRIAGE-001', 'FAITH_WORLDVIEW.AUTHORITY', 'FAITH_WORLDVIEW', null, 2, 0, 'If one of us stopped believing, what would the other do?', 'A stated answer to deconversion, decided before it is a live wound.', 'Belief change is common, and the unprepared response is often the end of the marriage rather than the end of the belief.', 'Ask what specifically would change: the children''s upbringing, the family''s knowledge, the marriage itself.', 'The answer is recorded as each person''s own statement. It is not a promise extracted, and it may be revised.'),
  ('FAITH_WORLDVIEW.AUTHORITY.CHILDREN', 'QYRIS-PREMARRIAGE-001', 'FAITH_WORLDVIEW.AUTHORITY', 'FAITH_WORLDVIEW', null, 2, 1, 'What are children taught, by whom, and at what age may they decide for themselves?', 'A named age or condition at which a child''s own position is honoured.', 'Children become the battleground precisely because nobody assigned this in advance.', 'Check whether both people can state the same age without prompting.', 'A child''s eventual dissent is planned for as normal rather than treated as a failure by one parent.'),
  ('FAITH_WORLDVIEW.COMMUNITY', 'QYRIS-PREMARRIAGE-001', 'FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', null, 1, 2, 'What does the surrounding community expect of this marriage, and what does it do to people who fall short?', 'A named list of community expectations and the cost of not meeting them.', 'A community can be a support system or an enforcement system, and often both to different people.', 'Ask what happened to the last couple in that community who divorced, doubted or married out.', 'Neither person is asked to cut ties as a condition of the marriage, and neither is required to stay in a community that is unsafe for them.'),
  ('FAITH_WORLDVIEW.HERITAGE', 'QYRIS-PREMARRIAGE-001', 'FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', null, 1, 3, 'What history, lineage and origin story does each of us carry, and where are those accounts contested or suppressed?', 'A named heritage position per person, including which parts are documented, which are oral, and which are disputed.', 'Belief and lineage are frequently the same conversation, and a household that never names whose account is being taught defaults to whichever one is louder.', 'Separate four things and label each: documented record, family oral account, contested claim, and open question. Do not collapse them into one story.', 'An oral account is preserved as an oral account rather than corrected out of existence. A contested claim is marked contested rather than resolved by whoever is more confident.'),
  ('SEX_INTIMACY', 'QYRIS-PREMARRIAGE-001', null, 'SEX_INTIMACY', 'SEX / INTIMACY', 0, 5, 'What does each of us expect of physical intimacy, and how is a no heard in this marriage?', 'A stated expectation and an explicit, agreed shape for refusal.', 'The frequency conversation is the one people have. The refusal conversation is the one that determines whether the marriage is safe.', 'Check the answer to refusal against real past behaviour, not intention.', 'Consent is not transferred by marriage. Nothing in this pack creates an obligation to any sexual act, and a no requires no reason.'),
  ('SEX_INTIMACY.EXPECTATION', 'QYRIS-PREMARRIAGE-001', 'SEX_INTIMACY', 'SEX_INTIMACY', null, 1, 0, 'What does each of us actually expect, and what would a long mismatch mean?', 'Two stated expectations and a named response to sustained difference.', 'Mismatch is normal and survivable; unspoken mismatch narrated as rejection is not.', 'Ask what each person would conclude about themselves after six months of mismatch. That conclusion is the actual risk.', 'Neither answer is graded. Low desire and high desire are both stated positions, not defects.'),
  ('SEX_INTIMACY.REFUSAL', 'QYRIS-PREMARRIAGE-001', 'SEX_INTIMACY', 'SEX_INTIMACY', null, 1, 1, 'What happens in the hours after one of us says no?', 'A concrete description of the aftermath, from both people.', 'Coercion usually lives in the aftermath — the silence, the withdrawal, the cost — rather than in the moment.', 'Compare both accounts of the same past refusal. A gap is the finding, and it is significant.', 'If either account describes pressure, punishment or fear, this pack stops being the right tool and names that plainly. Support routes are surfaced rather than a next question.'),
  ('SEX_INTIMACY.REFUSAL.SAFETY', 'QYRIS-PREMARRIAGE-001', 'SEX_INTIMACY.REFUSAL', 'SEX_INTIMACY', null, 2, 0, 'Has either of us ever felt unsafe, pressured or unable to leave a situation with the other?', 'A direct answer, asked once, privately, with a route attached.', 'This is asked before a marriage because after it the exit costs rise sharply.', 'The question is asked separately and privately, or it is not asked at all — a joint answer here is not evidence.', 'A yes routes to a support service, not to a couples conversation. This system never records the answer, never reports it, and never shows it to the other person.'),
  ('SEX_INTIMACY.REFUSAL.HEALTH', 'QYRIS-PREMARRIAGE-001', 'SEX_INTIMACY.REFUSAL', 'SEX_INTIMACY', null, 2, 1, 'What health, medication, history or trauma affects intimacy, and what does each of us need because of it?', 'A stated need, in the person''s own words, at the level of detail they choose.', 'Needs that are never stated get read as rejection.', 'This is a clinical matter. The pack records only what a person chooses to say, and names the clinician as the route for the rest.', 'No medical detail is stored by this system. A person may answer at any depth, including none, and the pack proceeds.'),
  ('SEX_INTIMACY.EXCLUSIVITY', 'QYRIS-PREMARRIAGE-001', 'SEX_INTIMACY', 'SEX_INTIMACY', null, 1, 2, 'What exactly counts as a breach of exclusivity, in specifics, for each of us?', 'Two concrete definitions instead of one assumed word.', 'Most people discover their partner''s definition only after crossing it.', 'Test twelve specific behaviours, including online, emotional, historical and workplace ones.', 'A definition is not retroactively applied as a verdict on past behaviour that was never agreed.'),
  ('SEX_INTIMACY.NONSEXUAL', 'QYRIS-PREMARRIAGE-001', 'SEX_INTIMACY', 'SEX_INTIMACY', null, 1, 3, 'What affection, touch, attention and time does each of us need that has nothing to do with sex?', 'A named list of non-sexual needs that can be met deliberately.', 'Collapsing every form of closeness into one act makes every refusal total.', 'Ask each person to name three specific things. Vagueness here predicts unmet need.', 'Meeting a non-sexual need is never treated as a down payment on a sexual one.'),
  ('HOUSEHOLD_LABOR', 'QYRIS-PREMARRIAGE-001', null, 'HOUSEHOLD_LABOR', 'HOUSEHOLD LABOR', 0, 6, 'Who does each piece of work that keeps this household running, including the work nobody sees?', 'A full task inventory with a named owner per task, including planning and remembering.', 'Household labour is settled by default rather than by decision, and the default is almost never even.', 'Track an actual week. Self-report and observation diverge substantially, in both directions.', 'Naming an imbalance is treated as information, not as an accusation, and is not answered with a list of the other person''s contributions.'),
  ('HOUSEHOLD_LABOR.INVENTORY', 'QYRIS-PREMARRIAGE-001', 'HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', null, 1, 0, 'What are all the tasks — including the ones that only exist because someone is tracking them?', 'A written list that includes scheduling, reminding, restocking and noticing.', 'The unwritten tasks are the ones that cause the exhaustion nobody can point to.', 'If the list is under thirty items, it is incomplete.', 'Building the list is itself a task and is not left to the person already doing more.'),
  ('HOUSEHOLD_LABOR.STANDARD', 'QYRIS-PREMARRIAGE-001', 'HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', null, 1, 1, 'Whose standard of clean, tidy, fed and organised applies?', 'An agreed standard per area rather than a permanent contest.', 'A higher standard held by one person becomes that person''s unpaid extra job.', 'Name the area and the standard concretely. "Clean kitchen" is not a standard.', 'Whoever holds the higher standard owns the gap, or the standard changes. It is not imposed as unnoticed labour on the other.'),
  ('HOUSEHOLD_LABOR.STANDARD.REDO', 'QYRIS-PREMARRIAGE-001', 'HOUSEHOLD_LABOR.STANDARD', 'HOUSEHOLD_LABOR', null, 2, 0, 'What happens when one of us redoes work the other already did?', 'A stated rule about redoing, and what it communicates when it happens.', 'Redoing a task is the clearest way to tell someone their work does not count, and it is almost never said out loud.', 'Count how often it happens in a real fortnight, and in which direction.', 'Either person may name redoing as it happens without it being treated as oversensitivity.'),
  ('HOUSEHOLD_LABOR.STANDARD.DELEGATION', 'QYRIS-PREMARRIAGE-001', 'HOUSEHOLD_LABOR.STANDARD', 'HOUSEHOLD_LABOR', null, 2, 1, 'When one of us asks the other to do something, who still carries the remembering?', 'A clear distinction between doing a task and owning it.', 'Being asked is not the same as being responsible, and the asker keeps the whole mental load either way.', 'Ask who would notice if the task simply stopped being done. That person owns it.', 'Ownership is transferred explicitly, not implied by having helped once.'),
  ('HOUSEHOLD_LABOR.CAPACITY', 'QYRIS-PREMARRIAGE-001', 'HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', null, 1, 2, 'What changes this allocation — illness, a new job, a baby, a caregiving season?', 'A named trigger list and a rule for renegotiation.', 'An allocation with no renegotiation rule becomes a grievance the moment circumstances move.', 'Walk two real scenarios and check whether the rule produces a workable answer.', 'Reduced capacity is not converted into a debt owed later.'),
  ('HOUSEHOLD_LABOR.PAID_HELP', 'QYRIS-PREMARRIAGE-001', 'HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', null, 1, 3, 'What can be bought instead of done, who decides that, and out of whose money?', 'A decision rule for outsourcing household work.', 'Paid help is often blocked by a value position that is never stated, only enforced.', 'Price one real task. The objection that survives the price is the actual objection.', 'Anyone paid to work in this household is engaged under the support-role rules — named scope, named pay, and no access beyond scope.'),
  ('CONFLICT', 'QYRIS-PREMARRIAGE-001', null, 'CONFLICT', 'CONFLICT', 0, 7, 'What does each of us do when we are angry, and what is never allowed to happen in a fight here?', 'Two described conflict patterns and a short list of absolute prohibitions.', 'Couples do not fail because they fight. They fail because of what is permitted during fights.', 'Describe the last three real conflicts, including who left the room, who raised their voice, and how it ended.', 'If any described behaviour involves violence, threat, restraint or intimidation, this pack stops and names a support route. It does not continue as a communication exercise.'),
  ('CONFLICT.PATTERN', 'QYRIS-PREMARRIAGE-001', 'CONFLICT', 'CONFLICT', null, 1, 0, 'When pressure rises, does each of us pursue, withdraw, escalate, comply or shut down?', 'A named pattern per person, and the pairing those two patterns produce.', 'The pairing predicts the failure mode more accurately than either pattern alone.', 'Check against a real fight. The pattern people claim and the pattern they run often differ.', 'A pattern is a description, not a diagnosis, and neither person is handed a label to use against the other.'),
  ('CONFLICT.PROHIBITED', 'QYRIS-PREMARRIAGE-001', 'CONFLICT', 'CONFLICT', null, 1, 1, 'What is never done here, no matter how justified it feels in the moment?', 'A short, absolute, unconditional list.', 'Prohibitions written while calm are the only ones available while angry.', 'Check each item is unconditional. Any item with an exception is not on the list.', 'Violence, threats, destruction of property, harm to animals, and threats involving children or immigration status are on the list by default and are not negotiable items.'),
  ('CONFLICT.PROHIBITED.BREACH', 'QYRIS-PREMARRIAGE-001', 'CONFLICT.PROHIBITED', 'CONFLICT', null, 2, 0, 'What happens the first time one of these is broken?', 'A consequence decided in advance and stated by the person who would face it.', 'A prohibition with no consequence is a preference.', 'Check the consequence is something that can actually be carried out.', 'The consequence for a safety breach is separation and outside help, not a negotiated apology.'),
  ('CONFLICT.PROHIBITED.EXIT', 'QYRIS-PREMARRIAGE-001', 'CONFLICT.PROHIBITED', 'CONFLICT', null, 2, 1, 'How does either of us leave a conversation safely, and what does the other do then?', 'An agreed pause protocol with a return time.', 'Leaving with no return time is abandonment; staying with no exit is entrapment.', 'Confirm the return time is specific and has actually been honoured before.', 'A pause may be taken by either person and is not blocked, followed or punished.'),
  ('CONFLICT.THIRD_PARTY', 'QYRIS-PREMARRIAGE-001', 'CONFLICT', 'CONFLICT', null, 1, 2, 'When do we bring in a counsellor, mediator, elder or friend, and who may call it?', 'A named threshold and an agreement that either person may trigger it alone.', 'Outside help is usually delayed until one person is already gone.', 'Check whether either person can call it without the other''s agreement. If not, it is not available.', 'Either person may seek individual support at any time without it being framed as building a case.'),
  ('CONFLICT.RECORD', 'QYRIS-PREMARRIAGE-001', 'CONFLICT', 'CONFLICT', null, 1, 3, 'What gets remembered from a fight, and what is allowed to be brought back later?', 'A rule about relitigating resolved matters.', 'A resolved matter that can be reopened as ammunition was never resolved.', 'Count how often a fight from over a year ago appears in a current one.', 'A pattern of genuine ongoing harm is exempt. This rule protects against ammunition, not against naming something that is still happening.'),
  ('HEALTH_CARE', 'QYRIS-PREMARRIAGE-001', null, 'HEALTH_CARE', 'HEALTH / CARE', 0, 8, 'What health realities does each of us carry, and who decides and provides care when one of us cannot?', 'A stated care position, a named decision-maker, and a named practical plan.', 'Care decisions get made in hospital corridors by whoever is present, unless they were made earlier.', 'Check whether the named decision-maker is legally documented. An intention is not a directive.', 'No medical detail is stored by this system. Only positions, decisions and named documents are recorded.'),
  ('HEALTH_CARE.DISCLOSURE', 'QYRIS-PREMARRIAGE-001', 'HEALTH_CARE', 'HEALTH_CARE', null, 1, 0, 'What conditions, diagnoses or risks does each of us want the other to know before marrying?', 'A voluntary disclosure at the depth each person chooses.', 'A condition discovered after the fact is experienced as deception even when it was only privacy.', 'The pack does not verify this. It records that the conversation happened and at what depth.', 'Disclosure is voluntary. Declining to disclose is recorded as declining, never as a negative finding, and never as a false statement.'),
  ('HEALTH_CARE.DECISION', 'QYRIS-PREMARRIAGE-001', 'HEALTH_CARE', 'HEALTH_CARE', null, 1, 1, 'Who decides for each of us when we cannot decide, and is it written down where a hospital will accept it?', 'A named proxy per person and the document that establishes it.', 'Without documentation the decision may fall to a relative neither spouse would choose.', 'Confirm the document exists, is signed, and is valid in the relevant jurisdiction.', 'Each person names their own proxy. It is not assumed to be the spouse, and it may be changed at any time without notice to anyone.'),
  ('HEALTH_CARE.DECISION.LIMITS', 'QYRIS-PREMARRIAGE-001', 'HEALTH_CARE.DECISION', 'HEALTH_CARE', null, 2, 0, 'What treatment does each of us want, refuse, or want stopped?', 'A written directive in each person''s own words.', 'A proxy without instructions is asked to guess during the worst hour of their life.', 'This is a legal and clinical document. The pack records that it exists and where.', 'The content stays with the person and their clinician. This system stores only the fact of its existence.'),
  ('HEALTH_CARE.DECISION.ELDERS', 'QYRIS-PREMARRIAGE-001', 'HEALTH_CARE.DECISION', 'HEALTH_CARE', null, 2, 1, 'Which parents or elders may need care, who provides it, and out of whose time and money?', 'A named expectation per elder, with the practical load identified.', 'Elder care lands on whoever is nearest or most willing, and is rarely planned as a shared obligation.', 'Ask what happens in the specific case of a parent needing daily care within two years.', 'The person doing the caring is not left to absorb the cost invisibly. Care work is counted as work.'),
  ('HEALTH_CARE.INSURANCE', 'QYRIS-PREMARRIAGE-001', 'HEALTH_CARE', 'HEALTH_CARE', null, 1, 2, 'How is each of us covered, what happens to that coverage on marriage, and what is not covered?', 'A coverage map with named gaps.', 'Coverage changes at marriage in ways that are discovered at the first claim.', 'Read the actual policy terms for the specific change of status.', 'Neither person is pressured to drop independent coverage for a saving that removes their own standing.'),
  ('HEALTH_CARE.MENTAL', 'QYRIS-PREMARRIAGE-001', 'HEALTH_CARE', 'HEALTH_CARE', null, 1, 3, 'What mental health support does each of us use or need, and how is it protected in this marriage?', 'A stated support arrangement and an agreement about its privacy.', 'Support that a spouse resents or surveils tends to be abandoned precisely when it is needed.', 'Check whether each person could continue their support if the other disapproved.', 'Therapy content is private. A spouse is not entitled to it, and this system never stores it.'),
  ('CAREERS', 'QYRIS-PREMARRIAGE-001', null, 'CAREERS', 'CAREERS', 0, 9, 'Whose work moves first when the two cannot both be accommodated, and how is that decided each time?', 'A decision rule for career conflicts, agreed before a specific offer is on the table.', 'Without a rule, the higher earner wins by default and the other career quietly becomes secondary.', 'Apply the rule to a real offer. A rule that has never been tested against a concrete case is untested.', 'The rule is symmetrical and reviewable. Deferring once does not establish a permanent order.'),
  ('CAREERS.AMBITION', 'QYRIS-PREMARRIAGE-001', 'CAREERS', 'CAREERS', null, 1, 0, 'What does each of us actually want from work in ten years, stated without editing for the other?', 'Two unedited ambitions that can then be compared honestly.', 'Ambitions trimmed to fit a partner resurface later as grief.', 'Ask separately. The edited version appears when the other is in the room.', 'An ambition is not treated as a threat, and stating it is not a commitment to pursue it.'),
  ('CAREERS.SACRIFICE', 'QYRIS-PREMARRIAGE-001', 'CAREERS', 'CAREERS', null, 1, 1, 'If one of us steps back for the household, what does that person get in return and for how long?', 'A named, time-bounded arrangement with a stated return.', 'An indefinite step-back with no return term is the most common uncompensated transfer in marriage.', 'Check whether the return is specified enough to be claimed later. "We will sort it out" cannot be claimed.', 'The stepping-back person keeps independent money, independent retirement contributions and a named date for review.'),
  ('CAREERS.SACRIFICE.REENTRY', 'QYRIS-PREMARRIAGE-001', 'CAREERS.SACRIFICE', 'CAREERS', null, 2, 0, 'What keeps the stepped-back career re-enterable — skills, licences, network, hours?', 'A concrete maintenance plan with a cost and an owner.', 'Re-entry difficulty compounds silently and is only discovered when re-entry is attempted.', 'Name the specific licence, certification or contact that decays, and its renewal interval.', 'The maintenance cost is a household cost, not the stepped-back person''s private expense.'),
  ('CAREERS.SACRIFICE.ENDING', 'QYRIS-PREMARRIAGE-001', 'CAREERS.SACRIFICE', 'CAREERS', null, 2, 1, 'If the marriage ended during this arrangement, what would the stepped-back person have?', 'An honest statement of the position that arrangement creates.', 'The arrangement creates a dependency, and the dependency should be entered with open eyes.', 'Count retirement contributions, independent income, credit history and housing standing.', 'Asking is not planning to leave. The answer informs what protection the arrangement needs.'),
  ('CAREERS.HOURS', 'QYRIS-PREMARRIAGE-001', 'CAREERS', 'CAREERS', null, 1, 2, 'What hours, travel and availability does each job actually demand, now and in the likely next role?', 'A realistic time budget per person.', 'Couples plan around current hours and are surprised by the next promotion''s hours.', 'Look at people one level up in the same organisation. That is the real forecast.', 'A demanding job is a fact to plan around, not a moral failing to be argued about.'),
  ('CAREERS.RISK', 'QYRIS-PREMARRIAGE-001', 'CAREERS', 'CAREERS', null, 1, 3, 'What appetite does each of us have for the other starting a business, going freelance, or taking a pay cut for meaning?', 'A stated risk appetite with a floor below which the answer is no.', 'Risk tolerance is discovered mid-venture unless it is stated in advance.', 'Name the floor as an amount and a duration, not as a feeling.', 'The floor protects the household, and the person taking the risk agrees to it rather than having it imposed mid-flight.'),
  ('GEOGRAPHY', 'QYRIS-PREMARRIAGE-001', null, 'GEOGRAPHY', 'GEOGRAPHY', 0, 10, 'Where will we live, who is farther from home, and what would make either of us refuse to move?', 'A location decision with the refusal conditions named in advance.', 'Location determines proximity to family, career options, safety and belonging all at once.', 'Ask each person for their hard no. If neither has one, it has not been considered.', 'Distance from one person''s support network is named as a cost that person carries, and is not dismissed as a preference.'),
  ('GEOGRAPHY.ROOTS', 'QYRIS-PREMARRIAGE-001', 'GEOGRAPHY', 'GEOGRAPHY', null, 1, 0, 'What does each of us lose by being far from where we are from?', 'A named list of what distance actually costs each person.', 'The person who moved is usually the person who is lonely, and it is rarely counted.', 'Name specific people and specific occasions that would be missed.', 'The cost is budgeted for — visits, calls, time off — rather than expected to be absorbed.'),
  ('GEOGRAPHY.SAFETY', 'QYRIS-PREMARRIAGE-001', 'GEOGRAPHY', 'GEOGRAPHY', null, 1, 1, 'Is either of us less safe in some places than the other, and does that change where we can live?', 'An honest statement of differential safety by place.', 'Two people in the same town can live in materially different countries.', 'Ask the person more exposed. The less exposed person''s assessment is not the measurement.', 'The more exposed person''s assessment governs. It is not debated, minimised or overruled by the other''s experience of the same place.'),
  ('GEOGRAPHY.STATUS', 'QYRIS-PREMARRIAGE-001', 'GEOGRAPHY', 'GEOGRAPHY', null, 1, 2, 'Does either of us have an immigration, visa, residency or citizenship position that this marriage affects?', 'A named legal position and the effect of marriage on it.', 'Immigration status creates a power asymmetry that shapes every other negotiation in the marriage.', 'This is a legal question. The pack names it and routes it to an immigration lawyer.', 'Status is never used as leverage. Any threat involving a partner''s status is named here, in advance, as abuse — and a support route is given.'),
  ('GEOGRAPHY.STATUS.DEPENDENCE', 'QYRIS-PREMARRIAGE-001', 'GEOGRAPHY.STATUS', 'GEOGRAPHY', null, 2, 0, 'Does either of us depend on the other for the right to remain, and for how long?', 'A named dependency with a named end date or condition.', 'A dependency with no end date is an open-ended power imbalance inside a marriage of supposed equals.', 'Confirm the actual route to independent status and its real timeline with a lawyer, not from memory.', 'The dependent person is told, before marrying, what protections exist for them if the marriage becomes unsafe. That information is not withheld to keep the peace.'),
  ('GEOGRAPHY.STATUS.DOCUMENTS', 'QYRIS-PREMARRIAGE-001', 'GEOGRAPHY.STATUS', 'GEOGRAPHY', null, 2, 1, 'Who physically holds each person''s passport, identity documents and immigration paperwork?', 'A named holder per document, and an answer to whether each person can reach their own.', 'Withholding documents is one of the most common and least visible forms of control.', 'Ask where the documents are right now, and whether each person could collect their own today.', 'Each person holds their own documents. If that is not currently true, this pack names it as a safety matter with a support route, not as a household arrangement.'),
  ('GEOGRAPHY.HOUSING', 'QYRIS-PREMARRIAGE-001', 'GEOGRAPHY', 'GEOGRAPHY', null, 1, 3, 'Do we rent or buy, whose name is on it, and what happens to the home if we separate?', 'A named ownership position and a named separation outcome for the home.', 'Whose name is on the housing determines who has to leave in the worst week.', 'Read the lease or deed. Contribution without legal title is not title.', 'A person contributing to a home they do not own is told plainly what that does and does not give them.'),
  ('PRIVACY', 'QYRIS-PREMARRIAGE-001', null, 'PRIVACY', 'PRIVACY', 0, 11, 'What remains each person''s own inside this marriage — devices, accounts, history, thoughts, friendships?', 'A stated privacy line per domain, agreed rather than assumed.', 'Marriage is frequently assumed to mean total access, and that assumption is where surveillance begins.', 'Ask what each person would do if the other asked to read their messages. The answer reveals the operating rule.', 'Privacy is not evidence of wrongdoing. This pack does not treat a request for privacy as a finding.'),
  ('PRIVACY.DEVICES', 'QYRIS-PREMARRIAGE-001', 'PRIVACY', 'PRIVACY', null, 1, 0, 'Do we share passwords and locations, and is that mutual, voluntary and revocable?', 'A stated access arrangement with an explicit revocation right.', 'Shared access that cannot be revoked is not sharing; it is monitoring.', 'Check whether either person could turn location sharing off today without a confrontation.', 'Either person may revoke access at any time without explanation. If that is not true, the arrangement is coercive and is named as such.'),
  ('PRIVACY.DEVICES.MONITORING', 'QYRIS-PREMARRIAGE-001', 'PRIVACY.DEVICES', 'PRIVACY', null, 2, 0, 'Is either of us monitoring the other — location, messages, spending, browser, contacts?', 'A direct answer about current monitoring.', 'Monitoring usually starts as reassurance and does not stop on its own.', 'Ask each person separately. Monitoring is frequently unknown to the monitored.', 'Discovered monitoring is treated as a safety matter with a support route, not as a trust exercise to be worked through together.'),
  ('PRIVACY.DEVICES.SHARED_RECORDS', 'QYRIS-PREMARRIAGE-001', 'PRIVACY.DEVICES', 'PRIVACY', null, 2, 1, 'What about this marriage is written down, where, and who can read it later?', 'A named list of shared records and their access rules.', 'Records made together in a good season are read alone in a bad one.', 'Include this pack''s own answers in the list. It is a record like any other.', 'Each person may delete their own answers in this system at any time. A deleted answer is deleted, not archived where the other can still reach it.'),
  ('PRIVACY.HISTORY', 'QYRIS-PREMARRIAGE-001', 'PRIVACY', 'PRIVACY', null, 1, 1, 'What from each of our pasts is the other entitled to know, and what is genuinely ours alone?', 'A stated line between relevant history and private history.', 'Demanding a complete past is not intimacy; it is an audit.', 'Separate what affects the marriage materially from what only satisfies curiosity.', 'Anything material to health, safety, money, legal standing or existing children is on the disclosable side. Everything else stays the person''s own.'),
  ('PRIVACY.FRIENDSHIPS', 'QYRIS-PREMARRIAGE-001', 'PRIVACY', 'PRIVACY', null, 1, 2, 'What friendships does each of us keep independently, and what may the other veto?', 'A stated veto scope, if any, and its limits.', 'Isolation from friends is usually built one reasonable-sounding veto at a time.', 'Count each person''s independent friendships now, and again in a year.', 'A shrinking independent social world is flagged by this pack as a risk indicator, regardless of the reasons given for each individual case.'),
  ('PRIVACY.PUBLIC', 'QYRIS-PREMARRIAGE-001', 'PRIVACY', 'PRIVACY', null, 1, 3, 'What may be posted publicly about this marriage, our home, our children and our faces?', 'A publication rule with a default and a veto.', 'One person''s ordinary sharing is another person''s exposure, and children cannot consent at all.', 'Check what is already public. That is the current rule in force.', 'Default is no. Either person may veto any specific post about themselves or a child, without argument and after the fact.'),
  ('TRUST', 'QYRIS-PREMARRIAGE-001', null, 'TRUST', 'TRUST', 0, 12, 'What would each of us have to do to lose the other''s trust, and what has already happened that is not yet resolved?', 'A named breach threshold per person and an inventory of unresolved matters.', 'Marriages are entered carrying unresolved matter that both people have agreed not to mention.', 'Ask what each person has decided not to bring up. The list is rarely empty.', 'A matter raised here is met once without escalation, or the question should not have been asked.'),
  ('TRUST.OUTSTANDING', 'QYRIS-PREMARRIAGE-001', 'TRUST', 'TRUST', null, 1, 0, 'What is still unresolved between us right now?', 'A written list of open matters rather than a shared silence.', 'Unresolved matter does not decay; it accrues.', 'If the list is empty, ask again separately. Empty lists are usually courteous rather than accurate.', 'Listing a matter does not commit either person to resolving it today.'),
  ('TRUST.THRESHOLD', 'QYRIS-PREMARRIAGE-001', 'TRUST', 'TRUST', null, 1, 1, 'What specifically would end this for each of us?', 'A stated, concrete threshold rather than an implied one.', 'An unstated threshold can be crossed by someone who genuinely did not know it existed.', 'Check each threshold is specific enough that a reasonable person could avoid crossing it.', 'Stating a threshold is not issuing a threat, and it does not obligate the person to act on it if it is crossed.'),
  ('TRUST.THRESHOLD.SECRECY', 'QYRIS-PREMARRIAGE-001', 'TRUST.THRESHOLD', 'TRUST', null, 2, 0, 'What is the difference, for each of us, between something private and something hidden?', 'Two working definitions that can be applied to a real case.', 'Most betrayal arguments are a collision between one person''s privacy and the other''s definition of concealment.', 'Test with three concrete cases, including one financial and one involving a friendship.', 'Neither definition is imposed. Where they differ, the difference is recorded as a known difference rather than settled by whoever is more upset.'),
  ('TRUST.THRESHOLD.DISCOVERY', 'QYRIS-PREMARRIAGE-001', 'TRUST.THRESHOLD', 'TRUST', null, 2, 1, 'If one of us crossed a threshold, would we rather hear it from the other or find it ourselves?', 'A stated preference that makes disclosure survivable rather than fatal.', 'The cost of disclosure determines whether anything is ever disclosed.', 'Check whether past disclosures were met in a way that makes the next one more or less likely.', 'A stated willingness to hear it first is honoured at least once, or it was not a real offer.'),
  ('TRUST.VERIFICATION', 'QYRIS-PREMARRIAGE-001', 'TRUST', 'TRUST', null, 1, 2, 'What does each of us take on trust that could be checked, and are we choosing not to check?', 'A conscious decision about where verification stops.', 'Trust chosen with the option to verify is different from trust that had no alternative.', 'Separate three things: what was verified, what was taken on trust, and what could not be checked at all.', 'Choosing not to verify is legitimate and is recorded as a choice, so it is not later rewritten as having been deceived.'),
  ('TRUST.REPAIRED', 'QYRIS-PREMARRIAGE-001', 'TRUST', 'TRUST', null, 1, 3, 'What has already been broken and repaired between us, and what did the repair actually consist of?', 'A record of the repair pattern this couple has demonstrated.', 'Demonstrated repair is the best available evidence of future repair.', 'Check whether the behaviour changed or only the apology arrived.', 'A past breach that has been genuinely repaired is not reopened by this question.'),
  ('FUTURE_CHANGE', 'QYRIS-PREMARRIAGE-001', null, 'FUTURE_CHANGE', 'FUTURE CHANGE', 0, 13, 'What changes in each of us would this marriage survive, and which ones would it not?', 'A named set of foreseeable changes with a stated response to each.', 'People change in ways that are foreseeable in category even when unforeseeable in detail.', 'Test with five concrete changes rather than a general willingness to adapt.', 'No person is asked to promise not to change. The question is what the other would do, not what the changer owes.'),
  ('FUTURE_CHANGE.IDENTITY', 'QYRIS-PREMARRIAGE-001', 'FUTURE_CHANGE', 'FUTURE_CHANGE', null, 1, 0, 'What if one of us changed faith, politics, gender presentation, sobriety or community?', 'A stated response per change rather than an assumption of permanence.', 'The response is what determines whether change is survivable, not the change itself.', 'Ask about each specifically. General tolerance rarely survives specification.', 'An honest "I do not know" is recorded as-is. It is more useful than a reassurance that will not hold.'),
  ('FUTURE_CHANGE.LOSS', 'QYRIS-PREMARRIAGE-001', 'FUTURE_CHANGE', 'FUTURE_CHANGE', null, 1, 1, 'What if one of us lost their health, their income, their parent, or a child?', 'A named support plan for the worst foreseeable seasons.', 'Grief and disability change a marriage more than almost anything else, and they are rarely discussed before they arrive.', 'Ask who would do what, practically, in the first month of each scenario.', 'Nobody is asked to guarantee their own capacity in advance. The plan names outside support, not just each other.'),
  ('FUTURE_CHANGE.LOSS.CAPACITY', 'QYRIS-PREMARRIAGE-001', 'FUTURE_CHANGE.LOSS', 'FUTURE_CHANGE', null, 2, 0, 'If one of us became a full-time carer for the other, what would that person need to stay a person?', 'A named list of what the carer needs — respite, income, their own care, time away.', 'The carer is the one who disappears, and nobody plans for them because they are not the one who is ill.', 'Name who provides the respite. A plan with no named relief is not a plan.', 'Naming a limit on what one can carry is not abandonment, and it is better said in advance than discovered at collapse.'),
  ('FUTURE_CHANGE.LOSS.GRIEF', 'QYRIS-PREMARRIAGE-001', 'FUTURE_CHANGE.LOSS', 'FUTURE_CHANGE', null, 2, 1, 'How does each of us grieve, and what does the other do that helps or makes it worse?', 'Two described grief patterns and a concrete instruction for the other person.', 'Couples most often fail each other in grief by offering the comfort they would want rather than the one that is needed.', 'Ask about a real past loss. What actually helped, and what did not.', 'A grief pattern is not corrected. Neither person is told they are grieving wrongly.'),
  ('FUTURE_CHANGE.REVIEW', 'QYRIS-PREMARRIAGE-001', 'FUTURE_CHANGE', 'FUTURE_CHANGE', null, 1, 2, 'When do we deliberately revisit all of this, and who can call a review early?', 'A scheduled review date and a unilateral trigger right.', 'Agreements without a review date are enforced against people who have since changed.', 'Check the date is in a calendar, not in an intention.', 'Either person may call a review at any time without needing to justify why.'),
  ('FUTURE_CHANGE.ESTATE', 'QYRIS-PREMARRIAGE-001', 'FUTURE_CHANGE', 'FUTURE_CHANGE', null, 1, 3, 'What happens to what each of us owns, and to any existing children, if one of us dies?', 'A named estate position and whether documents exist.', 'Intestacy rules distribute an estate in a way that frequently surprises blended families.', 'Confirm the will, beneficiary designations and any trust exist and are current. Beneficiary forms override wills more often than people expect.', 'Existing children''s provision is settled explicitly rather than left to a default rule or a survivor''s goodwill.'),
  ('DEAL_BREAKERS', 'QYRIS-PREMARRIAGE-001', null, 'DEAL_BREAKERS', 'DEAL BREAKERS', 0, 14, 'What is each of us unwilling to accept under any circumstances, stated plainly and without negotiation?', 'Two short lists of absolute limits, in each person''s own words.', 'A limit that is never stated is discovered only by being crossed.', 'Check each item is genuinely absolute. Anything with a condition belongs in a different cluster.', 'A deal breaker is stated, not defended. The other person is not entitled to argue it down in this session.'),
  ('DEAL_BREAKERS.STATED', 'QYRIS-PREMARRIAGE-001', 'DEAL_BREAKERS', 'DEAL_BREAKERS', null, 1, 0, 'What are the items, in plain words, with no softening?', 'The unsoftened list.', 'Softened limits are not usable later.', 'Read each item back. If it now sounds negotiable, it was softened.', 'Nobody is required to explain why an item is on their list.'),
  ('DEAL_BREAKERS.CONFLICT', 'QYRIS-PREMARRIAGE-001', 'DEAL_BREAKERS', 'DEAL_BREAKERS', null, 1, 1, 'Does either of us currently do something that is on the other''s list?', 'An honest identification of a live incompatibility.', 'This is the single most useful finding a pre-marriage process can produce.', 'Cross the two lists against current behaviour, item by item.', 'A live incompatibility is allowed to be named without an immediate decision being demanded in the same conversation.'),
  ('DEAL_BREAKERS.CONFLICT.HONESTY', 'QYRIS-PREMARRIAGE-001', 'DEAL_BREAKERS.CONFLICT', 'DEAL_BREAKERS', null, 2, 0, 'Is either of us planning to change after the wedding rather than before it?', 'An honest answer about intended post-wedding change.', 'Change promised for after the ceremony is the least likely change to occur.', 'Check whether the change has been attempted before, and what happened.', 'The answer is not held against the person as evidence of bad faith. It is treated as information about timing and support.'),
  ('DEAL_BREAKERS.CONFLICT.DECISION', 'QYRIS-PREMARRIAGE-001', 'DEAL_BREAKERS.CONFLICT', 'DEAL_BREAKERS', null, 2, 1, 'If this does not resolve, what does each of us do?', 'A stated path, including the path of not marrying.', 'Not marrying must remain a live, speakable option or the whole process is theatre.', 'Check whether either person believes they can still say no. If not, the process has no integrity.', 'Either person may end the process at any point. Cost already spent on a wedding is never treated as a reason to proceed.'),
  ('DEAL_BREAKERS.SAFETY_FLOOR', 'QYRIS-PREMARRIAGE-001', 'DEAL_BREAKERS', 'DEAL_BREAKERS', null, 1, 2, 'Which items are on the list by default, regardless of what either person says?', 'A stated floor that does not depend on either person having thought of it.', 'Some limits should not depend on a person being well enough to name them.', 'Confirm the floor is visible to both people before the lists are written.', 'Violence, coercion, threats to children, threats involving immigration status, and controlling access to money, documents or medical care are on the floor. They are not removable by agreement.'),
  ('DEAL_BREAKERS.REVIEW', 'QYRIS-PREMARRIAGE-001', 'DEAL_BREAKERS', 'DEAL_BREAKERS', null, 1, 3, 'Can an item ever leave the list, and by what process?', 'A stated revision process owned by the person whose list it is.', 'Lists that can never change become instruments rather than protections.', 'Confirm only the list''s owner may remove an item from it.', 'Removal is never done under pressure, in a fight, or as a condition of reconciliation. Floor items cannot be removed at all.'),
  ('REPAIR', 'QYRIS-PREMARRIAGE-001', null, 'REPAIR', 'REPAIR', 0, 15, 'When one of us has hurt the other, what actually repairs it here — in actions, not sentiments?', 'A described repair sequence both people recognise as sufficient.', 'Marriages survive on repair capacity far more than on compatibility.', 'Describe a real past repair and check whether both people agree it worked.', 'Repair is not the wronged person''s job. They are not required to manage the other''s guilt as part of being hurt.'),
  ('REPAIR.SEQUENCE', 'QYRIS-PREMARRIAGE-001', 'REPAIR', 'REPAIR', null, 1, 0, 'What are the steps — acknowledgement, specifics, change, time, and what else?', 'A named sequence that can be followed while upset.', 'A sequence agreed while calm is the only one available while ashamed.', 'Check whether the sequence includes a behaviour change, not only an apology.', 'Nobody is required to accept a repair on a schedule. Time is part of the sequence.'),
  ('REPAIR.SEQUENCE.SPECIFICS', 'QYRIS-PREMARRIAGE-001', 'REPAIR.SEQUENCE', 'REPAIR', null, 2, 0, 'Does the acknowledgement name the specific thing, or only that something happened?', 'A test each person can apply to a repair as it is offered.', 'A general apology leaves the wronged person to carry the specifics alone, which is more work than the original injury.', 'Check whether the person apologising can state what they did without being told.', 'The wronged person is never required to prosecute the case to receive the apology.'),
  ('REPAIR.SEQUENCE.COST', 'QYRIS-PREMARRIAGE-001', 'REPAIR.SEQUENCE', 'REPAIR', null, 2, 1, 'What does the repair cost the person making it, and is that cost visible?', 'A named cost — time, a habit given up, a boundary accepted — rather than words alone.', 'A repair that costs nothing is indistinguishable from a repair that was not meant.', 'Check whether anything about the next week is different. If not, nothing was paid.', 'The cost is chosen by the person making the repair, not set as a punishment by the other.'),
  ('REPAIR.REFUSAL', 'QYRIS-PREMARRIAGE-001', 'REPAIR', 'REPAIR', null, 1, 1, 'What happens when a repair is offered and not accepted?', 'A stated response to non-acceptance.', 'Repair refused is where a second, larger injury usually happens.', 'Check whether the response includes pressure. If it does, the repair was conditional.', 'Non-acceptance is not punished. The wronged person keeps the right to still be hurt.'),
  ('REPAIR.PATTERN', 'QYRIS-PREMARRIAGE-001', 'REPAIR', 'REPAIR', null, 1, 2, 'What do we do when the same thing needs repairing for the fourth time?', 'A named escalation from repair to outside help or structural change.', 'Repeated repair of the same injury is a system problem, not a series of incidents.', 'Count repeats. Four is a number, not a mood.', 'Naming a pattern is not refusing to forgive. Forgiveness and a structural change are both allowed at once.'),
  ('REPAIR.UNREPAIRABLE', 'QYRIS-PREMARRIAGE-001', 'REPAIR', 'REPAIR', null, 1, 3, 'What could happen here that repair would not fix, and what do we do then?', 'An honest acknowledgement that some things do not repair, and a named response.', 'A marriage that believes everything is repairable has no floor under it.', 'Cross-check against the deal-breaker floor. They should agree.', 'Naming the unrepairable is not predicting failure. It is what makes the rest of the repair work trustworthy.')
on conflict (node_id) do update set
  pack_id = excluded.pack_id, parent_id = excluded.parent_id, cluster_id = excluded.cluster_id,
  label = excluded.label, depth = excluded.depth, ordinal = excluded.ordinal,
  question = excluded.question, yield = excluded.yield, reason = excluded.reason,
  inspect = excluded.inspect, safeguard = excluded.safeguard;

insert into qyr_node_deltas (node_id, delta_code) values
  ('MONEY', 'ACTION'),
  ('MONEY', 'EVIDENCE'),
  ('MONEY', 'RISK'),
  ('MONEY', 'AUTHORITY'),
  ('MONEY', 'TRANSFER'),
  ('MONEY.INCOME', 'EVIDENCE'),
  ('MONEY.INCOME', 'RISK'),
  ('MONEY.ACCOUNTS', 'ACTION'),
  ('MONEY.ACCOUNTS', 'AUTHORITY'),
  ('MONEY.ACCOUNTS', 'TRANSFER'),
  ('MONEY.ACCOUNTS.THRESHOLD', 'ACTION'),
  ('MONEY.ACCOUNTS.THRESHOLD', 'AUTHORITY'),
  ('MONEY.ACCOUNTS.EXIT', 'RISK'),
  ('MONEY.ACCOUNTS.EXIT', 'AUTHORITY'),
  ('MONEY.ACCOUNTS.EXIT', 'TRANSFER'),
  ('MONEY.HISTORY', 'RISK'),
  ('MONEY.SUPPORT', 'EVIDENCE'),
  ('MONEY.SUPPORT', 'TRANSFER'),
  ('DEBT', 'ACTION'),
  ('DEBT', 'EVIDENCE'),
  ('DEBT', 'RISK'),
  ('DEBT', 'AUTHORITY'),
  ('DEBT', 'TRANSFER'),
  ('DEBT.INVENTORY', 'EVIDENCE'),
  ('DEBT.INVENTORY', 'ACTION'),
  ('DEBT.EXPOSURE', 'RISK'),
  ('DEBT.EXPOSURE', 'AUTHORITY'),
  ('DEBT.EXPOSURE', 'TRANSFER'),
  ('DEBT.EXPOSURE.COSIGN', 'ACTION'),
  ('DEBT.EXPOSURE.COSIGN', 'AUTHORITY'),
  ('DEBT.EXPOSURE.COSIGN', 'TRANSFER'),
  ('DEBT.EXPOSURE.HIDDEN', 'EVIDENCE'),
  ('DEBT.EXPOSURE.HIDDEN', 'RISK'),
  ('DEBT.PLAN', 'ACTION'),
  ('DEBT.PLAN', 'AUTHORITY'),
  ('DEBT.FUTURE', 'ACTION'),
  ('DEBT.FUTURE', 'RISK'),
  ('CHILDREN', 'ACTION'),
  ('CHILDREN', 'EVIDENCE'),
  ('CHILDREN', 'RISK'),
  ('CHILDREN', 'AUTHORITY'),
  ('CHILDREN', 'TRANSFER'),
  ('CHILDREN.EXISTING', 'EVIDENCE'),
  ('CHILDREN.EXISTING', 'AUTHORITY'),
  ('CHILDREN.EXISTING', 'TRANSFER'),
  ('CHILDREN.FERTILITY', 'ACTION'),
  ('CHILDREN.FERTILITY', 'RISK'),
  ('CHILDREN.FERTILITY.ALTERNATIVES', 'ACTION'),
  ('CHILDREN.FERTILITY.ALTERNATIVES', 'RISK'),
  ('CHILDREN.FERTILITY.STOP', 'AUTHORITY'),
  ('CHILDREN.FERTILITY.STOP', 'RISK'),
  ('CHILDREN.RAISING', 'ACTION'),
  ('CHILDREN.RAISING', 'AUTHORITY'),
  ('CHILDREN.LOAD', 'ACTION'),
  ('CHILDREN.LOAD', 'RISK'),
  ('CHILDREN.LOAD', 'TRANSFER'),
  ('FAMILY_BOUNDARIES', 'ACTION'),
  ('FAMILY_BOUNDARIES', 'RISK'),
  ('FAMILY_BOUNDARIES', 'AUTHORITY'),
  ('FAMILY_BOUNDARIES.ACCESS', 'ACTION'),
  ('FAMILY_BOUNDARIES.ACCESS', 'AUTHORITY'),
  ('FAMILY_BOUNDARIES.INFORMATION', 'RISK'),
  ('FAMILY_BOUNDARIES.INFORMATION', 'AUTHORITY'),
  ('FAMILY_BOUNDARIES.INFORMATION.CONFLICT', 'RISK'),
  ('FAMILY_BOUNDARIES.INFORMATION.CONFLICT', 'AUTHORITY'),
  ('FAMILY_BOUNDARIES.INFORMATION.REPAIR', 'ACTION'),
  ('FAMILY_BOUNDARIES.OBLIGATION', 'ACTION'),
  ('FAMILY_BOUNDARIES.OBLIGATION', 'TRANSFER'),
  ('FAMILY_BOUNDARIES.CULTURE', 'ACTION'),
  ('FAMILY_BOUNDARIES.CULTURE', 'TRANSFER'),
  ('FAITH_WORLDVIEW', 'ACTION'),
  ('FAITH_WORLDVIEW', 'RISK'),
  ('FAITH_WORLDVIEW', 'AUTHORITY'),
  ('FAITH_WORLDVIEW.PRACTICE', 'ACTION'),
  ('FAITH_WORLDVIEW.AUTHORITY', 'AUTHORITY'),
  ('FAITH_WORLDVIEW.AUTHORITY', 'RISK'),
  ('FAITH_WORLDVIEW.AUTHORITY.CHANGE', 'RISK'),
  ('FAITH_WORLDVIEW.AUTHORITY.CHANGE', 'AUTHORITY'),
  ('FAITH_WORLDVIEW.AUTHORITY.CHILDREN', 'ACTION'),
  ('FAITH_WORLDVIEW.AUTHORITY.CHILDREN', 'AUTHORITY'),
  ('FAITH_WORLDVIEW.COMMUNITY', 'RISK'),
  ('FAITH_WORLDVIEW.HERITAGE', 'EVIDENCE'),
  ('FAITH_WORLDVIEW.HERITAGE', 'RISK'),
  ('SEX_INTIMACY', 'ACTION'),
  ('SEX_INTIMACY', 'RISK'),
  ('SEX_INTIMACY', 'AUTHORITY'),
  ('SEX_INTIMACY.EXPECTATION', 'RISK'),
  ('SEX_INTIMACY.REFUSAL', 'RISK'),
  ('SEX_INTIMACY.REFUSAL', 'AUTHORITY'),
  ('SEX_INTIMACY.REFUSAL.SAFETY', 'RISK'),
  ('SEX_INTIMACY.REFUSAL.SAFETY', 'AUTHORITY'),
  ('SEX_INTIMACY.REFUSAL.HEALTH', 'ACTION'),
  ('SEX_INTIMACY.REFUSAL.HEALTH', 'RISK'),
  ('SEX_INTIMACY.EXCLUSIVITY', 'ACTION'),
  ('SEX_INTIMACY.EXCLUSIVITY', 'AUTHORITY'),
  ('SEX_INTIMACY.NONSEXUAL', 'ACTION'),
  ('HOUSEHOLD_LABOR', 'ACTION'),
  ('HOUSEHOLD_LABOR', 'EVIDENCE'),
  ('HOUSEHOLD_LABOR', 'TRANSFER'),
  ('HOUSEHOLD_LABOR.INVENTORY', 'EVIDENCE'),
  ('HOUSEHOLD_LABOR.INVENTORY', 'ACTION'),
  ('HOUSEHOLD_LABOR.STANDARD', 'ACTION'),
  ('HOUSEHOLD_LABOR.STANDARD', 'AUTHORITY'),
  ('HOUSEHOLD_LABOR.STANDARD.REDO', 'ACTION'),
  ('HOUSEHOLD_LABOR.STANDARD.REDO', 'RISK'),
  ('HOUSEHOLD_LABOR.STANDARD.DELEGATION', 'ACTION'),
  ('HOUSEHOLD_LABOR.STANDARD.DELEGATION', 'AUTHORITY'),
  ('HOUSEHOLD_LABOR.STANDARD.DELEGATION', 'TRANSFER'),
  ('HOUSEHOLD_LABOR.CAPACITY', 'ACTION'),
  ('HOUSEHOLD_LABOR.CAPACITY', 'RISK'),
  ('HOUSEHOLD_LABOR.PAID_HELP', 'ACTION'),
  ('HOUSEHOLD_LABOR.PAID_HELP', 'TRANSFER'),
  ('CONFLICT', 'ACTION'),
  ('CONFLICT', 'RISK'),
  ('CONFLICT', 'AUTHORITY'),
  ('CONFLICT.PATTERN', 'EVIDENCE'),
  ('CONFLICT.PATTERN', 'RISK'),
  ('CONFLICT.PROHIBITED', 'ACTION'),
  ('CONFLICT.PROHIBITED', 'RISK'),
  ('CONFLICT.PROHIBITED', 'AUTHORITY'),
  ('CONFLICT.PROHIBITED.BREACH', 'ACTION'),
  ('CONFLICT.PROHIBITED.BREACH', 'AUTHORITY'),
  ('CONFLICT.PROHIBITED.EXIT', 'ACTION'),
  ('CONFLICT.PROHIBITED.EXIT', 'AUTHORITY'),
  ('CONFLICT.THIRD_PARTY', 'ACTION'),
  ('CONFLICT.THIRD_PARTY', 'AUTHORITY'),
  ('CONFLICT.RECORD', 'ACTION'),
  ('HEALTH_CARE', 'ACTION'),
  ('HEALTH_CARE', 'RISK'),
  ('HEALTH_CARE', 'AUTHORITY'),
  ('HEALTH_CARE.DISCLOSURE', 'EVIDENCE'),
  ('HEALTH_CARE.DISCLOSURE', 'RISK'),
  ('HEALTH_CARE.DECISION', 'AUTHORITY'),
  ('HEALTH_CARE.DECISION', 'ACTION'),
  ('HEALTH_CARE.DECISION.LIMITS', 'AUTHORITY'),
  ('HEALTH_CARE.DECISION.ELDERS', 'ACTION'),
  ('HEALTH_CARE.DECISION.ELDERS', 'TRANSFER'),
  ('HEALTH_CARE.DECISION.ELDERS', 'RISK'),
  ('HEALTH_CARE.INSURANCE', 'EVIDENCE'),
  ('HEALTH_CARE.INSURANCE', 'RISK'),
  ('HEALTH_CARE.INSURANCE', 'TRANSFER'),
  ('HEALTH_CARE.MENTAL', 'RISK'),
  ('HEALTH_CARE.MENTAL', 'AUTHORITY'),
  ('CAREERS', 'ACTION'),
  ('CAREERS', 'AUTHORITY'),
  ('CAREERS', 'TRANSFER'),
  ('CAREERS.AMBITION', 'RISK'),
  ('CAREERS.SACRIFICE', 'ACTION'),
  ('CAREERS.SACRIFICE', 'TRANSFER'),
  ('CAREERS.SACRIFICE', 'RISK'),
  ('CAREERS.SACRIFICE.REENTRY', 'ACTION'),
  ('CAREERS.SACRIFICE.REENTRY', 'TRANSFER'),
  ('CAREERS.SACRIFICE.ENDING', 'RISK'),
  ('CAREERS.SACRIFICE.ENDING', 'TRANSFER'),
  ('CAREERS.HOURS', 'EVIDENCE'),
  ('CAREERS.HOURS', 'ACTION'),
  ('CAREERS.RISK', 'RISK'),
  ('CAREERS.RISK', 'AUTHORITY'),
  ('GEOGRAPHY', 'ACTION'),
  ('GEOGRAPHY', 'RISK'),
  ('GEOGRAPHY', 'AUTHORITY'),
  ('GEOGRAPHY.ROOTS', 'RISK'),
  ('GEOGRAPHY.ROOTS', 'TRANSFER'),
  ('GEOGRAPHY.SAFETY', 'RISK'),
  ('GEOGRAPHY.SAFETY', 'AUTHORITY'),
  ('GEOGRAPHY.STATUS', 'RISK'),
  ('GEOGRAPHY.STATUS', 'AUTHORITY'),
  ('GEOGRAPHY.STATUS', 'TRANSFER'),
  ('GEOGRAPHY.STATUS.DEPENDENCE', 'RISK'),
  ('GEOGRAPHY.STATUS.DEPENDENCE', 'AUTHORITY'),
  ('GEOGRAPHY.STATUS.DOCUMENTS', 'ACTION'),
  ('GEOGRAPHY.STATUS.DOCUMENTS', 'RISK'),
  ('GEOGRAPHY.STATUS.DOCUMENTS', 'AUTHORITY'),
  ('GEOGRAPHY.HOUSING', 'AUTHORITY'),
  ('GEOGRAPHY.HOUSING', 'TRANSFER'),
  ('GEOGRAPHY.HOUSING', 'RISK'),
  ('PRIVACY', 'ACTION'),
  ('PRIVACY', 'RISK'),
  ('PRIVACY', 'AUTHORITY'),
  ('PRIVACY.DEVICES', 'AUTHORITY'),
  ('PRIVACY.DEVICES', 'RISK'),
  ('PRIVACY.DEVICES.MONITORING', 'RISK'),
  ('PRIVACY.DEVICES.MONITORING', 'AUTHORITY'),
  ('PRIVACY.DEVICES.SHARED_RECORDS', 'EVIDENCE'),
  ('PRIVACY.DEVICES.SHARED_RECORDS', 'AUTHORITY'),
  ('PRIVACY.HISTORY', 'EVIDENCE'),
  ('PRIVACY.HISTORY', 'AUTHORITY'),
  ('PRIVACY.FRIENDSHIPS', 'RISK'),
  ('PRIVACY.FRIENDSHIPS', 'AUTHORITY'),
  ('PRIVACY.PUBLIC', 'ACTION'),
  ('PRIVACY.PUBLIC', 'AUTHORITY'),
  ('PRIVACY.PUBLIC', 'RISK'),
  ('TRUST', 'EVIDENCE'),
  ('TRUST', 'RISK'),
  ('TRUST', 'AUTHORITY'),
  ('TRUST.OUTSTANDING', 'EVIDENCE'),
  ('TRUST.THRESHOLD', 'RISK'),
  ('TRUST.THRESHOLD', 'AUTHORITY'),
  ('TRUST.THRESHOLD.SECRECY', 'EVIDENCE'),
  ('TRUST.THRESHOLD.SECRECY', 'AUTHORITY'),
  ('TRUST.THRESHOLD.DISCOVERY', 'ACTION'),
  ('TRUST.THRESHOLD.DISCOVERY', 'RISK'),
  ('TRUST.VERIFICATION', 'EVIDENCE'),
  ('TRUST.VERIFICATION', 'RISK'),
  ('TRUST.REPAIRED', 'EVIDENCE'),
  ('FUTURE_CHANGE', 'RISK'),
  ('FUTURE_CHANGE', 'AUTHORITY'),
  ('FUTURE_CHANGE.IDENTITY', 'RISK'),
  ('FUTURE_CHANGE.IDENTITY', 'AUTHORITY'),
  ('FUTURE_CHANGE.LOSS', 'ACTION'),
  ('FUTURE_CHANGE.LOSS', 'RISK'),
  ('FUTURE_CHANGE.LOSS.CAPACITY', 'ACTION'),
  ('FUTURE_CHANGE.LOSS.CAPACITY', 'RISK'),
  ('FUTURE_CHANGE.LOSS.CAPACITY', 'TRANSFER'),
  ('FUTURE_CHANGE.LOSS.GRIEF', 'ACTION'),
  ('FUTURE_CHANGE.REVIEW', 'ACTION'),
  ('FUTURE_CHANGE.REVIEW', 'AUTHORITY'),
  ('FUTURE_CHANGE.ESTATE', 'AUTHORITY'),
  ('FUTURE_CHANGE.ESTATE', 'TRANSFER'),
  ('DEAL_BREAKERS', 'RISK'),
  ('DEAL_BREAKERS', 'AUTHORITY'),
  ('DEAL_BREAKERS.STATED', 'RISK'),
  ('DEAL_BREAKERS.CONFLICT', 'EVIDENCE'),
  ('DEAL_BREAKERS.CONFLICT', 'RISK'),
  ('DEAL_BREAKERS.CONFLICT.HONESTY', 'EVIDENCE'),
  ('DEAL_BREAKERS.CONFLICT.HONESTY', 'RISK'),
  ('DEAL_BREAKERS.CONFLICT.DECISION', 'ACTION'),
  ('DEAL_BREAKERS.CONFLICT.DECISION', 'AUTHORITY'),
  ('DEAL_BREAKERS.SAFETY_FLOOR', 'RISK'),
  ('DEAL_BREAKERS.SAFETY_FLOOR', 'AUTHORITY'),
  ('DEAL_BREAKERS.REVIEW', 'AUTHORITY'),
  ('REPAIR', 'ACTION'),
  ('REPAIR', 'AUTHORITY'),
  ('REPAIR.SEQUENCE', 'ACTION'),
  ('REPAIR.SEQUENCE.SPECIFICS', 'ACTION'),
  ('REPAIR.SEQUENCE.SPECIFICS', 'EVIDENCE'),
  ('REPAIR.SEQUENCE.COST', 'ACTION'),
  ('REPAIR.SEQUENCE.COST', 'TRANSFER'),
  ('REPAIR.REFUSAL', 'RISK'),
  ('REPAIR.REFUSAL', 'AUTHORITY'),
  ('REPAIR.PATTERN', 'ACTION'),
  ('REPAIR.PATTERN', 'RISK'),
  ('REPAIR.UNREPAIRABLE', 'RISK'),
  ('REPAIR.UNREPAIRABLE', 'AUTHORITY')
on conflict do nothing;

-- 112 nodes across 16 clusters, 244 declared deltas.
