-- THYLORA · QYRIS · 0003 · Industry template
--
-- GENERATED FILE — DO NOT EDIT BY HAND.
-- Source of truth: qyris/lib/industry.js
-- Regenerate:     node db/qyris/generate-seed.mjs
-- Drift check:    node db/qyris/generate-seed.mjs --check  (run by npm test)
--
-- Idempotent: every insert is an upsert, so a second application is a no-op.


create table if not exists qyr_axes (
  axis_id   text primary key,
  label     text not null,
  invariant text not null
);

create table if not exists qyr_domains (
  domain_id text primary key,
  label     text not null
);

create table if not exists qyr_axis_deltas (
  axis_id    text not null references qyr_axes(axis_id) on delete cascade,
  delta_code text not null references qyr_deltas(delta_code),
  primary key (axis_id, delta_code)
);

-- Which fields the grammar produced mechanically and which a human had to
-- write. The AUTHORED rows are the honest finding about where a generic
-- projection would have been vague or unsafe.
create table if not exists qyr_projections (
  node_id    text primary key references qyr_nodes(node_id) on delete cascade,
  axis_id    text not null references qyr_axes(axis_id),
  domain_id  text not null references qyr_domains(domain_id),
  provenance jsonb not null,
  constraint qyr_projections_provenance_shape check (
    provenance ?& array['question','yield','reason','inspect','safeguard']
  )
);

insert into qyr_packs (pack_id, title, kind, notice) values
  ('QYRIS-INDUSTRY-001', 'QYRIS Industry Template', 'INDUSTRY', 'The same QYRIS grammar projected across six domains. Sixteen axes times six domains. Every QUESTION is authored per domain; YIELD, REASON and INSPECT are produced from the axis invariant plus the domain lexicon; SAFEGUARD is authored only where a generic one would be unsafe.')
on conflict (pack_id) do update set title = excluded.title, notice = excluded.notice;

insert into qyr_axes (axis_id, label, invariant) values
  ('MONEY', 'MONEY', 'What value exists, who holds it, and who may move it without asking.'),
  ('DEBT', 'DEBT', 'What obligation is already owed, to whom, and who it follows when things end.'),
  ('CHILDREN', 'CHILDREN', 'Who is dependent on this, who comes next, and what they are owed regardless of the outcome.'),
  ('FAMILY_BOUNDARIES', 'FAMILY BOUNDARIES', 'Who outside the core may decide, enter, know — and who says no to them.'),
  ('FAITH_WORLDVIEW', 'FAITH / WORLDVIEW', 'What creed governs practice here, whose ruling settles a dispute, and what happens if someone stops believing it.'),
  ('SEX_INTIMACY', 'CLOSENESS & POWER', 'Where closeness and power meet, and how a no is heard by the person with less of it.'),
  ('HOUSEHOLD_LABOR', 'UNSEEN LABOUR', 'The work that keeps this running that nobody credits, and who is carrying it.'),
  ('CONFLICT', 'CONFLICT', 'What happens under pressure, and what is never permitted no matter how justified it feels.'),
  ('HEALTH_CARE', 'CAPACITY & CARE', 'What happens when someone here cannot continue, and who decides for them.'),
  ('CAREERS', 'PATHS', 'Whose path moves first when both cannot be accommodated, and who decided that.'),
  ('GEOGRAPHY', 'PLACE', 'Where this happens, who is farther from home, and who is less safe in that place.'),
  ('PRIVACY', 'PRIVACY', 'What stays a person''s own here, and whether access granted can be withdrawn.'),
  ('TRUST', 'TRUST', 'What would end this, and what is already unresolved and unspoken.'),
  ('FUTURE_CHANGE', 'FUTURE CHANGE', 'What change would this survive, and when is it deliberately revisited.'),
  ('DEAL_BREAKERS', 'DEAL BREAKERS', 'The absolute limits, plus the floor that applies whether anyone named it or not.'),
  ('REPAIR', 'REPAIR', 'What actually repairs harm here, in actions, and what happens when the same harm recurs.')
on conflict (axis_id) do update set label = excluded.label, invariant = excluded.invariant;

insert into qyr_axis_deltas (axis_id, delta_code) values
  ('MONEY', 'EVIDENCE'),
  ('MONEY', 'AUTHORITY'),
  ('MONEY', 'TRANSFER'),
  ('DEBT', 'EVIDENCE'),
  ('DEBT', 'RISK'),
  ('DEBT', 'TRANSFER'),
  ('CHILDREN', 'AUTHORITY'),
  ('CHILDREN', 'RISK'),
  ('CHILDREN', 'TRANSFER'),
  ('FAMILY_BOUNDARIES', 'ACTION'),
  ('FAMILY_BOUNDARIES', 'AUTHORITY'),
  ('FAMILY_BOUNDARIES', 'RISK'),
  ('FAITH_WORLDVIEW', 'ACTION'),
  ('FAITH_WORLDVIEW', 'AUTHORITY'),
  ('FAITH_WORLDVIEW', 'RISK'),
  ('SEX_INTIMACY', 'RISK'),
  ('SEX_INTIMACY', 'AUTHORITY'),
  ('HOUSEHOLD_LABOR', 'ACTION'),
  ('HOUSEHOLD_LABOR', 'EVIDENCE'),
  ('HOUSEHOLD_LABOR', 'TRANSFER'),
  ('CONFLICT', 'ACTION'),
  ('CONFLICT', 'RISK'),
  ('CONFLICT', 'AUTHORITY'),
  ('HEALTH_CARE', 'AUTHORITY'),
  ('HEALTH_CARE', 'RISK'),
  ('HEALTH_CARE', 'ACTION'),
  ('CAREERS', 'ACTION'),
  ('CAREERS', 'AUTHORITY'),
  ('CAREERS', 'TRANSFER'),
  ('GEOGRAPHY', 'RISK'),
  ('GEOGRAPHY', 'AUTHORITY'),
  ('GEOGRAPHY', 'ACTION'),
  ('PRIVACY', 'AUTHORITY'),
  ('PRIVACY', 'RISK'),
  ('PRIVACY', 'EVIDENCE'),
  ('TRUST', 'EVIDENCE'),
  ('TRUST', 'RISK'),
  ('TRUST', 'AUTHORITY'),
  ('FUTURE_CHANGE', 'RISK'),
  ('FUTURE_CHANGE', 'AUTHORITY'),
  ('FUTURE_CHANGE', 'ACTION'),
  ('DEAL_BREAKERS', 'RISK'),
  ('DEAL_BREAKERS', 'AUTHORITY'),
  ('REPAIR', 'ACTION'),
  ('REPAIR', 'AUTHORITY'),
  ('REPAIR', 'RISK')
on conflict do nothing;

insert into qyr_domains (domain_id, label) values
  ('MUSIC', 'MUSIC'),
  ('COMEDY', 'COMEDY'),
  ('BUSINESS', 'BUSINESS'),
  ('RELIGION', 'RELIGION'),
  ('EDUCATION', 'EDUCATION'),
  ('FAMILY', 'FAMILY')
on conflict (domain_id) do update set label = excluded.label;

insert into qyr_nodes (node_id, pack_id, parent_id, cluster_id, label, depth, ordinal, question, yield, reason, inspect, safeguard) values
  ('MUSIC.MONEY', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · MONEY', 0, 0, 'What are the master, publishing, performance and sync splits on this record, in writing, signed by everyone in the room before release?', 'A written map of master, publishing, performance and sync income with a named holder and a named mover for each line.', 'In music, the money fight is almost always a fight about a number one party never saw.', 'Check the stated position against the split sheet, the session log and the registration. An impression is not a figure.', 'Disclosure is mutual. The uncredited contributor is not asked to disclose to someone who has disclosed nothing.'),
  ('MUSIC.DEBT', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · DEBT', 0, 1, 'What advance, studio cost, marketing spend or producer fee is recoupable against whose income, and at what point does anyone actually get paid?', 'An obligation schedule with a legal owner and an end condition per line.', 'Obligations that predate the arrangement do not end when the arrangement begins.', 'Read the instrument. A remembered obligation is an estimate; a signed one is evidence.', 'A disclosed obligation is a shared map, not a file kept on the uncredited contributor for later use.'),
  ('MUSIC.CHILDREN', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · CHILDREN', 0, 2, 'Who inherits and administers this catalogue, and who collects for a contributor who has died or become unreachable?', 'A named list of dependants with an obligation that survives the arrangement ending.', 'Dependants carry the cost of decisions they could not participate in.', 'Check the obligation is written where a dependant or their advocate could actually enforce it.', 'A dependant''s existing claim is never reduced to make a new arrangement work.'),
  ('MUSIC.FAMILY_BOUNDARIES', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · FAMILY BOUNDARIES', 0, 3, 'Who outside the credited contributors — managers, relatives, label staff, a partner — can hold up a release or take a cut, and who tells them no?', 'A boundary map naming what is decided inside and what is not.', 'Outside interference is rarely about the outsider; it is about who will hold a line with their own people.', 'Test against a real past incident. What happened is the boundary, whatever was intended.', 'Each party holds the line with their own people. Nobody is required to deliver another''s bad news.'),
  ('MUSIC.FAITH_WORLDVIEW', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · FAITH / WORLDVIEW', 0, 4, 'What is this record actually about, who decides when a song crosses a line, and what happens to an artist who changes their mind about it later?', 'A named governing authority and a stated consequence for dissent.', 'An unnamed governing belief defaults to whoever can invoke one, which is a power question in other clothes.', 'Look at what is scheduled and what is funded. Both record the operative creed more honestly than a statement.', 'Nobody is bound to an authority they did not personally accept, and accepting one does not surrender the right to leave.'),
  ('MUSIC.SEX_INTIMACY', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · CLOSENESS & POWER', 0, 5, 'Where do closeness and power overlap in this session, tour or writing room, and what happened the last time the person with the least leverage said no?', 'A concrete description of the aftermath of refusal, from both sides.', 'Coercion lives in the aftermath — the silence, the withdrawal, the lost opportunity — rather than in the moment.', 'Compare both accounts of the same past refusal. A gap between them is the finding.', 'If either account describes pressure, retaliation or fear, this stops being a process question and routes to support. No answer is recorded.'),
  ('MUSIC.HOUSEHOLD_LABOR', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · UNSEEN LABOUR', 0, 6, 'Who does the clearance, the metadata, the registration, the file management and the follow-up that nobody credits and nobody wants?', 'A task inventory with a named owner per line, including remembering and noticing.', 'Unwritten work is allocated by default to whoever notices it first, permanently.', 'Track a real week. Self-report and observation diverge substantially in both directions.', 'Naming an imbalance is information, not an accusation, and is not answered with a list of the other side''s contributions.'),
  ('MUSIC.CONFLICT', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · CONFLICT', 0, 7, 'When a credit or a split is disputed after release, who decides, on what record, and what is never done — pulling a track, withholding stems, going public first?', 'Described pressure patterns and a short list of unconditional prohibitions.', 'Arrangements do not fail because there is conflict. They fail because of what is permitted during it.', 'Describe the last three real disputes: who escalated, who went silent, how it ended.', 'Threats, retaliation and intimidation are on the prohibited list by default and are not negotiable items.'),
  ('MUSIC.HEALTH_CARE', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · CAPACITY & CARE', 0, 8, 'What happens to this project if the lead artist cannot work, and who is authorised to approve a release, a licence or a takedown in their place?', 'A named decision-holder for incapacity and a named practical continuity plan.', 'Continuity decisions get made by whoever is present, unless they were made earlier.', 'Confirm the named holder is documented where it would actually be honoured. Intention is not authority.', 'No health detail is stored here. Only the position, the named holder and the document''s existence.'),
  ('MUSIC.CAREERS', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · PATHS', 0, 9, 'When a tour, a session and a day job collide, whose commitment moves first, and was that rule set before the offer arrived?', 'A decision rule agreed before a specific opportunity is on the table.', 'Without a rule, the party with more leverage wins by default and the other path quietly becomes secondary.', 'Apply the rule to a real opportunity. An untested rule is a sentiment.', 'The rule is symmetrical and reviewable. Deferring once does not establish a permanent order.'),
  ('MUSIC.GEOGRAPHY', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · PLACE', 0, 10, 'Where is this recorded, mixed, released and toured — and who is farther from home, paying their own travel, or less safe in those venues?', 'A place decision with differential exposure named per person.', 'Two people in the same room can be in materially different countries.', 'Ask the more exposed party. The less exposed party''s assessment is not a measurement.', 'The more exposed party''s assessment governs and is not debated down by someone with a different experience of the same place.'),
  ('MUSIC.PRIVACY', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · PRIVACY', 0, 11, 'Who holds the session files, the stems, the unreleased material and the personal footage, and can a contributor withdraw their material or their likeness later?', 'A stated privacy line per domain with an explicit revocation right.', 'Access that cannot be revoked is not sharing; it is monitoring.', 'Check whether the uncredited contributor could withdraw access today without a confrontation. If not, that is the real rule.', 'Privacy is not evidence of wrongdoing. A request for it is never recorded as a finding.'),
  ('MUSIC.TRUST', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · TRUST', 0, 12, 'What would make each person here refuse to work with the others again, and what from the last project is still unsettled?', 'A named breach threshold per party and an inventory of open matters.', 'Arrangements are entered carrying unresolved matter everyone has agreed not to mention.', 'If the list of open matters is empty, ask each party separately. Empty lists are usually courteous.', 'A matter raised here is met once without retaliation, or the question should not have been asked.'),
  ('MUSIC.FUTURE_CHANGE', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · FUTURE CHANGE', 0, 13, 'If this record succeeds beyond anyone''s expectation, or if a contributor becomes someone the others will not stand beside, what happens to the splits and the credits?', 'A named set of foreseeable changes, a response to each, and a review date in a calendar.', 'Agreements without a review date are enforced against people who have since changed.', 'Test five concrete changes rather than a general willingness to adapt.', 'Any party may call a review early without justifying why.'),
  ('MUSIC.DEAL_BREAKERS', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · DEAL BREAKERS', 0, 14, 'What use of this music would each person refuse outright — a campaign, a brand, a film, a political ad — and who can veto it after release?', 'Short unsoftened limit lists, plus a stated floor nobody can remove by agreement.', 'A limit that is never stated is discovered only by being crossed.', 'Check each item is genuinely absolute. Anything with a condition belongs in another axis.', 'Coercion, retaliation, harm to dependants, and control of another''s money, documents or care are on the floor and are not removable by agreement.'),
  ('MUSIC.REPAIR', 'QYRIS-INDUSTRY-001', null, 'MUSIC', 'MUSIC · REPAIR', 0, 15, 'When a credit was wrong or a payment did not arrive, what actually fixed it — a corrected registration and a back-payment, or an apology?', 'A repair sequence that can be followed while upset, and a named escalation for repetition.', 'Arrangements survive on repair capacity far more than on initial compatibility.', 'Check the sequence includes a behaviour change, not only an acknowledgement. Count repeats; four is a number, not a mood.', 'Repair is not the harmed party''s job, and non-acceptance of a repair is not punished.'),
  ('COMEDY.MONEY', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · MONEY', 0, 0, 'What does each person on this bill actually get paid — door, guarantee, taping fee, back-end — and who saw the settlement?', 'A written map of material, credits, taping fees, back-end and stage time with a named holder and a named mover for each line.', 'In comedy, the money fight is almost always a fight about a number one party never saw.', 'Check the stated position against the set list, the tape, the writers'' room credit and the booking. An impression is not a figure.', 'Disclosure is mutual. The opener or the staff writer is not asked to disclose to someone who has disclosed nothing.'),
  ('COMEDY.DEBT', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · DEBT', 0, 1, 'What development work, road costs and favours are already owed here, and what is a writer or opener expected to eat before anything is paid?', 'An obligation schedule with a legal owner and an end condition per line.', 'Obligations that predate the arrangement do not end when the arrangement begins.', 'Read the instrument. A remembered obligation is an estimate; a signed one is evidence.', 'A disclosed obligation is a shared map, not a file kept on the opener or the staff writer for later use.'),
  ('COMEDY.CHILDREN', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · CHILDREN', 0, 2, 'Who is coming up under this room, what are they promised, and does any of it survive the person who promised it leaving?', 'A named list of dependants with an obligation that survives the arrangement ending.', 'Dependants carry the cost of decisions they could not participate in.', 'Check the obligation is written where a dependant or their advocate could actually enforce it.', 'A dependant''s existing claim is never reduced to make a new arrangement work.'),
  ('COMEDY.FAMILY_BOUNDARIES', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · FAMILY BOUNDARIES', 0, 3, 'Who outside the credited writers — a manager, a network note, a headliner''s friend — can rewrite, cut or take credit, and who says no to them?', 'A boundary map naming what is decided inside and what is not.', 'Outside interference is rarely about the outsider; it is about who will hold a line with their own people.', 'Test against a real past incident. What happened is the boundary, whatever was intended.', 'Each party holds the line with their own people. Nobody is required to deliver another''s bad news.'),
  ('COMEDY.FAITH_WORLDVIEW', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · FAITH / WORLDVIEW', 0, 4, 'What does this room believe is fair game, who rules when a bit crosses a line, and what happens to a comic who stops agreeing?', 'A named governing authority and a stated consequence for dissent.', 'An unnamed governing belief defaults to whoever can invoke one, which is a power question in other clothes.', 'Look at what is scheduled and what is funded. Both record the operative creed more honestly than a statement.', 'Nobody is bound to an authority they did not personally accept, and accepting one does not surrender the right to leave.'),
  ('COMEDY.SEX_INTIMACY', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · CLOSENESS & POWER', 0, 5, 'Where do closeness and power overlap on this bill or in this room, and what happened after the person with the least leverage last said no to a late invitation?', 'A concrete description of the aftermath of refusal, from both sides.', 'Coercion lives in the aftermath — the silence, the withdrawal, the lost opportunity — rather than in the moment.', 'Compare both accounts of the same past refusal. A gap between them is the finding.', 'If either account describes pressure, retaliation or fear, this stops being a process question and routes to support. No answer is recorded.'),
  ('COMEDY.HOUSEHOLD_LABOR', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · UNSEEN LABOUR', 0, 6, 'Who books, drives, handles the room, cuts the tape and follows up on payment — and is that person also on the bill?', 'A task inventory with a named owner per line, including remembering and noticing.', 'Unwritten work is allocated by default to whoever notices it first, permanently.', 'Track a real week. Self-report and observation diverge substantially in both directions.', 'Naming an imbalance is information, not an accusation, and is not answered with a list of the other side''s contributions.'),
  ('COMEDY.CONFLICT', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · CONFLICT', 0, 7, 'When a joke is claimed by two people, who decides, on what record, and what is never done — burning someone publicly, blacklisting, going to the club first?', 'Described pressure patterns and a short list of unconditional prohibitions.', 'Arrangements do not fail because there is conflict. They fail because of what is permitted during it.', 'Describe the last three real disputes: who escalated, who went silent, how it ended.', 'Threats, retaliation and intimidation are on the prohibited list by default and are not negotiable items.'),
  ('COMEDY.HEALTH_CARE', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · CAPACITY & CARE', 0, 8, 'What happens to this tour or taping when someone cannot go on, and who is authorised to cancel without it ending their standing in the room?', 'A named decision-holder for incapacity and a named practical continuity plan.', 'Continuity decisions get made by whoever is present, unless they were made earlier.', 'Confirm the named holder is documented where it would actually be honoured. Intention is not authority.', 'No health detail is stored here. Only the position, the named holder and the document''s existence.'),
  ('COMEDY.CAREERS', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · PATHS', 0, 9, 'When a spot, a taping and a paying date collide, whose commitment moves first, and who told the other they had to give it up?', 'A decision rule agreed before a specific opportunity is on the table.', 'Without a rule, the party with more leverage wins by default and the other path quietly becomes secondary.', 'Apply the rule to a real opportunity. An untested rule is a sentiment.', 'The rule is symmetrical and reviewable. Deferring once does not establish a permanent order.'),
  ('COMEDY.GEOGRAPHY', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · PLACE', 0, 10, 'Which rooms and cities is each comic on this bill actually safe in, who is travelling farthest on their own money, and who gets the hotel?', 'A place decision with differential exposure named per person.', 'Two people in the same room can be in materially different countries.', 'Ask the more exposed party. The less exposed party''s assessment is not a measurement.', 'The more exposed party''s assessment governs and is not debated down by someone with a different experience of the same place.'),
  ('COMEDY.PRIVACY', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · PRIVACY', 0, 11, 'Who owns the tape of a set that was not meant to be recorded, who can post it, and can a comic have it taken down?', 'A stated privacy line per domain with an explicit revocation right.', 'Access that cannot be revoked is not sharing; it is monitoring.', 'Check whether the opener or the staff writer could withdraw access today without a confrontation. If not, that is the real rule.', 'Privacy is not evidence of wrongdoing. A request for it is never recorded as a finding.'),
  ('COMEDY.TRUST', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · TRUST', 0, 12, 'What would make each person here never work this room again, and what from the last taping has still not been settled?', 'A named breach threshold per party and an inventory of open matters.', 'Arrangements are entered carrying unresolved matter everyone has agreed not to mention.', 'If the list of open matters is empty, ask each party separately. Empty lists are usually courteous.', 'A matter raised here is met once without retaliation, or the question should not have been asked.'),
  ('COMEDY.FUTURE_CHANGE', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · FUTURE CHANGE', 0, 13, 'If a bit from this room becomes the special, or if a comic here becomes someone the others will not share a bill with, what happens to the credit and the money?', 'A named set of foreseeable changes, a response to each, and a review date in a calendar.', 'Agreements without a review date are enforced against people who have since changed.', 'Test five concrete changes rather than a general willingness to adapt.', 'Any party may call a review early without justifying why.'),
  ('COMEDY.DEAL_BREAKERS', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · DEAL BREAKERS', 0, 14, 'What material, booking or brand association would each person here refuse outright, and can they refuse without losing their spot?', 'Short unsoftened limit lists, plus a stated floor nobody can remove by agreement.', 'A limit that is never stated is discovered only by being crossed.', 'Check each item is genuinely absolute. Anything with a condition belongs in another axis.', 'Coercion, retaliation, harm to dependants, and control of another''s money, documents or care are on the floor and are not removable by agreement.'),
  ('COMEDY.REPAIR', 'QYRIS-INDUSTRY-001', null, 'COMEDY', 'COMEDY · REPAIR', 0, 15, 'When credit was taken or a payment was short, what actually fixed it — a corrected credit and the money, or a drink after the show?', 'A repair sequence that can be followed while upset, and a named escalation for repetition.', 'Arrangements survive on repair capacity far more than on initial compatibility.', 'Check the sequence includes a behaviour change, not only an acknowledgement. Count repeats; four is a number, not a mood.', 'Repair is not the harmed party''s job, and non-acceptance of a repair is not punished.'),
  ('BUSINESS.MONEY', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · MONEY', 0, 0, 'What is the actual cap table, what is in the bank, what is committed, and who can move money without a second signature?', 'A written map of equity, revenue, payroll and reserves with a named holder and a named mover for each line.', 'In business, the money fight is almost always a fight about a number one party never saw.', 'Check the stated position against the cap table, the operating agreement and the books. An impression is not a figure.', 'Disclosure is mutual. The early employee without documented equity is not asked to disclose to someone who has disclosed nothing.'),
  ('BUSINESS.DEBT', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · DEBT', 0, 1, 'What is already owed — loans, deferred salary, unpaid invoices, personal guarantees — and which of it follows a founder personally after shutdown?', 'An obligation schedule with a legal owner and an end condition per line.', 'Obligations that predate the arrangement do not end when the arrangement begins.', 'Read the instrument. A remembered obligation is an estimate; a signed one is evidence.', 'A disclosed obligation is a shared map, not a file kept on the early employee without documented equity for later use.'),
  ('BUSINESS.CHILDREN', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · CHILDREN', 0, 2, 'Who are the employees and customers who depend on this continuing, and what do they get if it stops next quarter?', 'A named list of dependants with an obligation that survives the arrangement ending.', 'Dependants carry the cost of decisions they could not participate in.', 'Check the obligation is written where a dependant or their advocate could actually enforce it.', 'A dependant''s existing claim is never reduced to make a new arrangement work.'),
  ('BUSINESS.FAMILY_BOUNDARIES', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · FAMILY BOUNDARIES', 0, 3, 'Who outside the operating team — an investor, a relative, a former founder — can override a decision, and who tells them no?', 'A boundary map naming what is decided inside and what is not.', 'Outside interference is rarely about the outsider; it is about who will hold a line with their own people.', 'Test against a real past incident. What happened is the boundary, whatever was intended.', 'Each party holds the line with their own people. Nobody is required to deliver another''s bad news.'),
  ('BUSINESS.FAITH_WORLDVIEW', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · FAITH / WORLDVIEW', 0, 4, 'What does this company actually believe it is for, who rules when profit and that purpose conflict, and what happens to someone who stops believing it?', 'A named governing authority and a stated consequence for dissent.', 'An unnamed governing belief defaults to whoever can invoke one, which is a power question in other clothes.', 'Look at what is scheduled and what is funded. Both record the operative creed more honestly than a statement.', 'Nobody is bound to an authority they did not personally accept, and accepting one does not surrender the right to leave.'),
  ('BUSINESS.SEX_INTIMACY', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · CLOSENESS & POWER', 0, 5, 'Where do closeness and power overlap here — reporting lines, founders who are partners, a manager and a direct report — and what happens after the person with less power says no?', 'A concrete description of the aftermath of refusal, from both sides.', 'Coercion lives in the aftermath — the silence, the withdrawal, the lost opportunity — rather than in the moment.', 'Compare both accounts of the same past refusal. A gap between them is the finding.', 'If either account describes pressure, retaliation or fear, this stops being a process question and routes to support. No answer is recorded.'),
  ('BUSINESS.HOUSEHOLD_LABOR', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · UNSEEN LABOUR', 0, 6, 'Who does the support tickets, the compliance, the bookkeeping, the onboarding and the remembering — and is that work in anyone''s title or comp?', 'A task inventory with a named owner per line, including remembering and noticing.', 'Unwritten work is allocated by default to whoever notices it first, permanently.', 'Track a real week. Self-report and observation diverge substantially in both directions.', 'Naming an imbalance is information, not an accusation, and is not answered with a list of the other side''s contributions.'),
  ('BUSINESS.CONFLICT', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · CONFLICT', 0, 7, 'When founders deadlock, who breaks the tie, by what document, and what is never done — locking someone out, withholding payroll, going to customers first?', 'Described pressure patterns and a short list of unconditional prohibitions.', 'Arrangements do not fail because there is conflict. They fail because of what is permitted during it.', 'Describe the last three real disputes: who escalated, who went silent, how it ended.', 'Threats, retaliation and intimidation are on the prohibited list by default and are not negotiable items.'),
  ('BUSINESS.HEALTH_CARE', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · CAPACITY & CARE', 0, 8, 'What happens to this company when a key person cannot work for three months, and who is authorised to sign, pay and decide in their place?', 'A named decision-holder for incapacity and a named practical continuity plan.', 'Continuity decisions get made by whoever is present, unless they were made earlier.', 'Confirm the named holder is documented where it would actually be honoured. Intention is not authority.', 'No health detail is stored here. Only the position, the named holder and the document''s existence.'),
  ('BUSINESS.CAREERS', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · PATHS', 0, 9, 'When two founders want the same role, or one wants out, whose path moves first and what does the other receive?', 'A decision rule agreed before a specific opportunity is on the table.', 'Without a rule, the party with more leverage wins by default and the other path quietly becomes secondary.', 'Apply the rule to a real opportunity. An untested rule is a sentiment.', 'The rule is symmetrical and reviewable. Deferring once does not establish a permanent order.'),
  ('BUSINESS.GEOGRAPHY', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · PLACE', 0, 10, 'Where is this incorporated, where do people actually work, and does anyone''s visa, safety or tax position depend on that answer?', 'A place decision with differential exposure named per person.', 'Two people in the same room can be in materially different countries.', 'Ask the more exposed party. The less exposed party''s assessment is not a measurement.', 'The more exposed party''s assessment governs and is not debated down by someone with a different experience of the same place.'),
  ('BUSINESS.PRIVACY', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · PRIVACY', 0, 11, 'What employee, customer and founder data is held, who can read it, and what happens to it at shutdown or acquisition?', 'A stated privacy line per domain with an explicit revocation right.', 'Access that cannot be revoked is not sharing; it is monitoring.', 'Check whether the early employee without documented equity could withdraw access today without a confrontation. If not, that is the real rule.', 'Privacy is not evidence of wrongdoing. A request for it is never recorded as a finding.'),
  ('BUSINESS.TRUST', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · TRUST', 0, 12, 'What would make each founder walk, and what is currently unsaid between them that everyone has agreed not to raise?', 'A named breach threshold per party and an inventory of open matters.', 'Arrangements are entered carrying unresolved matter everyone has agreed not to mention.', 'If the list of open matters is empty, ask each party separately. Empty lists are usually courteous.', 'A matter raised here is met once without retaliation, or the question should not have been asked.'),
  ('BUSINESS.FUTURE_CHANGE', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · FUTURE CHANGE', 0, 13, 'If this is acquired, if a founder leaves, or if the market disappears, what happens to equity, to employees and to the promises already made?', 'A named set of foreseeable changes, a response to each, and a review date in a calendar.', 'Agreements without a review date are enforced against people who have since changed.', 'Test five concrete changes rather than a general willingness to adapt.', 'Any party may call a review early without justifying why.'),
  ('BUSINESS.DEAL_BREAKERS', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · DEAL BREAKERS', 0, 14, 'What customer, investor, contract or practice would each founder refuse outright, and can one of them veto it alone?', 'Short unsoftened limit lists, plus a stated floor nobody can remove by agreement.', 'A limit that is never stated is discovered only by being crossed.', 'Check each item is genuinely absolute. Anything with a condition belongs in another axis.', 'Coercion, retaliation, harm to dependants, and control of another''s money, documents or care are on the floor and are not removable by agreement.'),
  ('BUSINESS.REPAIR', 'QYRIS-INDUSTRY-001', null, 'BUSINESS', 'BUSINESS · REPAIR', 0, 15, 'When payroll was late or equity was promised and never papered, what actually fixed it — an executed document and the money, or a conversation?', 'A repair sequence that can be followed while upset, and a named escalation for repetition.', 'Arrangements survive on repair capacity far more than on initial compatibility.', 'Check the sequence includes a behaviour change, not only an acknowledgement. Count repeats; four is a number, not a mood.', 'Repair is not the harmed party''s job, and non-acceptance of a repair is not punished.'),
  ('RELIGION.MONEY', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · MONEY', 0, 0, 'What is given, where does it go, who sees the accounts, and can an ordinary member read them without asking permission?', 'A written map of tithes, offerings, property and trust with a named holder and a named mover for each line.', 'In religion, the money fight is almost always a fight about a number one party never saw.', 'Check the stated position against the minutes, the accounts and the membership roll. An impression is not a figure.', 'Disclosure is mutual. The member with no standing to ask is not asked to disclose to someone who has disclosed nothing.'),
  ('RELIGION.DEBT', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · DEBT', 0, 1, 'What does this body owe — building loans, personal guarantees by members, obligations to a parent organisation — and who carries it if the congregation dissolves?', 'An obligation schedule with a legal owner and an end condition per line.', 'Obligations that predate the arrangement do not end when the arrangement begins.', 'Read the instrument. A remembered obligation is an estimate; a signed one is evidence.', 'A disclosed obligation is a shared map, not a file kept on the member with no standing to ask for later use.'),
  ('RELIGION.CHILDREN', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · CHILDREN', 0, 2, 'What happens to children here — who is alone with them, who checked, what is taught, and at what age is a child''s own position honoured?', 'A named list of dependants with an obligation that survives the arrangement ending.', 'Dependants carry the cost of decisions they could not participate in.', 'Check the obligation is written where a dependant or their advocate could actually enforce it.', 'A child''s safety is never a matter of internal discretion. Any disclosure of harm routes outside this body to the relevant statutory authority, and this system records no detail about any child.'),
  ('RELIGION.FAMILY_BOUNDARIES', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · FAMILY BOUNDARIES', 0, 3, 'What may leadership decide inside a member''s household — marriage, discipline, schooling, money, medical care — and who tells them that is not theirs?', 'A boundary map naming what is decided inside and what is not.', 'Outside interference is rarely about the outsider; it is about who will hold a line with their own people.', 'Test against a real past incident. What happened is the boundary, whatever was intended.', 'Each party holds the line with their own people. Nobody is required to deliver another''s bad news.'),
  ('RELIGION.FAITH_WORLDVIEW', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · FAITH / WORLDVIEW', 0, 4, 'Who rules when doctrine is disputed, how is that ruling changed, and what happens socially and materially to a member who stops believing?', 'A named governing authority and a stated consequence for dissent.', 'An unnamed governing belief defaults to whoever can invoke one, which is a power question in other clothes.', 'Look at what is scheduled and what is funded. Both record the operative creed more honestly than a statement.', 'Nobody is bound to an authority they did not personally accept, and accepting one does not surrender the right to leave.'),
  ('RELIGION.SEX_INTIMACY', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · CLOSENESS & POWER', 0, 5, 'Where do spiritual authority and personal closeness overlap here, and what happened the last time someone with less standing said no to someone with more?', 'A concrete description of the aftermath of refusal, from both sides.', 'Coercion lives in the aftermath — the silence, the withdrawal, the lost opportunity — rather than in the moment.', 'Compare both accounts of the same past refusal. A gap between them is the finding.', 'If either account describes pressure, retaliation or fear, this stops being a process question and routes to support. No answer is recorded.'),
  ('RELIGION.HOUSEHOLD_LABOR', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · UNSEEN LABOUR', 0, 6, 'Who does the cleaning, the childcare, the cooking, the visiting and the setup — and is that the same group of women every week, unpaid and uncounted?', 'A task inventory with a named owner per line, including remembering and noticing.', 'Unwritten work is allocated by default to whoever notices it first, permanently.', 'Track a real week. Self-report and observation diverge substantially in both directions.', 'Naming an imbalance is information, not an accusation, and is not answered with a list of the other side''s contributions.'),
  ('RELIGION.CONFLICT', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · CONFLICT', 0, 7, 'When a member disputes leadership, who hears it, is it heard by anyone independent, and what is never done — shunning, disclosure of a confession, withholding a child''s access?', 'Described pressure patterns and a short list of unconditional prohibitions.', 'Arrangements do not fail because there is conflict. They fail because of what is permitted during it.', 'Describe the last three real disputes: who escalated, who went silent, how it ended.', 'Threats, retaliation and intimidation are on the prohibited list by default and are not negotiable items.'),
  ('RELIGION.HEALTH_CARE', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · CAPACITY & CARE', 0, 8, 'What does this body teach about medical care, and has anyone been discouraged from treatment, medication or a clinician?', 'A named decision-holder for incapacity and a named practical continuity plan.', 'Continuity decisions get made by whoever is present, unless they were made earlier.', 'Confirm the named holder is documented where it would actually be honoured. Intention is not authority.', 'No health detail is stored here. Only the position, the named holder and the document''s existence.'),
  ('RELIGION.CAREERS', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · PATHS', 0, 9, 'Who is paid here, who is expected to serve for free, and how does someone move from unpaid service to a paid role — or say no without losing standing?', 'A decision rule agreed before a specific opportunity is on the table.', 'Without a rule, the party with more leverage wins by default and the other path quietly becomes secondary.', 'Apply the rule to a real opportunity. An untested rule is a sentiment.', 'The rule is symmetrical and reviewable. Deferring once does not establish a permanent order.'),
  ('RELIGION.GEOGRAPHY', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · PLACE', 0, 10, 'Where does this body meet and gather, who has to travel farthest or cannot reach it, and is anyone less safe in that place or that neighbourhood?', 'A place decision with differential exposure named per person.', 'Two people in the same room can be in materially different countries.', 'Ask the more exposed party. The less exposed party''s assessment is not a measurement.', 'The more exposed party''s assessment governs and is not debated down by someone with a different experience of the same place.'),
  ('RELIGION.PRIVACY', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · PRIVACY', 0, 11, 'What is recorded about members — confessions, giving records, counselling notes, attendance — who can read it, and can a member have it deleted on leaving?', 'A stated privacy line per domain with an explicit revocation right.', 'Access that cannot be revoked is not sharing; it is monitoring.', 'Check whether the member with no standing to ask could withdraw access today without a confrontation. If not, that is the real rule.', 'Confession, counselling and giving records are the member''s own. Using them to discipline, expose or retain a member is named here as a breach, not a governance style.'),
  ('RELIGION.TRUST', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · TRUST', 0, 12, 'What would make a member leave, what would make leadership remove a member, and what is currently unresolved that nobody will raise from the floor?', 'A named breach threshold per party and an inventory of open matters.', 'Arrangements are entered carrying unresolved matter everyone has agreed not to mention.', 'If the list of open matters is empty, ask each party separately. Empty lists are usually courteous.', 'A matter raised here is met once without retaliation, or the question should not have been asked.'),
  ('RELIGION.FUTURE_CHANGE', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · FUTURE CHANGE', 0, 13, 'If leadership changes, if doctrine changes, or if the building is sold, what happens to the members, the money and the promises made to them?', 'A named set of foreseeable changes, a response to each, and a review date in a calendar.', 'Agreements without a review date are enforced against people who have since changed.', 'Test five concrete changes rather than a general willingness to adapt.', 'Any party may call a review early without justifying why.'),
  ('RELIGION.DEAL_BREAKERS', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · DEAL BREAKERS', 0, 14, 'What would this body never do to a member, stated as an unconditional floor rather than as a matter of leadership discretion?', 'Short unsoftened limit lists, plus a stated floor nobody can remove by agreement.', 'A limit that is never stated is discovered only by being crossed.', 'Check each item is genuinely absolute. Anything with a condition belongs in another axis.', 'Coercion, retaliation, harm to dependants, and control of another''s money, documents or care are on the floor and are not removable by agreement.'),
  ('RELIGION.REPAIR', 'QYRIS-INDUSTRY-001', null, 'RELIGION', 'RELIGION · REPAIR', 0, 15, 'When this body has harmed someone, what actually repaired it — restitution, independent review and a change in practice, or a public apology and a move on?', 'A repair sequence that can be followed while upset, and a named escalation for repetition.', 'Arrangements survive on repair capacity far more than on initial compatibility.', 'Check the sequence includes a behaviour change, not only an acknowledgement. Count repeats; four is a number, not a mood.', 'Repair is not the harmed party''s job, and non-acceptance of a repair is not punished.'),
  ('EDUCATION.MONEY', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · MONEY', 0, 0, 'What does this actually cost a family across the whole programme — tuition, materials, trips, technology, uniform — and what is the real total before anyone enrols?', 'A written map of tuition, funding, time and the credential with a named holder and a named mover for each line.', 'In education, the money fight is almost always a fight about a number one party never saw.', 'Check the stated position against the syllabus, the grade record and the support plan. An impression is not a figure.', 'Disclosure is mutual. The student who cannot advocate for themselves is not asked to disclose to someone who has disclosed nothing.'),
  ('EDUCATION.DEBT', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · DEBT', 0, 1, 'What debt does a student or family take on for this credential, what is the realistic income after it, and who told them that number?', 'An obligation schedule with a legal owner and an end condition per line.', 'Obligations that predate the arrangement do not end when the arrangement begins.', 'Read the instrument. A remembered obligation is an estimate; a signed one is evidence.', 'A disclosed obligation is a shared map, not a file kept on the student who cannot advocate for themselves for later use.'),
  ('EDUCATION.CHILDREN', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · CHILDREN', 0, 2, 'What does this institution owe a student who is struggling, and does that obligation survive the student becoming inconvenient to its results?', 'A named list of dependants with an obligation that survives the arrangement ending.', 'Dependants carry the cost of decisions they could not participate in.', 'Check the obligation is written where a dependant or their advocate could actually enforce it.', 'A child''s safety and a child''s support entitlement are not internal discretion. Concerns route to the statutory authority, and this system records no detail about any child.'),
  ('EDUCATION.FAMILY_BOUNDARIES', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · FAMILY BOUNDARIES', 0, 3, 'What may the institution decide about a child without the family, what may the family decide without the child, and where is the line written?', 'A boundary map naming what is decided inside and what is not.', 'Outside interference is rarely about the outsider; it is about who will hold a line with their own people.', 'Test against a real past incident. What happened is the boundary, whatever was intended.', 'Each party holds the line with their own people. Nobody is required to deliver another''s bad news.'),
  ('EDUCATION.FAITH_WORLDVIEW', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · FAITH / WORLDVIEW', 0, 4, 'What worldview is being taught as neutral here, who decides the curriculum, and what happens to a student or teacher who contests it?', 'A named governing authority and a stated consequence for dissent.', 'An unnamed governing belief defaults to whoever can invoke one, which is a power question in other clothes.', 'Look at what is scheduled and what is funded. Both record the operative creed more honestly than a statement.', 'Nobody is bound to an authority they did not personally accept, and accepting one does not surrender the right to leave.'),
  ('EDUCATION.SEX_INTIMACY', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · CLOSENESS & POWER', 0, 5, 'Where do closeness and power overlap between staff and students here, what is the rule on contact outside class, and what happened the last time a student raised a concern?', 'A concrete description of the aftermath of refusal, from both sides.', 'Coercion lives in the aftermath — the silence, the withdrawal, the lost opportunity — rather than in the moment.', 'Compare both accounts of the same past refusal. A gap between them is the finding.', 'Between staff and students there is no symmetry to examine. This axis asks about the rule and the reporting route only, and any disclosure routes outside the institution.'),
  ('EDUCATION.HOUSEHOLD_LABOR', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · UNSEEN LABOUR', 0, 6, 'Who does the marking, the planning, the parent contact, the emotional work and the covering — and is any of it inside the paid hours?', 'A task inventory with a named owner per line, including remembering and noticing.', 'Unwritten work is allocated by default to whoever notices it first, permanently.', 'Track a real week. Self-report and observation diverge substantially in both directions.', 'Naming an imbalance is information, not an accusation, and is not answered with a list of the other side''s contributions.'),
  ('EDUCATION.CONFLICT', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · CONFLICT', 0, 7, 'When a family disputes a grade, an exclusion or a support decision, who hears it, is there anyone independent, and what is never done to the student in the meantime?', 'Described pressure patterns and a short list of unconditional prohibitions.', 'Arrangements do not fail because there is conflict. They fail because of what is permitted during it.', 'Describe the last three real disputes: who escalated, who went silent, how it ended.', 'Threats, retaliation and intimidation are on the prohibited list by default and are not negotiable items.'),
  ('EDUCATION.HEALTH_CARE', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · CAPACITY & CARE', 0, 8, 'What happens when a student''s health, disability or crisis affects their work, and who decides on accommodations — the clinician, the institution, or whoever is cheapest?', 'A named decision-holder for incapacity and a named practical continuity plan.', 'Continuity decisions get made by whoever is present, unless they were made earlier.', 'Confirm the named holder is documented where it would actually be honoured. Intention is not authority.', 'No health detail is stored here. Only the position, the named holder and the document''s existence.'),
  ('EDUCATION.CAREERS', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · PATHS', 0, 9, 'Whose progression is prioritised when a teacher''s workload and a student''s needs collide, and who set that rule?', 'A decision rule agreed before a specific opportunity is on the table.', 'Without a rule, the party with more leverage wins by default and the other path quietly becomes secondary.', 'Apply the rule to a real opportunity. An untested rule is a sentiment.', 'The rule is symmetrical and reviewable. Deferring once does not establish a permanent order.'),
  ('EDUCATION.GEOGRAPHY', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · PLACE', 0, 10, 'Where is this taught, how does each student get there, and is any student less safe on that journey or in that building than the others?', 'A place decision with differential exposure named per person.', 'Two people in the same room can be in materially different countries.', 'Ask the more exposed party. The less exposed party''s assessment is not a measurement.', 'The more exposed party''s assessment governs and is not debated down by someone with a different experience of the same place.'),
  ('EDUCATION.PRIVACY', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · PRIVACY', 0, 11, 'What is recorded about each student — behaviour, diagnosis, family circumstance — who can read it, how long does it follow them, and can it be corrected?', 'A stated privacy line per domain with an explicit revocation right.', 'Access that cannot be revoked is not sharing; it is monitoring.', 'Check whether the student who cannot advocate for themselves could withdraw access today without a confrontation. If not, that is the real rule.', 'A behaviour or diagnosis record that follows a child for years is named here as a lasting transfer of risk to that child, and correction rights are checked as a matter of course.'),
  ('EDUCATION.TRUST', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · TRUST', 0, 12, 'What would make a family withdraw a student, what would make a teacher leave, and what is currently unresolved that nobody will say in a meeting?', 'A named breach threshold per party and an inventory of open matters.', 'Arrangements are entered carrying unresolved matter everyone has agreed not to mention.', 'If the list of open matters is empty, ask each party separately. Empty lists are usually courteous.', 'A matter raised here is met once without retaliation, or the question should not have been asked.'),
  ('EDUCATION.FUTURE_CHANGE', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · FUTURE CHANGE', 0, 13, 'If funding is cut, leadership changes, or this student''s needs change, what happens to the support that was promised in writing?', 'A named set of foreseeable changes, a response to each, and a review date in a calendar.', 'Agreements without a review date are enforced against people who have since changed.', 'Test five concrete changes rather than a general willingness to adapt.', 'Any party may call a review early without justifying why.'),
  ('EDUCATION.DEAL_BREAKERS', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · DEAL BREAKERS', 0, 14, 'What would this institution never do to a student, stated as an unconditional floor rather than as policy that can be revised quietly?', 'Short unsoftened limit lists, plus a stated floor nobody can remove by agreement.', 'A limit that is never stated is discovered only by being crossed.', 'Check each item is genuinely absolute. Anything with a condition belongs in another axis.', 'Coercion, retaliation, harm to dependants, and control of another''s money, documents or care are on the floor and are not removable by agreement.'),
  ('EDUCATION.REPAIR', 'QYRIS-INDUSTRY-001', null, 'EDUCATION', 'EDUCATION · REPAIR', 0, 15, 'When a student was failed here, what actually repaired it — a changed placement, restored time, an independent review — or a letter?', 'A repair sequence that can be followed while upset, and a named escalation for repetition.', 'Arrangements survive on repair capacity far more than on initial compatibility.', 'Check the sequence includes a behaviour change, not only an acknowledgement. Count repeats; four is a number, not a mood.', 'Repair is not the harmed party''s job, and non-acceptance of a repair is not punished.'),
  ('FAMILY.MONEY', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · MONEY', 0, 0, 'What does this household hold, who can move it, and does every adult here know the actual figures rather than an impression?', 'A written map of household money, property and inheritance with a named holder and a named mover for each line.', 'In family, the money fight is almost always a fight about a number one party never saw.', 'Check the stated position against the will, the deed, the accounts and the family ledger. An impression is not a figure.', 'Disclosure is mutual. The dependant and the unpaid caregiver is not asked to disclose to someone who has disclosed nothing.'),
  ('FAMILY.DEBT', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · DEBT', 0, 1, 'What does this household owe, whose name is on each obligation, and who is pursued for it if the household separates?', 'An obligation schedule with a legal owner and an end condition per line.', 'Obligations that predate the arrangement do not end when the arrangement begins.', 'Read the instrument. A remembered obligation is an estimate; a signed one is evidence.', 'A disclosed obligation is a shared map, not a file kept on the dependant and the unpaid caregiver for later use.'),
  ('FAMILY.CHILDREN', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · CHILDREN', 0, 2, 'What do the children and dependants here get regardless of what happens between the adults, and is it written where it could be enforced?', 'A named list of dependants with an obligation that survives the arrangement ending.', 'Dependants carry the cost of decisions they could not participate in.', 'Check the obligation is written where a dependant or their advocate could actually enforce it.', 'A dependant''s existing claim is never reduced to make a new arrangement work.'),
  ('FAMILY.FAMILY_BOUNDARIES', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · FAMILY BOUNDARIES', 0, 3, 'What may relatives decide, enter, or be told about this household — and which adult here delivers the no to their own people?', 'A boundary map naming what is decided inside and what is not.', 'Outside interference is rarely about the outsider; it is about who will hold a line with their own people.', 'Test against a real past incident. What happened is the boundary, whatever was intended.', 'Each party holds the line with their own people. Nobody is required to deliver another''s bad news.'),
  ('FAMILY.FAITH_WORLDVIEW', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · FAITH / WORLDVIEW', 0, 4, 'What belief and what family account of where we come from is being taught here as settled, and what is actually documented, oral, or contested?', 'A named governing authority and a stated consequence for dissent.', 'An unnamed governing belief defaults to whoever can invoke one, which is a power question in other clothes.', 'Look at what is scheduled and what is funded. Both record the operative creed more honestly than a statement.', 'Nobody is bound to an authority they did not personally accept, and accepting one does not surrender the right to leave.'),
  ('FAMILY.SEX_INTIMACY', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · CLOSENESS & POWER', 0, 5, 'Where do closeness and power overlap between the adults here, and what happens in the hours after one of them says no?', 'A concrete description of the aftermath of refusal, from both sides.', 'Coercion lives in the aftermath — the silence, the withdrawal, the lost opportunity — rather than in the moment.', 'Compare both accounts of the same past refusal. A gap between them is the finding.', 'Consent is not transferred by any household arrangement. If either account describes pressure, fear or inability to leave, this routes to a support service and no answer is recorded.'),
  ('FAMILY.HOUSEHOLD_LABOR', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · UNSEEN LABOUR', 0, 6, 'Who carries the care, the appointments, the remembering and the whole schedule in their head — and does anyone else know the size of it?', 'A task inventory with a named owner per line, including remembering and noticing.', 'Unwritten work is allocated by default to whoever notices it first, permanently.', 'Track a real week. Self-report and observation diverge substantially in both directions.', 'Naming an imbalance is information, not an accusation, and is not answered with a list of the other side''s contributions.'),
  ('FAMILY.CONFLICT', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · CONFLICT', 0, 7, 'What happens here under pressure, what is never permitted, and what happens the first time that line is crossed?', 'Described pressure patterns and a short list of unconditional prohibitions.', 'Arrangements do not fail because there is conflict. They fail because of what is permitted during it.', 'Describe the last three real disputes: who escalated, who went silent, how it ended.', 'Threats, retaliation and intimidation are on the prohibited list by default and are not negotiable items.'),
  ('FAMILY.HEALTH_CARE', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · CAPACITY & CARE', 0, 8, 'Who decides for each adult here when they cannot decide, is it documented, and which elder may need care within two years?', 'A named decision-holder for incapacity and a named practical continuity plan.', 'Continuity decisions get made by whoever is present, unless they were made earlier.', 'Confirm the named holder is documented where it would actually be honoured. Intention is not authority.', 'No health detail is stored here. Only the position, the named holder and the document''s existence.'),
  ('FAMILY.CAREERS', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · PATHS', 0, 9, 'Whose work moves first when both cannot be accommodated, and what does the person who steps back receive and by when?', 'A decision rule agreed before a specific opportunity is on the table.', 'Without a rule, the party with more leverage wins by default and the other path quietly becomes secondary.', 'Apply the rule to a real opportunity. An untested rule is a sentiment.', 'The rule is symmetrical and reviewable. Deferring once does not establish a permanent order.'),
  ('FAMILY.GEOGRAPHY', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · PLACE', 0, 10, 'Where does this household live, who is farthest from their own people, and whose immigration or safety position depends on staying?', 'A place decision with differential exposure named per person.', 'Two people in the same room can be in materially different countries.', 'Ask the more exposed party. The less exposed party''s assessment is not a measurement.', 'Any threat involving a household member''s immigration status, documents or ability to leave is named here as abuse, not as a negotiating position.'),
  ('FAMILY.PRIVACY', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · PRIVACY', 0, 11, 'What stays each person''s own here — devices, history, friendships, therapy — and is any monitoring happening that the monitored person does not know about?', 'A stated privacy line per domain with an explicit revocation right.', 'Access that cannot be revoked is not sharing; it is monitoring.', 'Check whether the dependant and the unpaid caregiver could withdraw access today without a confrontation. If not, that is the real rule.', 'Privacy is not evidence of wrongdoing. A request for it is never recorded as a finding.'),
  ('FAMILY.TRUST', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · TRUST', 0, 12, 'What would end this for each adult here, and what is currently unresolved that both have agreed not to raise?', 'A named breach threshold per party and an inventory of open matters.', 'Arrangements are entered carrying unresolved matter everyone has agreed not to mention.', 'If the list of open matters is empty, ask each party separately. Empty lists are usually courteous.', 'A matter raised here is met once without retaliation, or the question should not have been asked.'),
  ('FAMILY.FUTURE_CHANGE', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · FUTURE CHANGE', 0, 13, 'What change in one of us would this household survive, what would it not, and when do we deliberately revisit all of this?', 'A named set of foreseeable changes, a response to each, and a review date in a calendar.', 'Agreements without a review date are enforced against people who have since changed.', 'Test five concrete changes rather than a general willingness to adapt.', 'Any party may call a review early without justifying why.'),
  ('FAMILY.DEAL_BREAKERS', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · DEAL BREAKERS', 0, 14, 'What is each adult unwilling to accept under any circumstance, and what is on the floor whether they named it or not?', 'Short unsoftened limit lists, plus a stated floor nobody can remove by agreement.', 'A limit that is never stated is discovered only by being crossed.', 'Check each item is genuinely absolute. Anything with a condition belongs in another axis.', 'Coercion, retaliation, harm to dependants, and control of another''s money, documents or care are on the floor and are not removable by agreement.'),
  ('FAMILY.REPAIR', 'QYRIS-INDUSTRY-001', null, 'FAMILY', 'FAMILY · REPAIR', 0, 15, 'When one of us has hurt the other, what actually repairs it in actions — and what do we do the fourth time?', 'A repair sequence that can be followed while upset, and a named escalation for repetition.', 'Arrangements survive on repair capacity far more than on initial compatibility.', 'Check the sequence includes a behaviour change, not only an acknowledgement. Count repeats; four is a number, not a mood.', 'Repair is not the harmed party''s job, and non-acceptance of a repair is not punished.')
on conflict (node_id) do update set
  pack_id = excluded.pack_id, cluster_id = excluded.cluster_id, label = excluded.label,
  ordinal = excluded.ordinal, question = excluded.question, yield = excluded.yield,
  reason = excluded.reason, inspect = excluded.inspect, safeguard = excluded.safeguard;

insert into qyr_node_deltas (node_id, delta_code) values
  ('MUSIC.MONEY', 'EVIDENCE'),
  ('MUSIC.MONEY', 'AUTHORITY'),
  ('MUSIC.MONEY', 'TRANSFER'),
  ('MUSIC.DEBT', 'EVIDENCE'),
  ('MUSIC.DEBT', 'RISK'),
  ('MUSIC.DEBT', 'TRANSFER'),
  ('MUSIC.CHILDREN', 'AUTHORITY'),
  ('MUSIC.CHILDREN', 'RISK'),
  ('MUSIC.CHILDREN', 'TRANSFER'),
  ('MUSIC.FAMILY_BOUNDARIES', 'ACTION'),
  ('MUSIC.FAMILY_BOUNDARIES', 'AUTHORITY'),
  ('MUSIC.FAMILY_BOUNDARIES', 'RISK'),
  ('MUSIC.FAITH_WORLDVIEW', 'ACTION'),
  ('MUSIC.FAITH_WORLDVIEW', 'AUTHORITY'),
  ('MUSIC.FAITH_WORLDVIEW', 'RISK'),
  ('MUSIC.SEX_INTIMACY', 'RISK'),
  ('MUSIC.SEX_INTIMACY', 'AUTHORITY'),
  ('MUSIC.HOUSEHOLD_LABOR', 'ACTION'),
  ('MUSIC.HOUSEHOLD_LABOR', 'EVIDENCE'),
  ('MUSIC.HOUSEHOLD_LABOR', 'TRANSFER'),
  ('MUSIC.CONFLICT', 'ACTION'),
  ('MUSIC.CONFLICT', 'RISK'),
  ('MUSIC.CONFLICT', 'AUTHORITY'),
  ('MUSIC.HEALTH_CARE', 'AUTHORITY'),
  ('MUSIC.HEALTH_CARE', 'RISK'),
  ('MUSIC.HEALTH_CARE', 'ACTION'),
  ('MUSIC.CAREERS', 'ACTION'),
  ('MUSIC.CAREERS', 'AUTHORITY'),
  ('MUSIC.CAREERS', 'TRANSFER'),
  ('MUSIC.GEOGRAPHY', 'RISK'),
  ('MUSIC.GEOGRAPHY', 'AUTHORITY'),
  ('MUSIC.GEOGRAPHY', 'ACTION'),
  ('MUSIC.PRIVACY', 'AUTHORITY'),
  ('MUSIC.PRIVACY', 'RISK'),
  ('MUSIC.PRIVACY', 'EVIDENCE'),
  ('MUSIC.TRUST', 'EVIDENCE'),
  ('MUSIC.TRUST', 'RISK'),
  ('MUSIC.TRUST', 'AUTHORITY'),
  ('MUSIC.FUTURE_CHANGE', 'RISK'),
  ('MUSIC.FUTURE_CHANGE', 'AUTHORITY'),
  ('MUSIC.FUTURE_CHANGE', 'ACTION'),
  ('MUSIC.DEAL_BREAKERS', 'RISK'),
  ('MUSIC.DEAL_BREAKERS', 'AUTHORITY'),
  ('MUSIC.REPAIR', 'ACTION'),
  ('MUSIC.REPAIR', 'AUTHORITY'),
  ('MUSIC.REPAIR', 'RISK'),
  ('COMEDY.MONEY', 'EVIDENCE'),
  ('COMEDY.MONEY', 'AUTHORITY'),
  ('COMEDY.MONEY', 'TRANSFER'),
  ('COMEDY.DEBT', 'EVIDENCE'),
  ('COMEDY.DEBT', 'RISK'),
  ('COMEDY.DEBT', 'TRANSFER'),
  ('COMEDY.CHILDREN', 'AUTHORITY'),
  ('COMEDY.CHILDREN', 'RISK'),
  ('COMEDY.CHILDREN', 'TRANSFER'),
  ('COMEDY.FAMILY_BOUNDARIES', 'ACTION'),
  ('COMEDY.FAMILY_BOUNDARIES', 'AUTHORITY'),
  ('COMEDY.FAMILY_BOUNDARIES', 'RISK'),
  ('COMEDY.FAITH_WORLDVIEW', 'ACTION'),
  ('COMEDY.FAITH_WORLDVIEW', 'AUTHORITY'),
  ('COMEDY.FAITH_WORLDVIEW', 'RISK'),
  ('COMEDY.SEX_INTIMACY', 'RISK'),
  ('COMEDY.SEX_INTIMACY', 'AUTHORITY'),
  ('COMEDY.HOUSEHOLD_LABOR', 'ACTION'),
  ('COMEDY.HOUSEHOLD_LABOR', 'EVIDENCE'),
  ('COMEDY.HOUSEHOLD_LABOR', 'TRANSFER'),
  ('COMEDY.CONFLICT', 'ACTION'),
  ('COMEDY.CONFLICT', 'RISK'),
  ('COMEDY.CONFLICT', 'AUTHORITY'),
  ('COMEDY.HEALTH_CARE', 'AUTHORITY'),
  ('COMEDY.HEALTH_CARE', 'RISK'),
  ('COMEDY.HEALTH_CARE', 'ACTION'),
  ('COMEDY.CAREERS', 'ACTION'),
  ('COMEDY.CAREERS', 'AUTHORITY'),
  ('COMEDY.CAREERS', 'TRANSFER'),
  ('COMEDY.GEOGRAPHY', 'RISK'),
  ('COMEDY.GEOGRAPHY', 'AUTHORITY'),
  ('COMEDY.GEOGRAPHY', 'ACTION'),
  ('COMEDY.PRIVACY', 'AUTHORITY'),
  ('COMEDY.PRIVACY', 'RISK'),
  ('COMEDY.PRIVACY', 'EVIDENCE'),
  ('COMEDY.TRUST', 'EVIDENCE'),
  ('COMEDY.TRUST', 'RISK'),
  ('COMEDY.TRUST', 'AUTHORITY'),
  ('COMEDY.FUTURE_CHANGE', 'RISK'),
  ('COMEDY.FUTURE_CHANGE', 'AUTHORITY'),
  ('COMEDY.FUTURE_CHANGE', 'ACTION'),
  ('COMEDY.DEAL_BREAKERS', 'RISK'),
  ('COMEDY.DEAL_BREAKERS', 'AUTHORITY'),
  ('COMEDY.REPAIR', 'ACTION'),
  ('COMEDY.REPAIR', 'AUTHORITY'),
  ('COMEDY.REPAIR', 'RISK'),
  ('BUSINESS.MONEY', 'EVIDENCE'),
  ('BUSINESS.MONEY', 'AUTHORITY'),
  ('BUSINESS.MONEY', 'TRANSFER'),
  ('BUSINESS.DEBT', 'EVIDENCE'),
  ('BUSINESS.DEBT', 'RISK'),
  ('BUSINESS.DEBT', 'TRANSFER'),
  ('BUSINESS.CHILDREN', 'AUTHORITY'),
  ('BUSINESS.CHILDREN', 'RISK'),
  ('BUSINESS.CHILDREN', 'TRANSFER'),
  ('BUSINESS.FAMILY_BOUNDARIES', 'ACTION'),
  ('BUSINESS.FAMILY_BOUNDARIES', 'AUTHORITY'),
  ('BUSINESS.FAMILY_BOUNDARIES', 'RISK'),
  ('BUSINESS.FAITH_WORLDVIEW', 'ACTION'),
  ('BUSINESS.FAITH_WORLDVIEW', 'AUTHORITY'),
  ('BUSINESS.FAITH_WORLDVIEW', 'RISK'),
  ('BUSINESS.SEX_INTIMACY', 'RISK'),
  ('BUSINESS.SEX_INTIMACY', 'AUTHORITY'),
  ('BUSINESS.HOUSEHOLD_LABOR', 'ACTION'),
  ('BUSINESS.HOUSEHOLD_LABOR', 'EVIDENCE'),
  ('BUSINESS.HOUSEHOLD_LABOR', 'TRANSFER'),
  ('BUSINESS.CONFLICT', 'ACTION'),
  ('BUSINESS.CONFLICT', 'RISK'),
  ('BUSINESS.CONFLICT', 'AUTHORITY'),
  ('BUSINESS.HEALTH_CARE', 'AUTHORITY'),
  ('BUSINESS.HEALTH_CARE', 'RISK'),
  ('BUSINESS.HEALTH_CARE', 'ACTION'),
  ('BUSINESS.CAREERS', 'ACTION'),
  ('BUSINESS.CAREERS', 'AUTHORITY'),
  ('BUSINESS.CAREERS', 'TRANSFER'),
  ('BUSINESS.GEOGRAPHY', 'RISK'),
  ('BUSINESS.GEOGRAPHY', 'AUTHORITY'),
  ('BUSINESS.GEOGRAPHY', 'ACTION'),
  ('BUSINESS.PRIVACY', 'AUTHORITY'),
  ('BUSINESS.PRIVACY', 'RISK'),
  ('BUSINESS.PRIVACY', 'EVIDENCE'),
  ('BUSINESS.TRUST', 'EVIDENCE'),
  ('BUSINESS.TRUST', 'RISK'),
  ('BUSINESS.TRUST', 'AUTHORITY'),
  ('BUSINESS.FUTURE_CHANGE', 'RISK'),
  ('BUSINESS.FUTURE_CHANGE', 'AUTHORITY'),
  ('BUSINESS.FUTURE_CHANGE', 'ACTION'),
  ('BUSINESS.DEAL_BREAKERS', 'RISK'),
  ('BUSINESS.DEAL_BREAKERS', 'AUTHORITY'),
  ('BUSINESS.REPAIR', 'ACTION'),
  ('BUSINESS.REPAIR', 'AUTHORITY'),
  ('BUSINESS.REPAIR', 'RISK'),
  ('RELIGION.MONEY', 'EVIDENCE'),
  ('RELIGION.MONEY', 'AUTHORITY'),
  ('RELIGION.MONEY', 'TRANSFER'),
  ('RELIGION.DEBT', 'EVIDENCE'),
  ('RELIGION.DEBT', 'RISK'),
  ('RELIGION.DEBT', 'TRANSFER'),
  ('RELIGION.CHILDREN', 'AUTHORITY'),
  ('RELIGION.CHILDREN', 'RISK'),
  ('RELIGION.CHILDREN', 'TRANSFER'),
  ('RELIGION.FAMILY_BOUNDARIES', 'ACTION'),
  ('RELIGION.FAMILY_BOUNDARIES', 'AUTHORITY'),
  ('RELIGION.FAMILY_BOUNDARIES', 'RISK'),
  ('RELIGION.FAITH_WORLDVIEW', 'ACTION'),
  ('RELIGION.FAITH_WORLDVIEW', 'AUTHORITY'),
  ('RELIGION.FAITH_WORLDVIEW', 'RISK'),
  ('RELIGION.SEX_INTIMACY', 'RISK'),
  ('RELIGION.SEX_INTIMACY', 'AUTHORITY'),
  ('RELIGION.HOUSEHOLD_LABOR', 'ACTION'),
  ('RELIGION.HOUSEHOLD_LABOR', 'EVIDENCE'),
  ('RELIGION.HOUSEHOLD_LABOR', 'TRANSFER'),
  ('RELIGION.CONFLICT', 'ACTION'),
  ('RELIGION.CONFLICT', 'RISK'),
  ('RELIGION.CONFLICT', 'AUTHORITY'),
  ('RELIGION.HEALTH_CARE', 'AUTHORITY'),
  ('RELIGION.HEALTH_CARE', 'RISK'),
  ('RELIGION.HEALTH_CARE', 'ACTION'),
  ('RELIGION.CAREERS', 'ACTION'),
  ('RELIGION.CAREERS', 'AUTHORITY'),
  ('RELIGION.CAREERS', 'TRANSFER'),
  ('RELIGION.GEOGRAPHY', 'RISK'),
  ('RELIGION.GEOGRAPHY', 'AUTHORITY'),
  ('RELIGION.GEOGRAPHY', 'ACTION'),
  ('RELIGION.PRIVACY', 'AUTHORITY'),
  ('RELIGION.PRIVACY', 'RISK'),
  ('RELIGION.PRIVACY', 'EVIDENCE'),
  ('RELIGION.TRUST', 'EVIDENCE'),
  ('RELIGION.TRUST', 'RISK'),
  ('RELIGION.TRUST', 'AUTHORITY'),
  ('RELIGION.FUTURE_CHANGE', 'RISK'),
  ('RELIGION.FUTURE_CHANGE', 'AUTHORITY'),
  ('RELIGION.FUTURE_CHANGE', 'ACTION'),
  ('RELIGION.DEAL_BREAKERS', 'RISK'),
  ('RELIGION.DEAL_BREAKERS', 'AUTHORITY'),
  ('RELIGION.REPAIR', 'ACTION'),
  ('RELIGION.REPAIR', 'AUTHORITY'),
  ('RELIGION.REPAIR', 'RISK'),
  ('EDUCATION.MONEY', 'EVIDENCE'),
  ('EDUCATION.MONEY', 'AUTHORITY'),
  ('EDUCATION.MONEY', 'TRANSFER'),
  ('EDUCATION.DEBT', 'EVIDENCE'),
  ('EDUCATION.DEBT', 'RISK'),
  ('EDUCATION.DEBT', 'TRANSFER'),
  ('EDUCATION.CHILDREN', 'AUTHORITY'),
  ('EDUCATION.CHILDREN', 'RISK'),
  ('EDUCATION.CHILDREN', 'TRANSFER'),
  ('EDUCATION.FAMILY_BOUNDARIES', 'ACTION'),
  ('EDUCATION.FAMILY_BOUNDARIES', 'AUTHORITY'),
  ('EDUCATION.FAMILY_BOUNDARIES', 'RISK'),
  ('EDUCATION.FAITH_WORLDVIEW', 'ACTION'),
  ('EDUCATION.FAITH_WORLDVIEW', 'AUTHORITY'),
  ('EDUCATION.FAITH_WORLDVIEW', 'RISK'),
  ('EDUCATION.SEX_INTIMACY', 'RISK'),
  ('EDUCATION.SEX_INTIMACY', 'AUTHORITY'),
  ('EDUCATION.HOUSEHOLD_LABOR', 'ACTION'),
  ('EDUCATION.HOUSEHOLD_LABOR', 'EVIDENCE'),
  ('EDUCATION.HOUSEHOLD_LABOR', 'TRANSFER'),
  ('EDUCATION.CONFLICT', 'ACTION'),
  ('EDUCATION.CONFLICT', 'RISK'),
  ('EDUCATION.CONFLICT', 'AUTHORITY'),
  ('EDUCATION.HEALTH_CARE', 'AUTHORITY'),
  ('EDUCATION.HEALTH_CARE', 'RISK'),
  ('EDUCATION.HEALTH_CARE', 'ACTION'),
  ('EDUCATION.CAREERS', 'ACTION'),
  ('EDUCATION.CAREERS', 'AUTHORITY'),
  ('EDUCATION.CAREERS', 'TRANSFER'),
  ('EDUCATION.GEOGRAPHY', 'RISK'),
  ('EDUCATION.GEOGRAPHY', 'AUTHORITY'),
  ('EDUCATION.GEOGRAPHY', 'ACTION'),
  ('EDUCATION.PRIVACY', 'AUTHORITY'),
  ('EDUCATION.PRIVACY', 'RISK'),
  ('EDUCATION.PRIVACY', 'EVIDENCE'),
  ('EDUCATION.TRUST', 'EVIDENCE'),
  ('EDUCATION.TRUST', 'RISK'),
  ('EDUCATION.TRUST', 'AUTHORITY'),
  ('EDUCATION.FUTURE_CHANGE', 'RISK'),
  ('EDUCATION.FUTURE_CHANGE', 'AUTHORITY'),
  ('EDUCATION.FUTURE_CHANGE', 'ACTION'),
  ('EDUCATION.DEAL_BREAKERS', 'RISK'),
  ('EDUCATION.DEAL_BREAKERS', 'AUTHORITY'),
  ('EDUCATION.REPAIR', 'ACTION'),
  ('EDUCATION.REPAIR', 'AUTHORITY'),
  ('EDUCATION.REPAIR', 'RISK'),
  ('FAMILY.MONEY', 'EVIDENCE'),
  ('FAMILY.MONEY', 'AUTHORITY'),
  ('FAMILY.MONEY', 'TRANSFER'),
  ('FAMILY.DEBT', 'EVIDENCE'),
  ('FAMILY.DEBT', 'RISK'),
  ('FAMILY.DEBT', 'TRANSFER'),
  ('FAMILY.CHILDREN', 'AUTHORITY'),
  ('FAMILY.CHILDREN', 'RISK'),
  ('FAMILY.CHILDREN', 'TRANSFER'),
  ('FAMILY.FAMILY_BOUNDARIES', 'ACTION'),
  ('FAMILY.FAMILY_BOUNDARIES', 'AUTHORITY'),
  ('FAMILY.FAMILY_BOUNDARIES', 'RISK'),
  ('FAMILY.FAITH_WORLDVIEW', 'ACTION'),
  ('FAMILY.FAITH_WORLDVIEW', 'AUTHORITY'),
  ('FAMILY.FAITH_WORLDVIEW', 'RISK'),
  ('FAMILY.SEX_INTIMACY', 'RISK'),
  ('FAMILY.SEX_INTIMACY', 'AUTHORITY'),
  ('FAMILY.HOUSEHOLD_LABOR', 'ACTION'),
  ('FAMILY.HOUSEHOLD_LABOR', 'EVIDENCE'),
  ('FAMILY.HOUSEHOLD_LABOR', 'TRANSFER'),
  ('FAMILY.CONFLICT', 'ACTION'),
  ('FAMILY.CONFLICT', 'RISK'),
  ('FAMILY.CONFLICT', 'AUTHORITY'),
  ('FAMILY.HEALTH_CARE', 'AUTHORITY'),
  ('FAMILY.HEALTH_CARE', 'RISK'),
  ('FAMILY.HEALTH_CARE', 'ACTION'),
  ('FAMILY.CAREERS', 'ACTION'),
  ('FAMILY.CAREERS', 'AUTHORITY'),
  ('FAMILY.CAREERS', 'TRANSFER'),
  ('FAMILY.GEOGRAPHY', 'RISK'),
  ('FAMILY.GEOGRAPHY', 'AUTHORITY'),
  ('FAMILY.GEOGRAPHY', 'ACTION'),
  ('FAMILY.PRIVACY', 'AUTHORITY'),
  ('FAMILY.PRIVACY', 'RISK'),
  ('FAMILY.PRIVACY', 'EVIDENCE'),
  ('FAMILY.TRUST', 'EVIDENCE'),
  ('FAMILY.TRUST', 'RISK'),
  ('FAMILY.TRUST', 'AUTHORITY'),
  ('FAMILY.FUTURE_CHANGE', 'RISK'),
  ('FAMILY.FUTURE_CHANGE', 'AUTHORITY'),
  ('FAMILY.FUTURE_CHANGE', 'ACTION'),
  ('FAMILY.DEAL_BREAKERS', 'RISK'),
  ('FAMILY.DEAL_BREAKERS', 'AUTHORITY'),
  ('FAMILY.REPAIR', 'ACTION'),
  ('FAMILY.REPAIR', 'AUTHORITY'),
  ('FAMILY.REPAIR', 'RISK')
on conflict do nothing;

insert into qyr_projections (node_id, axis_id, domain_id, provenance) values
  ('MUSIC.MONEY', 'MONEY', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.DEBT', 'DEBT', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.CHILDREN', 'CHILDREN', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.SEX_INTIMACY', 'SEX_INTIMACY', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.CONFLICT', 'CONFLICT', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.HEALTH_CARE', 'HEALTH_CARE', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.CAREERS', 'CAREERS', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.GEOGRAPHY', 'GEOGRAPHY', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.PRIVACY', 'PRIVACY', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.TRUST', 'TRUST', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.FUTURE_CHANGE', 'FUTURE_CHANGE', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.DEAL_BREAKERS', 'DEAL_BREAKERS', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('MUSIC.REPAIR', 'REPAIR', 'MUSIC', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.MONEY', 'MONEY', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.DEBT', 'DEBT', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.CHILDREN', 'CHILDREN', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.SEX_INTIMACY', 'SEX_INTIMACY', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.CONFLICT', 'CONFLICT', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.HEALTH_CARE', 'HEALTH_CARE', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.CAREERS', 'CAREERS', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.GEOGRAPHY', 'GEOGRAPHY', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.PRIVACY', 'PRIVACY', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.TRUST', 'TRUST', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.FUTURE_CHANGE', 'FUTURE_CHANGE', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.DEAL_BREAKERS', 'DEAL_BREAKERS', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('COMEDY.REPAIR', 'REPAIR', 'COMEDY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.MONEY', 'MONEY', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.DEBT', 'DEBT', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.CHILDREN', 'CHILDREN', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.SEX_INTIMACY', 'SEX_INTIMACY', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.CONFLICT', 'CONFLICT', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.HEALTH_CARE', 'HEALTH_CARE', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.CAREERS', 'CAREERS', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.GEOGRAPHY', 'GEOGRAPHY', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.PRIVACY', 'PRIVACY', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.TRUST', 'TRUST', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.FUTURE_CHANGE', 'FUTURE_CHANGE', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.DEAL_BREAKERS', 'DEAL_BREAKERS', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('BUSINESS.REPAIR', 'REPAIR', 'BUSINESS', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.MONEY', 'MONEY', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.DEBT', 'DEBT', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.CHILDREN', 'CHILDREN', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"AUTHORED"}'::jsonb),
  ('RELIGION.FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.SEX_INTIMACY', 'SEX_INTIMACY', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.CONFLICT', 'CONFLICT', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.HEALTH_CARE', 'HEALTH_CARE', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.CAREERS', 'CAREERS', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.GEOGRAPHY', 'GEOGRAPHY', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.PRIVACY', 'PRIVACY', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"AUTHORED"}'::jsonb),
  ('RELIGION.TRUST', 'TRUST', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.FUTURE_CHANGE', 'FUTURE_CHANGE', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.DEAL_BREAKERS', 'DEAL_BREAKERS', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('RELIGION.REPAIR', 'REPAIR', 'RELIGION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.MONEY', 'MONEY', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.DEBT', 'DEBT', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.CHILDREN', 'CHILDREN', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"AUTHORED"}'::jsonb),
  ('EDUCATION.FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.SEX_INTIMACY', 'SEX_INTIMACY', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"AUTHORED"}'::jsonb),
  ('EDUCATION.HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.CONFLICT', 'CONFLICT', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.HEALTH_CARE', 'HEALTH_CARE', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.CAREERS', 'CAREERS', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.GEOGRAPHY', 'GEOGRAPHY', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.PRIVACY', 'PRIVACY', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"AUTHORED"}'::jsonb),
  ('EDUCATION.TRUST', 'TRUST', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.FUTURE_CHANGE', 'FUTURE_CHANGE', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.DEAL_BREAKERS', 'DEAL_BREAKERS', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('EDUCATION.REPAIR', 'REPAIR', 'EDUCATION', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.MONEY', 'MONEY', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.DEBT', 'DEBT', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.CHILDREN', 'CHILDREN', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.FAMILY_BOUNDARIES', 'FAMILY_BOUNDARIES', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.FAITH_WORLDVIEW', 'FAITH_WORLDVIEW', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.SEX_INTIMACY', 'SEX_INTIMACY', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"AUTHORED"}'::jsonb),
  ('FAMILY.HOUSEHOLD_LABOR', 'HOUSEHOLD_LABOR', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.CONFLICT', 'CONFLICT', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.HEALTH_CARE', 'HEALTH_CARE', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.CAREERS', 'CAREERS', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.GEOGRAPHY', 'GEOGRAPHY', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"AUTHORED"}'::jsonb),
  ('FAMILY.PRIVACY', 'PRIVACY', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.TRUST', 'TRUST', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.FUTURE_CHANGE', 'FUTURE_CHANGE', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.DEAL_BREAKERS', 'DEAL_BREAKERS', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb),
  ('FAMILY.REPAIR', 'REPAIR', 'FAMILY', '{"question":"AUTHORED","yield":"MECHANICAL","reason":"MECHANICAL","inspect":"MECHANICAL","safeguard":"MECHANICAL"}'::jsonb)
on conflict (node_id) do update set provenance = excluded.provenance;

-- 96 projected questions: 16 axes x 6 domains.
