const SUPABASE_URL='https://jvsdxhrfhtlgaknhjxlz.supabase.co';
const SUPABASE_KEY='sb_publishable_ta33XJ9rtS8VljoUYw-GuA_Pi4OycpQ';
const SESSION_KEY='thylora_app_auth_session';
function session(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function token(){return session()?.access_token||SUPABASE_KEY}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(path){const r=await fetch(`${SUPABASE_URL}${path}`,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token()}`}});const text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||text||`HTTP ${r.status}`);return data}
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.bet-panel').forEach(x=>x.classList.toggle('active',x.id===b.dataset.panel))}));
async function load(){try{const [teams,catalog,games,staff]=await Promise.all([api('/rest/v1/sports_team_registry?select=team_code,competition_code,thylora_name,earth_english_name,status,unresolved&order=team_code'),api('/rest/v1/game_bet_market_catalog?select=catalog_code,sport_class,display_name,explanation_child,explanation_young_adult,settlement_rule,availability_state&order=sport_class,catalog_code'),api('/rest/v1/game_bet_casino_games?select=game_code,display_name,skill_class,rules_plain,rules_expanded,payout_table,published_house_edge,state&order=display_name'),api('/rest/v1/game_bet_staff_roster?select=staff_code,display_name,pronunciation,person_layer,desk,role_title,shift_pattern,employment_state&order=staff_code')]);
document.getElementById('teamCount').textContent=teams.length;document.getElementById('catalogCount').textContent=catalog.length;document.getElementById('gameCount').textContent=games.length;document.getElementById('staffCount').textContent=staff.length;document.getElementById('boardStatus').textContent=`${teams.length} registry records · verified season board not yet available`;
document.getElementById('teamBoard').innerHTML=teams.slice(0,12).map(t=>`<article><p class="eyebrow">${esc(t.competition_code||'SPORT')}</p><h3>${esc(t.thylora_name||'OPEN TEAM SLOT')}</h3><p>${esc(t.team_code)} · ${esc(t.status||'UNKNOWN')}</p><span class="tag">${Array.isArray(t.unresolved)?t.unresolved.length:0} open items</span></article>`).join('');
document.getElementById('marketCatalog').innerHTML=catalog.map(m=>`<article><p class="eyebrow">${esc(m.sport_class.toUpperCase())}</p><h3>${esc(m.display_name)}</h3><p><strong>Simple:</strong> ${esc(m.explanation_child)}</p><p><strong>Detail:</strong> ${esc(m.explanation_young_adult)}</p><small>${esc(m.settlement_rule)}</small></article>`).join('');
document.getElementById('casinoGames').innerHTML=games.map(g=>`<article><p class="eyebrow">${esc(g.skill_class)}</p><h3>${esc(g.display_name)}</h3><p>${esc(g.rules_plain)}</p><small>House edge: ${esc(JSON.stringify(g.published_house_edge))}</small><span class="tag">${esc(g.state)}</span></article>`).join('');
document.getElementById('staffBoard').innerHTML=staff.map(s=>`<article><p class="eyebrow">${esc(s.desk)}</p><h3>${esc(s.display_name)}</h3><p>${esc(s.pronunciation||'Pronunciation OPEN')} · ${esc(s.role_title)}</p><small>${esc(s.shift_pattern||'Schedule OPEN')}</small><span class="tag">${esc(s.employment_state)}</span></article>`).join('');
}catch(e){document.getElementById('boardStatus').textContent=`Backend read blocked: ${e.message}`}}
load();