-- THYLORA · PRODUCT VISUAL QUALITY GATE (fail-closed, pre-preview)
-- Work code: THY-WORK-VISUAL-STANDARD-RECOVERY-545
-- Gate code: THY-VISUAL-QUALITY-GATE-001
-- Binds:     THY-WORK-BRAMBLE-PROOF-PRODUCT-544
--
-- This supplies the criteria behind a boolean the release-review surface already
-- renders — visual_preflight_passed in get_thylora_release_review_candidates_v1()
-- — which until now nothing defined. It creates no second product truth, no
-- second approval system and no second preview surface.
--
-- Fail-closed: absence of evidence is a FAIL, never a pass.

begin;

-- 1 · Page plan. One row per meaningful page or spread. The eleven columns after
--     product_code are the eleven questions the page standard requires.
create table if not exists thylora_product_page_plan (
  product_code   text not null,
  page_index     integer not null,
  page_label     text,
  meaningful     boolean not null default true,

  who_is_here              text,
  where_are_they           text,
  when_is_it               text,
  what_are_they_doing      text,
  objects_present          text,
  object_makers            text,
  background_action        text,
  light_weather            text,
  world_signature          text,
  text_region              text,
  differs_from_previous    text,

  illustration_ref                  text,
  reference_binding                 text,
  illustration_area_ratio           numeric(4,3) check (illustration_area_ratio between 0 and 1),
  illustration_carries_information  boolean,
  world_continues_beyond_subject    boolean,
  composition_signature             text,
  white_page_dominant               boolean not null default false,
  era_declared                      text,
  era_exception_approved            text,

  artistic_exception               text,
  artistic_exception_justification text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (product_code, page_index),
  -- A blank white page is allowed only as a documented AND justified exception.
  constraint thylora_page_white_needs_justified_exception check (
    white_page_dominant = false
    or (coalesce(artistic_exception,'') <> '' and coalesce(artistic_exception_justification,'') <> '')
  )
);

-- 2 · Authored product identity. RESOLVED or explicitly OPEN. Never invented.
create table if not exists thylora_product_authorship (
  product_code text not null,
  role_code    text not null check (role_code in
    ('AUTHOR','EDITOR','ILLUSTRATOR','DESIGNER','PUBLISHER_IMPRINT','PRODUCTION_HOUSE')),
  byline       text,
  role_state   text not null check (role_state in ('RESOLVED','OPEN')),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  primary key (product_code, role_code),
  constraint thylora_authorship_resolved_needs_a_name check (
    role_state <> 'RESOLVED' or coalesce(byline,'') <> ''),
  -- A generic system-generated byline is not an authored identity.
  constraint thylora_authorship_no_generic_byline check (
    role_state <> 'RESOLVED' or lower(btrim(byline)) <> all (array[
      'thylora','thylora system','system','system-generated','ai','ai generated',
      'ai-generated','generated','auto','automated','admin','staff','team',
      'n/a','na','tbd','unknown','anonymous','assistant','claude','chatgpt',
      'openai','midjourney','stable diffusion','dall-e','dalle']))
);

-- 3 · Product-level visual facts the page plan cannot hold.
create table if not exists thylora_product_visual_record (
  product_code                text primary key,
  product_kind                text not null default 'ILLUSTRATED_STORY',
  story_summary               text,
  visual_matches_story        boolean,
  reads_as_lesson_handout     boolean not null default false,
  generated_without_reference boolean not null default false,
  price_minor_units           bigint,
  price_value_basis           text,
  external_product_id         text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 4 · Append-only gate results. A gate run is evidence, so it is never updated.
create table if not exists thylora_visual_gate_checks (
  check_id     bigint generated always as identity primary key,
  gate_code    text not null default 'THY-VISUAL-QUALITY-GATE-001',
  product_code text not null,
  gate_state   text not null check (gate_state in ('PASS','FAIL')),
  problems     jsonb not null default '[]'::jsonb,
  evaluated_at timestamptz not null default now(),
  evaluated_by uuid
);
create index if not exists thylora_visual_gate_checks_product
  on thylora_visual_gate_checks (product_code, evaluated_at desc);

-- 5 · The gate. Returns every failing condition in one call, each with a route.
create or replace function thylora_visual_gate_evaluate_v1(p_product_code text)
returns jsonb language plpgsql stable security definer set search_path = public as $fn$
declare
  problems jsonb := '[]'::jsonb;
  rec      thylora_product_visual_record;
  n_pages  integer;
  illustrated boolean;
  mean_ratio numeric;
  v_open_author boolean;
  v_open_illus  boolean;
  v_res_author  boolean;
  v_res_illus   boolean;

  procedure_add text;
begin
  if not (thylora_is_chairman() or thylora_is_trusted_server()) then
    return jsonb_build_object('ok', false,
      'reason', 'CHAIRMAN_ONLY: thylora_visual_gate_evaluate_v1 is readable by the Chairman or a trusted server only.');
  end if;

  select * into rec from thylora_product_visual_record where product_code = p_product_code;
  select count(*) into n_pages from thylora_product_page_plan where product_code = p_product_code;
  illustrated := coalesce(rec.product_kind, 'ILLUSTRATED_STORY') <> 'NON_ILLUSTRATED';

  -- Fail-closed: a product with no visual record at all is not previewable.
  if rec.product_code is null then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_PAGE_ARCHITECTURE',
      'detail','No visual record exists for this product. Absence of evidence is a FAIL.',
      'route','thylora_product_visual_record'));
  end if;

  if illustrated and n_pages = 0 then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_PAGE_ARCHITECTURE',
      'detail','No page plan exists. An illustrated story product with no page plan cannot be previewed.',
      'route','thylora_product_page_plan'));
  end if;

  -- Unresolved page questions, named one page at a time.
  problems := problems || coalesce((
    select jsonb_agg(jsonb_build_object(
      'code','PAGE_UNRESOLVED_' || upper(q.col),
      'detail', coalesce(p.page_label, 'page ' || p.page_index) || ' does not resolve ' || q.label || '.',
      'route','thylora_product_page_plan.' || q.col))
    from thylora_product_page_plan p
    cross join lateral (values
      ('who_is_here','WHO IS HERE'), ('where_are_they','WHERE ARE THEY'),
      ('when_is_it','WHEN IS IT'), ('what_are_they_doing','WHAT ARE THEY DOING'),
      ('objects_present','WHAT OBJECTS ARE PRESENT'),
      ('object_makers','WHO MADE / SUPPLIED IMPORTANT OBJECTS'),
      ('background_action','WHAT IS HAPPENING IN THE BACKGROUND'),
      ('light_weather','WHAT LIGHT / WEATHER'),
      ('world_signature','WHAT MAKES THIS EDEREARIAH'),
      ('text_region','WHERE TEXT LIVES'),
      ('differs_from_previous','WHY THIS PAGE LOOKS DIFFERENT FROM THE PREVIOUS ONE')
    ) as q(col,label)
    where p.product_code = p_product_code
      and coalesce(btrim(to_jsonb(p) ->> q.col), '') = ''), '[]'::jsonb);

  -- White page dominance without a justified exception.
  if exists (select 1 from thylora_product_page_plan
             where product_code = p_product_code and white_page_dominant
               and coalesce(artistic_exception_justification,'') = '') then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','WHITE_PAGE_DOMINATES',
      'detail','One or more pages are dominantly white with no documented artistic exception.',
      'route','thylora_product_page_plan.artistic_exception'));
  end if;

  -- Text as the main visual. No recorded ratio is also a FAIL.
  select avg(illustration_area_ratio) into mean_ratio
  from thylora_product_page_plan
  where product_code = p_product_code and illustration_area_ratio is not null;

  if n_pages > 0 and mean_ratio is null and illustrated then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','TEXT_IS_THE_MAIN_VISUAL',
      'detail','No page records how much of itself is illustration, so text dominance cannot be ruled out. Fail-closed.',
      'route','thylora_product_page_plan.illustration_area_ratio'));
  elsif mean_ratio is not null and mean_ratio < 0.5 then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','TEXT_IS_THE_MAIN_VISUAL',
      'detail','Illustration occupies ' || round(mean_ratio*100) || '% of the average page. Text is the main visual.',
      'route','thylora_product_page_plan.illustration_area_ratio'));
  end if;

  -- Meaningful illustration.
  if illustrated and n_pages > 0 and not exists (
      select 1 from thylora_product_page_plan
      where product_code = p_product_code and coalesce(illustration_ref,'') <> '') then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_MEANINGFUL_ILLUSTRATION','detail','No page binds an illustration reference.',
      'route','thylora_product_page_plan.illustration_ref'));
  end if;
  if exists (select 1 from thylora_product_page_plan
             where product_code = p_product_code and illustration_carries_information is false) then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_MEANINGFUL_ILLUSTRATION',
      'detail','One or more pages record the illustration as carrying no information the text does not. That is decoration.',
      'route','thylora_product_page_plan.illustration_carries_information'));
  end if;

  -- Generic / unbound imagery.
  if exists (select 1 from thylora_product_page_plan
             where product_code = p_product_code
               and coalesce(illustration_ref,'') <> ''
               and coalesce(reference_binding,'') = '') then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','GENERIC_AI_ILLUSTRATION',
      'detail','One or more pages carry an illustration with no reference-image binding to an approved exemplar or a named source.',
      'route','thylora_product_page_plan.reference_binding'));
  end if;
  if coalesce(rec.generated_without_reference, false) then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','GENERIC_AI_ILLUSTRATION',
      'detail','The product records imagery generated with no reference binding. Unapproved imagery stays absent rather than entering the preview.',
      'route','THY-BUILD8-VISUAL-FLOOR-002'));
  end if;

  -- Authorship. OPEN on AUTHOR or ILLUSTRATOR is an honest gap that still blocks
  -- preview; it is reported as a Chairman decision, never filled with a name.
  select
    bool_or(role_code='AUTHOR'      and role_state='OPEN'),
    bool_or(role_code='ILLUSTRATOR' and role_state='OPEN'),
    bool_or(role_code='AUTHOR'      and role_state='RESOLVED'),
    bool_or(role_code='ILLUSTRATOR' and role_state='RESOLVED')
  into v_open_author, v_open_illus, v_res_author, v_res_illus
  from thylora_product_authorship where product_code = p_product_code;

  if not coalesce(v_res_author, false) then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_AUTHOR_IDENTITY',
      'detail', case when coalesce(v_open_author,false)
        then 'AUTHOR is explicitly OPEN. The gate does not invent a name; preview stays blocked until the Chairman names one.'
        else 'No author identity is resolved and none is explicitly OPEN.' end,
      'route', case when coalesce(v_open_author,false)
        then 'CHAIRMAN_DECISION: thylora_product_authorship.AUTHOR'
        else 'thylora_product_authorship.AUTHOR' end));
  end if;
  if illustrated and not coalesce(v_res_illus, false) then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_ART_IDENTITY',
      'detail', case when coalesce(v_open_illus,false)
        then 'ILLUSTRATOR is explicitly OPEN. The gate does not invent a name; preview stays blocked until the Chairman names one.'
        else 'No illustrator or art identity is resolved and none is explicitly OPEN.' end,
      'route', case when coalesce(v_open_illus,false)
        then 'CHAIRMAN_DECISION: thylora_product_authorship.ILLUSTRATOR'
        else 'thylora_product_authorship.ILLUSTRATOR' end));
  end if;
  problems := problems || coalesce((
    select jsonb_agg(jsonb_build_object(
      'code','UNRESOLVED_ROLE_' || r.role_code,
      'detail', r.role_code || ' is neither resolved nor explicitly OPEN.',
      'route','thylora_product_authorship.' || r.role_code))
    from (values ('AUTHOR'),('EDITOR'),('ILLUSTRATOR'),('DESIGNER'),
                 ('PUBLISHER_IMPRINT'),('PRODUCTION_HOUSE')) as r(role_code)
    where not exists (select 1 from thylora_product_authorship a
                      where a.product_code = p_product_code and a.role_code = r.role_code)),
    '[]'::jsonb);

  -- World-specific detail, background life, maker/source, page architecture.
  if illustrated and not exists (
      select 1 from thylora_product_page_plan
      where product_code = p_product_code and length(coalesce(world_signature,'')) >= 12) then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_WORLD_SPECIFIC_DETAIL',
      'detail','No page names a specific location, object or person that belongs to this world and no other.',
      'route','thylora_product_page_plan.world_signature'));
  end if;
  if illustrated and n_pages > 0 and not exists (
      select 1 from thylora_product_page_plan
      where product_code = p_product_code and coalesce(background_action,'') <> '') then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_BACKGROUND_LIFE',
      'detail','No page records anything happening behind the main subject.',
      'route','thylora_product_page_plan.background_action'));
  end if;
  if exists (select 1 from thylora_product_page_plan
             where product_code = p_product_code and coalesce(objects_present,'') <> '')
     and not exists (select 1 from thylora_product_page_plan
             where product_code = p_product_code and coalesce(object_makers,'') <> '') then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_MAKER_SOURCE_DETAIL',
      'detail','Objects are present on the pages but no page records who made or supplied them.',
      'route','thylora_product_page_plan.object_makers'));
  end if;
  if n_pages > 0 and not exists (
      select 1 from thylora_product_page_plan
      where product_code = p_product_code and coalesce(text_region,'') <> '') then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','NO_PAGE_ARCHITECTURE','detail','No page declares where its text lives.',
      'route','thylora_product_page_plan.text_region'));
  end if;

  -- Page-to-page repetition.
  if illustrated and n_pages >= 2 then
    if (select count(distinct lower(composition_signature)) from thylora_product_page_plan
        where product_code = p_product_code and coalesce(composition_signature,'') <> '') <= 1 then
      problems := problems || jsonb_build_array(jsonb_build_object(
        'code','REPEATED_COMPOSITION',
        'detail','Pages do not vary their composition signature, or do not record one at all. Fail-closed.',
        'route','thylora_product_page_plan.composition_signature'));
    end if;
  end if;

  -- Lesson handout, price/value, visual-story match, world depth.
  if coalesce(rec.reads_as_lesson_handout, false) then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','READS_AS_LESSON_HANDOUT',
      'detail','The product is recorded as reading like a lesson handout rather than a story.',
      'route','thylora_product_visual_record.reads_as_lesson_handout'));
  end if;
  if coalesce(rec.price_minor_units, 0) > 0 and coalesce(rec.price_value_basis,'') = '' then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','PRICE_VALUE_UNEXPLAINED',
      'detail','The product carries a price with no recorded basis for its value.',
      'route','thylora_product_visual_record.price_value_basis'));
  end if;
  if rec.visual_matches_story is false then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','VISUAL_STORY_MISMATCH','detail','The bound visual is recorded as not matching the product story.',
      'route','thylora_product_visual_record.visual_matches_story'));
  end if;
  if illustrated and coalesce(rec.story_summary,'') = '' then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','VISUAL_STORY_MISMATCH',
      'detail','No product story is recorded, so the visual cannot be shown to match it. Fail-closed.',
      'route','thylora_product_visual_record.story_summary'));
  end if;
  if illustrated and n_pages > 0 and not exists (
      select 1 from thylora_product_page_plan
      where product_code = p_product_code and world_continues_beyond_subject is true) then
    problems := problems || jsonb_build_array(jsonb_build_object(
      'code','WORLD_STOPS_AT_SUBJECT',
      'detail','No page records the world continuing beyond the main subject.',
      'route','thylora_product_page_plan.world_continues_beyond_subject'));
  end if;

  return jsonb_build_object(
    'ok', true,
    'gate_code','THY-VISUAL-QUALITY-GATE-001',
    'product_code', p_product_code,
    'gate_state', case when jsonb_array_length(problems) = 0 then 'PASS' else 'FAIL' end,
    'ready_for_chairman_preview', jsonb_array_length(problems) = 0,
    'evaluated_pages', n_pages,
    'problems', problems,
    'chairman_blockers', coalesce((
      select jsonb_agg(p) from jsonb_array_elements(problems) p
      where p->>'route' like 'CHAIRMAN_DECISION%'), '[]'::jsonb),
    'evaluated_at', now());
end $fn$;

-- 6 · Fail-closed preview admission. DRAFT -> QUALITY_GATE -> PASS -> CHAIRMAN_PREVIEW.
--     A FAIL returns internally for repair and is never shown to the Chairman.
create or replace function thylora_preview_admission_v1(p_product_code text)
returns jsonb language plpgsql volatile security definer set search_path = public as $fn$
declare
  gate jsonb;
begin
  if not (thylora_is_chairman() or thylora_is_trusted_server()) then
    return jsonb_build_object('ok', false,
      'reason','CHAIRMAN_ONLY: thylora_preview_admission_v1 is callable by the Chairman or a trusted server only.');
  end if;

  gate := thylora_visual_gate_evaluate_v1(p_product_code);
  if coalesce((gate->>'ok')::boolean, false) is not true then
    return gate;
  end if;

  insert into thylora_visual_gate_checks (product_code, gate_state, problems, evaluated_by)
  values (p_product_code, gate->>'gate_state', gate->'problems', auth.uid());

  if gate->>'gate_state' = 'PASS' then
    return jsonb_build_object('ok', true, 'from_state','QUALITY_GATE',
      'to_state','CHAIRMAN_PREVIEW', 'shown_to_chairman', true,
      'returned_for_repair', false, 'gate', gate);
  end if;

  return jsonb_build_object('ok', true, 'from_state','QUALITY_GATE',
    'to_state','FAIL', 'shown_to_chairman', false, 'returned_for_repair', true,
    'repair_route','INTERNAL_REPAIR', 'gate', gate);
end $fn$;

-- 7 · Soft link into the existing preview packet table, guarded. The live schema
--     could not be inspected from this session, so this degrades instead of
--     failing to apply if the table is absent or differently shaped.
do $$
begin
  if to_regclass('public.thylora_chairman_preview_packets') is not null then
    execute $v$
      create or replace view thylora_preview_packets_gated_v1 as
      select p.*,
             coalesce(g.gate_state, 'NOT_EVALUATED') as visual_gate_state,
             (coalesce(g.gate_state,'NOT_EVALUATED') = 'PASS')
               as visual_preflight_passed_evidenced,
             g.evaluated_at as visual_gate_evaluated_at,
             coalesce(g.problems, '[]'::jsonb) as visual_gate_problems
      from thylora_chairman_preview_packets p
      left join lateral (
        select c.gate_state, c.evaluated_at, c.problems
        from thylora_visual_gate_checks c
        where c.product_code = p.packet_code
        order by c.evaluated_at desc limit 1) g on true
    $v$;
  end if;
end $$;

-- 8 · Bramble binding. The work code is bound to this gate; no Bramble content,
--     page or illustration is authored here, and no authorship name is invented.
create table if not exists thylora_visual_gate_bindings (
  work_code   text primary key,
  gate_code   text not null default 'THY-VISUAL-QUALITY-GATE-001',
  bound_note  text not null,
  created_at  timestamptz not null default now()
);
insert into thylora_visual_gate_bindings (work_code, gate_code, bound_note) values
 ('THY-WORK-BRAMBLE-PROOF-PRODUCT-544','THY-VISUAL-QUALITY-GATE-001',
  'Bramble is not rebuilt independently of this standard. Any Bramble manuscript or page plan is checked against the recovered exemplars and the 1930s-1940s era lock (THY-VIS-EXEMPLAR-003) before it returns to the Chairman. Authorship for Bramble is OPEN on all six roles; no name is invented to clear the gate.')
on conflict (work_code) do update set
  gate_code = excluded.gate_code, bound_note = excluded.bound_note;

alter table thylora_product_page_plan       enable row level security;
alter table thylora_product_authorship      enable row level security;
alter table thylora_product_visual_record   enable row level security;
alter table thylora_visual_gate_checks      enable row level security;
alter table thylora_visual_gate_bindings    enable row level security;

revoke all on function thylora_visual_gate_evaluate_v1(text) from public;
revoke all on function thylora_preview_admission_v1(text)    from public;
grant execute on function thylora_visual_gate_evaluate_v1(text) to authenticated;
grant execute on function thylora_preview_admission_v1(text)    to authenticated;

commit;
